banzaicloud/pipeline

- cloud/aws.go
- main.go
- vendor/github.com/kris-nova/kubicorn/apis/cluster/instanceprofile.go
- vendor/github.com/kris-nova/kubicorn/apis/cluster/serverpool.go
- vendor/github.com/kris-nova/kubicorn/bootstrap/amazon_k8s_ubuntu_16.04_master_pipeline.sh
- vendor/github.com/kris-nova/kubicorn/bootstrap/amazon_k8s_ubuntu_16.04_node_pipeline.sh
- vendor/github.com/kris-nova/kubicorn/bootstrap/bootstrap.go
- vendor/github.com/kris-nova/kubicorn/cloud/amazon/awsSdkGo/sdk.go
- vendor/github.com/kris-nova/kubicorn/cloud/amazon/public/model.go
- vendor/github.com/kris-nova/kubicorn/cloud/amazon/public/resources/instanceprofile.go
- vendor/github.com/kris-nova/kubicorn/cloud/amazon/public/resources/launchconfiguration.go
- vendor/github.com/kris-nova/kubicorn/cloud/atomic_reconciler.go
Add InstanceProfile feature for AWS. This enables Kubernetes features like: Automatic ELB allocation, PVC handling, etc. 
- New model element: InstanceProfile
- New resource element: InstanceProfile
- Supports Add/Delete/Update InstanceProfile
- Add InstanceProfile to LaunchConfiguration if present
- Manage InstanceProfile - Role - Policy together
- Add Cloud specific configuration to Bootstrap scripts
> Add instance profile support

- .circleci/config.yml
the command docker images need docker hub auth for pushed-images ?!
> fix circle-ci PR check

- cloud/aws.go
- cloud/base.go
- cloud/utils.go
- helm/helm.go
- helm/kubernetes.go
- main.go
Assuming that kubeconfig can be stored in various places (db, key value store, file) pass the config content to methods that need kubernetes config instead of the path the file that caches the config
> Fix: pass kubeconfig to CreateDeployment instead of path to kubeconfig [PIP-26]

- cloud/cluster.go
Although k8s tags with `KubernetesCreated` the SG it fails to remove when an LB (ELB) is removed. This fix is a temporary solution until it's fixed upstream (or we shall make a fix/pr for k8s).
> Add AWS cluster garbage collection to ELB security groups

- main.go
Without this fix, if the cluster create succeeded but the tiller install failed, the delete cluster returns 500 with could not find tiller. This fix allows to delete cluster even if tiller is not installed.
> Fix cluster delete, delete cluster when tiller is not available

- cloud/azure.go
Save cluster to database before polling in case of Azure. So you can delete the cluster from pipeline if there's a failure in creation.
> Cluster save fix

- auth/authn.go
- auth/user.go
- config/config.toml.example
- config/configuration.go
- db-init.sql
- docker-compose-local.yml
- glide.lock
- glide.yaml
- model/database.go
- vault-enable-database.sh
- vendor/github.com/banzaicloud/bank-vaults/database/database.go
This needs some changes in the helm charts to be able to use it on the supported cloud providers, but currently, it is turned on if one defines the
```toml
[database]
role = "pipeline"
```
It is possible to use it locally, otherwise, it falls back to the good old static password based connection.
> Dynamic database secrets

- auth/authn.go
- auth/user.go
- config/configuration.go
This PR adds a logic to user registration to trigger Drone user repository synchronization, so when a users logs in at the first time his/her repos will be there on the Drone UI.
> Synchronize Drone repositories on register

- model/defaults/gke.go
`1.8.7-gke.1` master version is no longer supported by Google. Current default cluster version is `1.8.8-gke.0`.
> Update default gke master/node version

- auth/authn.go
`/auth/logout` is the logout endpoint.
> Logout extended with Drone logout

- auth/user.go
* the default orgname is set to the user's GitHub username to align the behaviour with "real" orgs
> fixed default org name

- auth/authn.go
- auth/github.go
- main.go
Also it is possible now to request Pipeline API tokens via Github Tokens
The auth installation is now more libraryfied
Usage (with HTTPie):
```bash
http http://localhost:9090/auth/github/callback?access_token=$GITHUB_TOKEN
http POST http://localhost:9090/auth/tokens?access_token=$GITHUB_TOKEN
```
> Make registration possible via Github Access Tokens

- _config.yml
We have this [dep](https://github.com/golang/dep/issues/1820) issue with non-go files while prune-ing (dep ensure actually). This triggers the page build failures we wanted to address with #452
> Revert until dep prune is fixed

- secret/store.go
> Secret tags should be sorted because binary search is applied on them

- api/secrets.go
- docs/openapi/pipeline.yaml
- secret/store.go
Instead of:
```json
{
"secrets": [
{...}
]
}
```
Now we return (as in `/clusters` and `/tokens` ....)
```json
[
{...}
]
```
> Secret list JSON body unwrapped

- auth/authz.go
This fix is needed to allow all logged in users to list allowed secret types.
> Fix allowed/secrets authz in Casbin

- scripts/get-token.sh
To get a Pipeline token in exchange for a Github access token, only for developer mode.
> Add get-token.sh

- client/examples/auth/main.go
- config/configuration.go
Also skip auditing the unauthenticated meta endpoint, because that is used in the Kubernetes health check, thus called in every 10 seconds.
> Add TLS snippet to a auth client example

- api/cluster.go
- api/helm.go
- cluster/common.go
- cluster/hooks.go
Cluster becomes `RUNNING` after:
- it is created on the cloud provider
- all post hooks have finished without errors
If the post hooks fail, the remaining posthooks aren't executed, and the state becomes ERROR. With the already existing rerun posthooks API call a user or an automation can trigger the post hook run again and promote the cluster into `RUNNING` state (healthy).
---
Also, there was a race condition during the cluster config downloading. The `getConfig` call shouldn't change the database, because the `StoreKubeConfig` posthook function also changes it, and there could be a state where none of those methods could finish correctly (and we end up without any configuration).
---
Fixes: #711
> Cluster Creation status reordering

- Gopkg.lock
- api/cluster.go
- audit/audit.go
- cluster/common.go
- cluster/proxy.go
- main.go
- vendor/github.com/mxk/go-flowrate/LICENSE
- vendor/github.com/mxk/go-flowrate/flowrate/flowrate.go
- vendor/github.com/mxk/go-flowrate/flowrate/io.go
- vendor/github.com/mxk/go-flowrate/flowrate/util.go
- vendor/k8s.io/apimachinery/pkg/util/proxy/dial.go
- vendor/k8s.io/apimachinery/pkg/util/proxy/doc.go
- vendor/k8s.io/apimachinery/pkg/util/proxy/transport.go
- vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
This endpoint lets you proxy into a provisioned Kubernetes cluster's API server through Pipeline (thus authenticated via our auth mechanism).
A possible use case is for example proxy the Kubernetes Dashboard through Pipeline:
http://localhost:9090/pipeline/api/v1/orgs/2/clusters/61/proxy/api/v1/namespaces/kube-system/services/https:dashboard-kubernetes-dashboard:/proxy
> Cluster proxy endpoint

- auth/authn.go
> repo:status GitHub scope is redundant

- cluster/gke.go
Overwrite the versions with the current GKE master/node version after create/update cluster to avoid unnecessary `UPGRADE_MASTER` and `UPGRADE_NODES` operations.  This happen when user uses `major.minor` version format in the requests.
> Save current GKE versions after create/update cluster

- Makefile
- cluster/gke.go
Fixes: 
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1effb67]
goroutine 11322 [running]:
github.com/banzaicloud/pipeline/cluster.(*GKECluster).CreateCluster(0xc420766aa0, 0x0, 0x0)
/go/src/github.com/banzaicloud/pipeline/cluster/gke.go:224 +0x657
github.com/banzaicloud/pipeline/api.postCreateCluster(0x2c70fe0, 0xc420766aa0, 0x0, 0x0, 0x0, 0x0, 0xc422057490)
/go/src/github.com/banzaicloud/pipeline/api/cluster.go:317 +0x77
created by github.com/banzaicloud/pipeline/api.CreateCluster
/go/src/github.com/banzaicloud/pipeline/api/cluster.go:293 +0xf69```
> Fix alreadyExists error handling on GKE

- config/configuration.go
- dns/externaldns.go
- dns/route53/dbstatestore.go
- dns/route53/event.go
- dns/route53/hostedZone.go
- dns/route53/iamUser.go
- dns/route53/operation.go
- dns/route53/policy.go
- dns/route53/route53.go
- dns/route53/route53_test.go
- dns/route53/statestore.go
- main.go
This implementation solely handles the finishing of incomplete tasks running against Route53 in case of a Pipeline restart.
It's separate work to make already created clusters aware of the completion of unfinished Route53 tasks.
> Finish uncompleted Route53 tasks on startup in background

- internal/gin/correlationid/middleware.go
- main.go
This PR adds a gin correlation ID middleware accepting a custom correlation ID from a header or generating a new one (UUID).
This ID can be used later on for logging/error handling/tracing.
> Add correlation ID middleware

- .gitignore
- .idea/go.imports.xml
This PR makes idea to format go imports.
Example:
```go
import (
"bytes"
"errors"
"fmt"
"localPackage"
"golang.org/x/tools/cmd/gotype"
"appengine"
"github.com/dlsniper/go-metrics"
)
```
Rules:
- one import block
- stdlib imports are grouped
> Add go import rules to idea config

- .idea/runConfigurations/Check.xml
- .idea/runConfigurations/Lint.xml
This PR adds a Lint build config for running the linter and a Check compound config for running both tests and the linter. Comes handy right before committing code.
> Add lint and check compound build config to idea

- .idea/runConfigurations/Check.xml
I propose that we remove this config from the repo. It causes more problem than it helps. It can easily be added back to the local workspace.
> Remove Check build config

- config/configuration.go
* Fix regression from #895: AllowOrigins option became unreachable
* Use whole string matching instead of substring matching for AllowOriginsRegexp as it is not intuitive and exposes a potential security risk
> Fix cors.AllowOrigin* config parsing

- config/config.toml.example
> Add missing github token from config example

- Gopkg.lock
- Gopkg.toml
- config/error_handler.go
- config/logger.go
- internal/platform/log/config.go
- internal/platform/log/logger.go
- main.go
- spotguide/spotguide.go
This PR adds the concept of "error handler" mentioned in [Error handling practices in Go](https://banzaicloud.com/blog/error-handling-go/) to Pipeline.
Instead of logging errors using logrus an error that we cannot gracefully handle should be passed to the error handler. The underlying handler implementation in turn will pass the error to logrus, but it also gives us the ability to use any third-party error tracking service or whichever way we want to handle errors. Conceptually logging is one way to "handle" an error.
Here is an example of the log (adds file and line information):
```
time="2018-08-30T15:13:14+02:00" level=error msg="failed to scrape Spotguide repositories: failed to list github repositories: GET https://api.github.com/orgs/banzaicloud/repos?per_page=100: 401 Bad …
```
> Introduce error handling concept

- client/README.md
- client/api/openapi.yaml
- client/api_spotguides.go
- client/docs/SpotguidesApi.md
- docs/openapi/pipeline.yaml
Duplicate key masked out one of the endpoints. Error message from [swagger editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/banzaicloud/pipeline/master/docs/openapi/pipeline.yaml):
Parser error duplicated mapping key / Jump to line 67
> Fix syntax of openapi description

- internal/providers/amazon/objectstore.go
- pkg/objectstore/objectstore.go
- pkg/providers/amazon/objectstore/objectstore.go
Fixes #973 
It will return the list of the buckets enhanced by the location.
```
{   "name": "your-mysql-backup",
"managed": false,
"location": "us-west-1"
},
{
"name": "zeppelin-sample-notebooks",
"managed": false,
"location": "us-west-2"
},
```
> Add location info to bucket list endpoint in case of Amazon

- client/README.md
- client/api/openapi.yaml
- client/docs/CreateEksPropertiesEks.md
- client/docs/CreateEksPropertiesEksMaster.md
- client/docs/CreateUpdateDeploymentRequest.md
- client/model_create_eks_properties_eks.go
- client/model_create_eks_properties_eks_master.go
- client/model_create_update_deployment_request.go
- docs/openapi/pipeline.yaml
Allow string values in items of CreateUpdateDeploymentRequest.Values. 2+ level maps were enforced, which made impossible to decode examples like
`"values":{"appVersion":"0.8.1","image":{"repository":"banzaicloud/drone",`...
> Fix OpenApi spec of CreateUpdateDeployment.Values

- api/helm.go
- client/api/openapi.yaml
- client/docs/ListDeploymentsResponseInner.md
- client/model_list_deployments_response_inner.go
- docs/openapi/pipeline.yaml
- pkg/helm/helm.go
This marks deployments with `supported: true` if they were installed from a known Helm repository.
> Add supported flag to deployment listings

- model/defaults/base.go
- pkg/providers/oracle/model/profile.go
Currently table names are quite inconsistent. Some are grouped by feature, some are grouped by cloud provider. Personally I find the latter better as it follows the group by provider logic that we apply in the code as well.
> Rename profile tables

- dns/route53/model/route53domain.go
Merge directly before release and rename the table manually so no records get lost on beta.
> Rename route53 domain table

- spotguide/spotguide.go
if not specified in the request (we are using latest version).
> Fix missing version in spotguide.LaunchRequest

- helm/helm.go
ListDeployments listed only deployments in DEPLOYED state giving no
feedback for example about failed ones (causing releaseName conflicts that are unresolvable form the ui)
Fixes #1056
> helm: list all active deployments

- api/bucket.go
- cluster/manager_create.go
- cluster/manager_delete.go
- cluster/manager_update.go
Since we don't want panics in long running processes to stop
Pipeline, these panics must be handled locally.
> Handle panics in long running processes

- api/bucket.go
- api/bucket_messages.go
- api/cluster_create.go
- client/api/openapi.yaml
- client/docs/CreateClusterRequest.md
- client/docs/CreateObjectStoreBucketRequest.md
- client/docs/LoggingPostHookInstallLogging.md
- client/model_create_cluster_request.go
- client/model_create_object_store_bucket_request.go
- client/model_logging_post_hook_install_logging.go
- cluster/hooks.go
- docs/openapi/pipeline.yaml
- pkg/cluster/base.go
This PR makes it possible to pass in secretId or secretName (only one is required) in requests where a secret reference is required. This makes the API a bit more user-friendly and simpler.
Fixes: https://github.com/banzaicloud/pipeline/issues/1091
> secretName support

- internal/platform/gin/drain.go
- main.go
This is a temporary solution for pipeline deployments maintenance mode. It will probably become obsolete when cluster management workflows become durable.
Usage:
Enable drain mode: `curl -X POST http://localhost:9090/-/drain`
Disable drain mode: `curl -X DELETE http://localhost:9090/-/drain`
Note: The middleware disables operations that might change state (POST, PUT, PATCH, DELETE), but it might also break features which use these HTTP methods, but don't change state (eg. authentication).
> Add drain mode middleware

- spotguide/spotguide.go
When the version tag is moved under a GitHub release, spotguide repo scraping will update the repositories `spotguide.yaml` in the database.
> Support spotguide version/tag move when scraping

- cluster/acsk.go
- cluster/aks.go
- cluster/common.go
- cluster/eks.go
- internal/providers/alibaba/objectstore_model.go
- internal/providers/google/gke_cluster_model.go
- internal/providers/oracle/objectstore_model.go
- model/cluster.go
- model/defaults/aks.go
- model/defaults/amazon.go
- model/defaults/base.go
- model/defaults/gke.go
- pkg/providers/oracle/model/cluster.go
- pkg/providers/oracle/model/profile.go
Upgrade migrations:
```sql
/* Clusters */
/* Alibaba */
ALTER TABLE alibaba_cluster_properties RENAME TO alibaba_acsk_clusters;
ALTER TABLE alibaba_acsk_clusters CHANGE COLUMN cluster_id provider_cluster_id VARCHAR(255);
ALTER TABLE alibaba_acsk_clusters CHANGE COLUMN cluster_model_id cluster_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE alibaba_node_pools RENAME TO alibaba_acsk_node_pools;
ALTER TABLE alibaba_acsk_node_pools CHANGE COLUMN cluster_model_id cluster_id INT(10) UNSIGNED DEFAULT NULL;
ALTER TABLE alibaba_acsk_node_pools RENAME INDEX idx_modelid_name TO idx_cluster_id_name;
/* EC2 */
ALTER TABLE amazon_cluster_properties RENAME TO amazon_ec2_clusters;
ALTER TABLE amazon_ec2_clusters CHANGE COLUMN cluster_model_id cluster_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT; …
```
> DB Schema improvements

- cluster/secrets.go
The wrong request was sent in cases when the secret wasnt installed
already.
> secrets: fix install secrets

- Makefile
- api/bucket.go
- client/api/openapi.yaml
- client/api_storage.go
- client/docs/StorageApi.md
- docs/openapi/pipeline.yaml
- internal/objectstore/objectstore.go
- internal/providers/alibaba/objectstore.go
- internal/providers/alibaba/objectstore_model.go
- internal/providers/amazon/objectstore.go
- internal/providers/amazon/objectstore_model.go
- internal/providers/azure/objectstore.go
- internal/providers/azure/objectstore_model.go
- internal/providers/google/objectstore.go
- internal/providers/google/objectstore_model.go
- internal/providers/objectstore.go
- internal/providers/oracle/objectstore.go
- internal/providers/oracle/objectstore_model.go
- main.go
- pkg/providers/amazon/objectstore/objectstore.go
- secret references are stored along with the buckets in the database (new column in cloud specific object store tables)
- when no secretId header is found in the request headers all managed buckets are returned (no filtering support by the backend - if required, to be added later)
- if secretId header is found fallback to the "original" behaviour
- basic (manual) testing on all supported providers
fixes #1082
> Support for listing managed buckets only

- spotguide/dronerepoconfig.go
The YAML marshaller parsed different types as the JSON parser, so the merging couldn't happen.
> spotguide json marshaling fix

- api/cluster.go
If the URL query param `field` was set to someting else then `id`or `name` the following panic occured:
```
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:513 (0x42cee8)
/usr/local/go/src/runtime/panic.go:82 (0x42c03d)
/usr/local/go/src/runtime/signal_unix.go:390 (0x442271)
/go/src/github.com/banzaicloud/pipeline/api/helm.go:52 (0x252ed08)
/go/src/github.com/banzaicloud/pipeline/api/helm.go:118 (0x252f8f2)
/go/src/github.com/banzaicloud/pipeline/vendor/github.com/gin-gonic/gin/context.go:107 (0x965732)
/go/src/github.com/banzaicloud/pipeline/api/organization.go:62 (0x253bb2a)
/go/src/github.com/banzaicloud/pipeline/vendor/github.com/gin-gonic/gin/context.go:107 (0x965732)
/go/src/github.com/banzaicloud/pipeline/internal/platform/gin/drai …
```
> Return error in case of unsupported field query value

- .circleci/config.yml
- .dockerignore
- .gitignore
- Makefile
- docker-compose.override.yml.dist
- docker-compose.yml
- main.go
This PR contains several improvements to the project's Makefile.
Backward incompatible changes:
```
make local      > make start
make local-kill > make stop
make build-ci   > GOOS=linux make build
```
There are also some changes in the docker-compose.yml file: the port mappings are moved to an uncommited override file. The file can be created using `make docker-compose.override.yml`, but `make start` also creates it.
For the first time you might also want to edit the generated override file manually as it relocates the mysql volume which removes your original database.
To avoid it just remove this section from the override file:
```yaml
volumes:
- ./.docker/volumes/mysql:/var/lib/mysql
```
> Improve makefile

- api/security.go
- client/api/openapi.yaml
- client/docs/ReleaseWhiteListItem.md
- client/model_release_white_list_item.go
- docs/openapi/pipeline.yaml
- pkg/security/security.go
ReleaseName isn't necessary to declare in WhitelistItem Spec, it's removed.
fixes: #14
> Remove releaseName from WhitelistItem Spec

- cluster/gke.go
- internal/providers/google/gke_cluster_model.go
- pkg/cluster/gke/gke.go
- pkg/secret/secret.go
- spotguide/spotguide_test.go
- project id saved as a new field in the cluster
- if not provided in the request the project id is taken from the secret
- project id in the secret is made optional
(please review - with focus on any other flows where the cluster specific project needs to be used)
> Project id saved along with the cluster on google

- auth/migrate.go
- config/config.toml.example
- config/configuration.go
- dns/route53/model/migrate.go
- internal/ark/model.go
- internal/audit/model.go
- internal/cluster/model.go
- internal/providers/alibaba/model.go
- internal/providers/amazon/model.go
- internal/providers/azure/model.go
- internal/providers/google/model.go
- internal/providers/oracle/model.go
- main.go
- migrate.go
- model/defaults/migrate.go
- model/migrate.go
- spotguide/migrate.go
This PR disables automatic migration of database schema by default.
To enable it locally add the following line to your config's database section:
```
autoMigrateEnabled = true
```
> Disable schema automigration

- Gopkg.lock
- auth/github.go
- auth/user.go
Currently, we store the first OAuth access token returned by GitHub, further logins create a new OAuth access token and there is a limit (sliding window, around 10 tokens if I counted correctly) for working issued OAuth tokens in Github (and in e.g.: Google as well): https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#creating-multiple-tokens-for-oauth-apps
This fix resolves this issue by refreshing this token in Vault and in Drone at every login flow.
> Update GitHub OAuth access token at further logins

- Gopkg.toml
- config/config.toml.example
- config/configuration.go
- spotguide/spotguide.go
This follows the rules of semantic versioning, pre-releases are not visible by default.
> spotguide release tags can be filtered by pre-releases

- cluster/oke.go
- pkg/providers/oracle/cluster/manager/cluster.go
- pkg/providers/oracle/cluster/manager/nodepool.go
- pkg/providers/oracle/oci/ce_cluster.go
- pkg/providers/oracle/oci/ce_nodepool.go
- Remove the preconfigured VCN if cluster creation request validation fails
- Return node errors raised during node pool manipulations
- Trying to get OKE cluster by it's name if OCID is empty
- Fix node pool config persistance in case of an error
Fixes #1284 and #1285
> OKE enhancements

- .vscode/launch.json
main.go was located under `./cmd/pipeline`, so the `.vscode/launch.json` has to follow it.
> Align .vscode config to new main.go location

- cluster/aks.go
> Fix ClusterDetails API call to hold information about Kubernetes version

- api/bucket.go
- docs/openapi/pipeline.yaml
- internal/providers/amazon/objectstore.go
- internal/providers/azure/objectstore.go
- internal/providers/google/objectstore.go
- internal/providers/objectstore.go
- internal/providers/oracle/objectstore.go
- the operation accesses the provider only when it makes sense (the bucket is in the state created, or deletion failed)
- added `force` query parameter to be able to force the deletion (the buclket is wiped from the pipeline db)
> amended delete bucket operation

- cluster/acsk.go
- cluster/eks.go
- cluster/kubernetes.go
This helps to prevent issues when trying to cross-mount EBS Volumes across zones.
https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
> Use VolumeBindingWaitForFirstConsumer in EKS and ACSK when creating the default StorageClass

- Gopkg.lock
- Gopkg.toml
- config/config.toml.example
Adds `Gopkg.toml` Kubernetes vendoring clenaup as well.
> Bump Helm version to 2.11 and Kubernetes to 1.11

- api/bucket.go
- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/BucketInfoSecret.md
- client/model_bucket_info_secret.go
- database/migrations/1542019624_objectstore_azure_accesssecret_field.down.sql
- database/migrations/1542019624_objectstore_azure_accesssecret_field.up.sql
- docs/openapi/pipeline.yaml
- internal/objectstore/objectstore.go
- internal/providers/azure/objectstore.go
- internal/providers/azure/objectstore_model.go
* bucket model extended with the access-secret reference (azure only)
* list managed buckets and get bucket calls return the access secret too (with the include=secret query passed also the name of secrets is returned)
* started the cleanup of error handling (azure mainly); context and logging need more elaboration
* added database schema modifier scripts
* openapi changes
Tested mainly on azure, other providers underway (no breaking changes though)
fixes #1336
> support for access secret (on azure)

- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/GetClusterStatusResponse.md
- client/model_get_cluster_status_response.go
- cluster/eks.go
- cluster/hooks.go
- docs/openapi/pipeline.yaml
- pkg/cluster/base.go
The new flag signals if the cluster has at least one node pool with spot instances configured.
This is needed for the UI implementation of setting "minimum on-demand percentages for replicas".
The GKE implementation will need to be updated once we have [this PR](https://github.com/banzaicloud/pipeline/pull/1352) merged.
Example cluster status call:
GET {{url}}/api/v1/orgs/:orgId/clusters/:clusterId
```
{
"status": "ERROR",
"statusMessage": "failed to create kubernetes tunnel: Unauthorized",
"name": "ekscluster-marton-177",
"location": "us-east-1",
"cloud": "amazon",
"distribution": "eks",
*   "spot": true,
"version": "1.10",
"id": 45,
"nodePools": {
"pool1": {
"count": 1,
"instanceType": "m5.xlarge",
"spotPrice": "0",
"minCount": 1,
"maxCount": 1,
"image": "ami-0440e4f6b9713faf6"
}, …
```
> Add `spot` flag to cluster status response

- api/bucket.go
- database/migrations/1542019624_objectstore_azure_accesssecret_field.up.sql
* new way of handling query parameters (ease parsing, validation)
* cleaned the getBucket implementation
* bucket filtering done at "controller" level (possibly to be moved later to the database query layer)
* tested manually (mainly azure)
fixes #1315
> Get bucket call fixed to return only one item

- api/helm.go
- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/CreateUpdateDeploymentRequest.md
- client/model_create_update_deployment_request.go
- cluster/autoscale.go
- cluster/hooks.go
- docs/openapi/pipeline.yaml
- helm/helm.go
- internal/ark/deployments_svc.go
- pkg/helm/helm.go
From helm docs:
> if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment are in a ready state before marking the release as successful
It's fixing the issue with spot mutating webhook that didn't wait until the webhook started before moving on the next deployment.
When sending a create deployment request, it is now configurable on the API.
I've set wait to `false` for all default posthooks other then spot-config-webhook. It was the default before, and setting it to true may increase the cluster creation time.
> added wait option to create deployment

- Gopkg.lock
- spotguide/spotguide.go
So the repo can be linked to the original spotguide repo it was started from.
> Add source spotguide repo name to spotguide repos in Drone

- cluster/manager_delete.go
In more than one case the deletion of a cluster with monitoring timeouted because the deleted pipeline-system namespace was still in terminating state after 3 minutes.
> Wait more for namespace termination during cluster deletion

- internal/audit/middleware.go
some cosmetics and a fix around the audit middleware.
> audit: use ioutil.NopCloser instead of custom type

- Gopkg.lock
- api/cluster.go
- api/cluster_delete.go
- cluster/manager.go
- cluster/manager_delete.go
- cluster/proxy.go
- cmd/pipeline/main.go
> Refactor cluster API proxy handling

- cluster/common.go
- cluster/manager_delete.go
if the kubeconfig is not available, then we were not able to create
resources on the cluster, so we don't have to remove them. this makes it
possible to delete incomplete clusters on a controlled way (get a
feedback if the deletion of the cloud resources did not succeed)
~~I would like to get review about the idea before testing the proposed solution.~~
Tested with gke.
> cluster: allow non-force delete of incomplete clusters

- internal/security/anchore.go
path.Join removes multiple '/' from string in case of 'http://'
> Fix anchore URL in DoAnchoreRequest

- Gopkg.lock
- Gopkg.toml
- cluster/gke.go
- pkg/providers/google/iamSvc.go
Support the creation of GKE cluster with RBAC enabled.
The following additional roles needs to be granted to already existing Goolge Service Accounts used by Pipeline to provision the GKE clusters:
* Service Account Token Creator
* Service Account User
The Google project the GKE cluster is created under needs to be granted usage access to "IAM Service Account Credentials API"
fixes #424
> Enable RBAC for GKE clusters

- api/cluster_create.go
- cluster/hooks.go
- If anchore is enabled in Pipeline, anchore user will be created with ClusterCreate
- AnchoreImageValidator just install anchore-policy-validator helm package with right credentials
> Create anchore user during ClusterCreate instead of ImageValidator posthook

- internal/ark/backups_repository.go
- internal/ark/backups_svc.go
Overwrite ARK backup cluster ID in the backup list to the cluster ID of the active deployment
> Overwrite ARK backup cluster ID in the backup list

- cluster/gke.go
Before creating the final kube config
we create a temporary token which requires a default configuration.
This default configuration can either be a command path
or default gcloud config (which is why it worked locally
and on alpha environment, but not in minikube)
Since we don't actually use this feature because we use the SDK
to retrieve the temporary token, we can use fake command path.
> Fix temporary gcp default config

- Gopkg.lock
- Gopkg.toml
> Go API client uses pooled HTTP client: The Go API client now uses a connection-pooling HTTP client by default. For CLI operations this makes no difference but it should provide significant performance benefits for those writing custom clients using the Go API library. As before, this can be changed to any custom HTTP client by the caller.
https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#100-december-3rd-2018
> Update bank-vaults to use Vault client 1.0.x

- api/user.go
The DB should be queried to get all information for the current user, just as the `/orgs/N/users` endpoint lists them.
> Extend /me endpoint with all user info

- docs/postman/e2e_test.postman_collection.json
I tried to create an OKE cluster using the Postman collection and had a few issues when trying to use the values provided by default:
- I could not create a cluster with version: *v1.10.3* The response was: "Invalid k8s version". As far as I know, the valid versions in OKE right now are *v.1.10.11* and *v1.11.5*. It was working for me with **v.1.10.11**, so I changed to that.
- I could not create a cluster with shape: *VM.Standard1.1* Based on [cloudinfo](https://beta.banzaicloud.io/cloudinfo), the valid types in OKE right now are *VM.Standard2.1* and *VM.Standard2.2*. It was working for me with **VM.Standard2.1**, so I changed to that.
> Fix create oke cluster example values

- docs/migrations.md
Extended developer docs about migrations with the [golang-migrate](https://github.com/golang-migrate/migrate) tool.
> added section about golang-migrate to migration docs

- cluster/hookfunctions.go
- cluster/hooks.go
- pkg/cluster/base.go
- templates/eks/amazon-eks-vpc-cf.yaml
| Related tickets | fixes #1635 
Deploying the more general instance termination handler instead of the spot-termination-handler.
The more general instance termination handler also handles ondemand ASG managed EC2 instance termination and also supports Hollowtrees managed scaling by removing the EC2 instance from the ASG when a termination notice arrives.
!! Do not merge yet !!
It depends on https://github.com/banzaicloud/banzai-charts/pull/613
> Deploy instance-termination-handler instead of spot-termination-handler

- templates/eks/amazon-eks-vpc-cf.yaml
Removes an invalid S3 permission (ListObjects) from the CF template
> remove invalid S3 permission from CF template

- spotguide/spotguide.go
We should accept a Spotguide repo without readme or icon, these are not necessary for a functional Spotguide.
> feat: make spotguide readme and icon optional

- cluster/hooks_istio.go
- internal/istio/istio.go
Mutual TLS can be enabled in the Istio posthook, by setting the property `"mtls": true`.
It sets the corresponding property in Helm, that:
1. creates a mesh-wide authentication policy that specifies that all services in the mesh will only accept TLS requests.
2. creates a `DestinationRule` that configures the client-side part, so all internal requests will include a client certificate.
3. creates another `DestinationRule` that disables `mtls` to the Kubernetes API server.
> istio mtls configurable

- cluster/hooks_istio.go
- config/config.toml.example
- config/configuration.go
- dashboards/istio/galley-dashboard.json
- dashboards/istio/istio-mesh-dashboard.json
- dashboards/istio/istio-performance-dashboard.json
- dashboards/istio/istio-service-dashboard.json
- dashboards/istio/istio-workload-dashboard.json
- dashboards/istio/mixer-dashboard.json
- dashboards/istio/pilot-dashboard.json
- internal/istio/grafana.go
- Istio chart version is coming from config instead of going with the latest. (default: 1.0.5)
- Grafana dashboards are added to the project, their location is configurable (default is to read it from the local path `dashboards/istio`)
> configurable istio chart version and grafana dashboard location

- api/cluster.go
- cluster/hookfunctions.go
Posthooks got a priority so they can run in a specific order.
Default priority is 0, for now 2 posthooks got a priority: Security Scan and Service Mesh.
Security Scan posthook must run as the last posthook and we had an `if` statement for that before.
Service Mesh posthook must run after the Monitoring posthook.
> posthooks can be priorized

- Gopkg.lock
- cluster/eks.go
EKS creates default storage class if kubernetes version is 1.11 or higher
> Fixed the creation of the EKS default storage class

- cmd/pipeline/main.go
`GithubID` has to be saved alongside of name when inserting shared Spotguide org.
Several query in the application uses both `Name` and `GithubID` in the where clause.
> fix: save github ID as well

- spotguide/spotguide.go
| Related tickets | fixes #1641
Check the error code for `422` and return from the sync function.
The GitHub API respond is unexpected when the org doesn't have any repos, handle this case.
> fix: handle empty organizations on Spotguide sync

- api/cluster.go
- client/SHA256SUMS
- client/api/openapi.yaml
- docs/openapi/pipeline.yaml
- pkg/k8sutil/boot_token.go
Hotfix to make kubeadm compatible output
> fix masterAddress and Token properties

- docker-compose.yml
This restarts the cicd-server and agent always in the local dev environment and also specifies an exact image version for them.
> docker-compose: restart cicd always, fix image

- spotguide/spotguide.go
| Related tickets | fixes #1692 
> spotguide: fix SIGSEGV during scrape if resp is not available

- Dockerfile
- Dockerfile.dev
- Dockerfile.local
| Related tickets | fixes #1647 
Build EKS CF templates into the docker images.
These templates are closely related to the built code itself.
> Add EKS templates to docker images

- cluster/aks.go
| Related tickets | none
- Deleted method `retreiveAzureCluster()` because it had the same functionality as `getAzureCluster()` and it was never used in the codebase (`getAzureCluster()` is used four times)
-  Added implementation to `GetK8sIpv4Cidrs()` on AKS to be able to access external services (by [including internal IP ranges](https://istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly) only). The service and pod CIDR ranges are fetched using Azure's GO SDK.
The functionality to configure the `BypassEgressTraffic` variable was only added for GKE in #1643 and for EKS in #1701.
- Launched …
> Configure bypass egress traffic on AKS for Istio posthook

- internal/providers/network.go
- internal/providers/oracle/network.go
This PR implements the virtual network/subnetwork/route table querying API for Oracle.
Allow API users to query OKE VCN resources to simplify creating clusters in existing VCNs.
> WIP Oracle VCN query API

- cluster/manager_delete.go
- internal/providers/banzaicloud/ec2_cluster_model.go
This is a hot-fix to emit event on PKE cluster delete "_detach_"
> Hot-fix to emit delete event to manager

- pkg/providers/oracle/network/manager.go
Due to service expansion, the Container Engine for Kubernetes service will require new security list rules for customer clusters.
Although right now SSH access is allowed from anywhere, we better keep these provider network rules up to date
See https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengnetworkconfigexample.htm#exampleseclistconfig for a security list example.
> Expand OKE nodes security list

- internal/providers/network.go
- internal/providers/oracle/network.go
Use the provided `region` query parameter when listing VCNs.
I thought the region couldn't be specified, but it was pointed out to me, that it can.
> Oracle VCN query API fix

- Dockerfile
- Dockerfile.dev
- Dockerfile.local
This PR upgrades Alpine to the latest version and installs timezone info in every docker image.
Locally built docker images lacked the system timezone info.
> Upgrade alpine version and install tzdata in every docker image

- cluster/acsk.go
- pkg/cluster/acsk/template.go
| Related tickets | none
- Expand `AlibabaDescribeClusterResponse` struct with `SubnetCIDR` and `Parameters.ServiceCIDR` fields so that these fields can be parsed from such a JSON response. The highlight of this response is like the following:
```
{
"instance_type": "",
"name": "mesh1",
...
"subnet_cidr": "172.16.0.0/16",
...
"parameters": {
...
"ServiceCIDR": "172.19.0.0/20",
...
}
}
```
This is why the `SubnetCIDR` field is parsed directly from the root of the JSON response and why `ServiceCIDR` is parsed under the `Parameters` JSON key.
-  Added implementation to `GetK8sIpv4Cidrs()` on ACK to be able to access external …
> Configure bypass egress traffic on ACK for Istio posthook

- api/network.go
Filter empty CIDR strings from CIDR lists returned by the VPC query API.
Sometimes there were empty CIDR strings returned in the CIDR lists.
> filter empty strings from CIDR list

- cluster/oke.go
| Related tickets | none
- Added `GetCluster()` method to extract some common functionality which was used from multiple places in the codebase
-  Added implementation to `GetK8sIpv4Cidrs()` on OKE to be able to access external services (by [including internal IP ranges](https://istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly) only). The service and pod CIDR ranges are fetched using Oracle's GO SDK.
The functionality to configure the `BypassEgressTraffic` variable was only added for GKE in #1643, for EKS in #1701, for AKS in #1714 and for ACK in #1729.
- Launched an OKE cluster with …
> Configure bypass egress traffic on OKE for Istio posthook

- api/cluster_secret.go
Install all keys as JSON under the given name when source secret name is not specified and the spec is empty.
A current change didn't handle this case properly.
> handle secret install when spec is empty and source secret name is not defined

- cluster/dummy.go
- cluster/ec2_pke.go
| Related tickets | none
-  Added implementation to `GetK8sIpv4Cidrs()` on PKE to be able to access external services (by [including internal IP ranges](https://istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly) only). The service and pod CIDR ranges are fetched from the model of the cluster.
The functionality to configure the `BypassEgressTraffic` variable was only added for GKE in #1643, for EKS in #1701, for AKS in #1714 and for ACK in #1729.
> Configure bypass egress traffic on PKE for Istio posthook

- cluster/common.go
- cluster/ec2_pke.go
- internal/providers/model.go
- internal/providers/pke/config.go
- internal/providers/pke/cri.go
- internal/providers/pke/ec2_cluster_model.go
- internal/providers/pke/kubeadm.go
- internal/providers/pke/kubernetes.go
- internal/providers/pke/model.go
- internal/providers/pke/network.go
- internal/providers/pke/nodepool.go
- internal/providers/pke/nodepool_provider_config_amazon.go
- pkg/cluster/base.go
- pkg/cluster/pke/types.go
Renames all identifiers containing "distribution" or "banzaicloud" referring to PKE to "pke".
Partially addressed in #1691, now remaining identifiers/packages are renamed too.
> rename banzaicloud to pke

- api/security.go
- cmd/pipeline/main.go
| API breaks?     | yes (non-public)
Move the /version endpoint under basepath so it can be shown on the UI.
Also some refactor to eliminate joining paths by hand.
Using basePath before all API endpoints is required for consistent UI calls.
- would not include this
- Please **do not squash** the two commits.
> Move /version endpoint to basepath

- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/CreateAckPropertiesAcsk.md
- client/model_create_ack_properties_acsk.go
- cluster/acsk.go
- database/migrations/1549864170_add_ack_vswitch_field.down.sql
- database/migrations/1549864170_add_ack_vswitch_field.up.sql
- docs/openapi/pipeline.yaml
- model/cluster.go
- pkg/cluster/acsk/acsk.go
| API breaks?     | BC only
Allow specifying the VPC/VSwitch that the Alibaba cluster should be created in.
Custom VPCs were not supported on Alibaba before.
> ACK custom VPC

- cluster/ec2_pke.go
- pkg/secret/secret.go
- secret/store.go
This PR removes the "clusterUID" secret value from PKE Secret type.
Cluster UID was already added to the secret as a tag and the new one introduced an unnecessary complexity.
> Remove duplicated clusterUID tag from PKE secret

- Gopkg.lock
- Gopkg.toml
- api/spotguide.go
- auth/user.go
- docker-compose.yml
- spotguide/spotguide.go
For non-github authenticated setups the user's login name might differ from it's SCM user name and in this case organization name in the virtual token won't be correct, so we have to tell CICD to which organizations it should request a virtual token.
Also abstraction levels in `spotguide/spotguide.go` are corrected a bit, so no `http.Request` has to be sent down there again, and the `User` context object holds the `APIToken`, so the Pipeline can proxy authenticated requests to other services.
> spotguide: add org name to enable-repo request

- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/CreateUpdateOkePropertiesOke.md
- client/docs/NodePoolsOracle.md
- client/model_create_update_oke_properties_oke.go
- client/model_node_pools_oracle.go
- docs/openapi/pipeline.yaml
- pkg/providers/oracle/cluster/cluster.go
| API breaks?     | BC only
Make OKE VCN cluster creation/update parameters (VCN ID, subnet IDs) public and (de)serializable.
Currently, these parameters are not accessible from the API.
> Publish OKE VCN params

- database/migrations/1550784299_node_pool_label_tables.down.sql
- database/migrations/1550784299_node_pool_label_tables.up.sql
- internal/providers/google/gke_cluster_model.go
- internal/providers/google/model.go
- internal/providers/oracle/model.go
- model/cluster.go
- model/migrate.go
- pkg/providers/oracle/model/cluster.go
Keep the node pool labels table for backward compatibility until a Pipeline version not using it is released.
New database changes have to be backwards compatible with current Pipeline release.
These tables should be removed once a version of the Pipeline is released that is not using these.
> Keep node pool label tables for backward compatibility

- internal/monitor/cluster_subscriber.go
Convert typed IDs to uint.
The event bus panics when an input argument is not the correct type.
Since we introduced typed IDs, uint caused a panic when registering a new cluster.
> Fix federated monitoring subscribers

- pkg/providers/azure/cloud.go
| Related tickets | fixes #1782
The default operation polling period of 15 min is too low as the cluster create/delete operations often take longer than 15 mins. This leads to Pipeline receiving an error that the operation did not succeed while the operation continues to run on the cloud provider side and eventually complete.
> Increase Azure API operation polling duration time

- internal/providers/pke/pkeworkflow/create_cluster.go
- templates/pke/vpc.cf.yaml
| New feature?    |no
| Related tickets | |
Allowing multiple subnets in PKE needs rethinking from API perspective. We will only use one subnet for now, until we come up with a more broad solution.
> PKE use a single subnet

- auth/authn.go
- auth/github.go
- auth/user.go
- database/migrations/1551105244_set_spotguides_org_provider.down..sql
- database/migrations/1551105244_set_spotguides_org_provider.down.sql
- database/migrations/1551105244_set_spotguides_org_provider.up.sql
- spotguide/spotguide.go
If a user logs in with some other provider than GitHub it's convenient to have its user name synced into an org when the Sync Orgs feature is called.
To enable CI/CD for non through-GitHub registered users.
> import user name as organization during org sync

- Gopkg.lock
- Gopkg.toml
- cluster/ec2_pke.go
- cluster/gke.go
- cluster/hookfunctions.go
- cluster/hooks.go
- cmd/worker/main.go
- config/config.toml.dist
- config/configuration.go
- config/dex.yml.dist
- docker-compose.override.yml.dist
- internal/cluster/auth/auth.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/create_dex_client.go
- internal/providers/pke/pkeworkflow/create_master_activity.go
- internal/providers/pke/pkeworkflow/delete_cluster.go
- internal/providers/pke/pkeworkflow/delete_dex_client.go
- pkg/cluster/base.go
- pkg/k8sutil/k8sutil.go
| Related tickets | https://github.com/banzaicloud/pke/pull/7
Dex based OIDC cluster authentication. This is the first part of a series of PRs, since this just integrates Dex client creation into the PKE install flow (and added the necessary flags to the `pke` command).
To have more users other than the global admin user.
Maybe the clientID and clientSecret could be bundled into an OAuth secret type and the values could be generated inside the secret engine. Not sure.
> Dex cluster auth with PKE

- pkg/cluster/acsk/action/action_utils.go
| Related tickets | fixes #1800
> Fix: Graceful deletion of failed ACK clusters doesn't work

- Gopkg.lock
- Gopkg.toml
- auth/migrate.go
- database/migrations/1551260857_drop_casbin_rule_table.down.sql
- database/migrations/1551260857_drop_casbin_rule_table.up.sql
| Related tickets | related #1758, related #1764
This PR removes the last remains of Casbin.
Earlier we decided to remove Casbin and replace it with a simple, custom implementation. However, because of our migration policy we couldn't remove the database tables in a single step.
> Remove the remains of casbin

- cluster/oke.go
Extend the check which verifies that there are exactly 2 load balancer subnets specified with a clause checking that the subnets are not the same.
The 2 required load balancer subnets must not be the same.
> Check that the specified load balancer subnets are not the same

- config/config.toml.dist
> config: remove wrong chart version from config.dist

- .circleci/config.yml
- Dockerfile
- Dockerfile.debug
- Dockerfile.local
- Makefile
- go.sum
This PR upgrades every build process to Go 1.12.
The minimum local version is 1.11.5.
> Upgrade to Go 1.12

- cluster/hooks.go
- config/configuration.go
External dns chart version bump to 1.6.2
Bump external dns chart version because of a bug we encountered on EKS clusters
> Bump external dns chart default version to 1.6.2

- cluster/hooks.go
- config/configuration.go
External dns chart version bump to 1.6.2
Bump external dns chart version because of a bug we encountered on EKS clusters
>  Bump external dns chart default version to 1.6.2 and introduce image version

- cluster/manager_delete.go
- helm/helm.go
If a helm upgrade of a deployment fails the deployment will have two states: the original state and a PENDING_UPGRADE state. This caused Pipeline to delete such deployments twice the second attempt failing since the first already deleted the deployment.
> Fix delete all deployments

- pkg/cluster/eks/action/actions.go
This is a workaround for low number of workers to avoid PVC attach problems from different zones.
> Always use the first subnet as worker subnet

- cluster/acsk.go
| Bug fix?        | yes|
In case of ACK we should return ZoneId in the Location field.
This is required by the UI.
> Use zoneId in location field in case of ACK

- cmd/worker/config.go
- config/config.toml.dist
- internal/platform/cadence/config.go
- internal/platform/cadence/worker.go
| Related tickets | fixes #1839 
Create the Cadence domain at worker startup if it does not exist.
The domain's existence is a hard dependency of the worker's startup (unlike in the case of pipeline).
> worker: create domain on startup if it didn't exist

- internal/security/anchore.go
Fix anchore user manipulation fv's return values in case of error
> Fix anchore user manipulation fv's return values in case of error

- internal/providers/pke/pkeworkflow/delete_dex_client.go
Propagate low-level dex error correctly from the activity.
To see the root cause of deletion issues.
> dex: propagate client delete error

- go.mod
- go.sum
this version of the auth package returns an HTTP error in case the OAuth token is nil after the exchange procedure, instead of SIGSEGV-ing.
> update auth package to v0.1.0

- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/set_master_taint_activity.go
The kubernetes controller-manager won't attach nodes with the master
role (node-role.kubernetes.io/master-worker) active.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L588
> Fix node label for standalone master

- cluster/acsk.go
- cluster/aks.go
- cluster/common.go
- cluster/dummy.go
- cluster/ec2_pke.go
- cluster/eks.go
- cluster/gke.go
- cluster/hookfunctions.go
- cluster/hooks.go
- cluster/kubernetes.go
- cluster/manager_common_creator.go
- cluster/manager_common_nodepool_updater.go
- cluster/manager_common_updater.go
- cluster/manager_create.go
- cluster/manager_delete.go
- cluster/manager_update.go
- cluster/oke.go
- internal/providers/pke/pkeworkflow/cluster.go
- internal/providers/pke/pkeworkflow/update_cluster_status_activity.go
Rename `CommonCluster.UpdateStatus` to `SetStatus` to better convey its function. Remove the `Persist` method because it was neves supposed to be there (when the internal state is persisted should be at the discretion of the cluster object) and it was always used like `UpdateStatus` whose function it mostly duplicated. Also, fix the status update logic in GKE, because of the order of instructions the condition never allowed the status change to be recorded in the history. 
Spring cleaning. 🌱
> Set cluster status

- config/config.toml.dist
| Related tickets | https://github.com/banzaicloud/bank-vaults/issues/178
Until https://github.com/banzaicloud/bank-vaults/issues/178 gets fixed, don't use the DB role based authentication.
> don't use database user role by default

- cluster/manager_create.go
Fix a panic when cluster create does not receive any posthooks.
> Fix posthook panic when posthooks are not configured

- cmd/worker/config.go
This PR turns off the cadence domain creation by default.
Resource creation like this should be opt-in, not opt-out (see: database).
> Turn domain creation off by default

- api/bucket.go
- client/SHA256SUMS
- client/api/openapi.yaml
- client/api_storage.go
- client/docs/StorageApi.md
- cluster/gke.go
- cluster/hooks.go
- config/config.toml.dist
- config/configuration.go
- docs/openapi/pipeline.yaml
- docs/postman/e2e_test.postman_collection.json
- internal/providers/alibaba/objectstore.go
- internal/providers/amazon/objectstore.go
- In case of (non managed) storages we don't add location field to the response items. 
- In install logging posthook check the region field, if it's empty we send a get region request to cloud and set the region field
- To initialize Amazon & Alibaba clients we use default regions
- Make configurable these default regions
The current storage listing is extremly slow (compared to other providers). These numbers are depend on how many storage we have.
In case of 95 Amazon storage it takes `~8 sec` to get a response.
In case of 8 Alibaba storage it takes `~10-12 sec` to get a response.
With this solution:
In case of 95 …
> Speed up storage listing in case of Amazon & Alibaba

- internal/objectstore/objectstore.go
Add `omitempty` tag to `status`, `statusMsg`, `accessSecretId` fields to `BucketInfo` struct
Don't send empty fields. Current JSON response for bucket list:
```
[
{
"name": "bucket1",
"managed": false,
"location": "eu-central-1",
"status": "",
"statusMsg": "",
"accessSecretId": ""
},
{
"name": "bucket2",
"managed": false,
"location": "eu-west-1",
"status": "",
"statusMsg": "",
"accessSecretId": ""
}
]
```
After this change:
```
[
{
"name": "bucket1",
"managed": false,
"location": "eu-central-1"
},
{
"name": "bucket2",
"managed": false,
"location": "eu-west-1"
}
]
```
> Don't send empty fields with BucketInfo

- api/ark/backupservice/enable.go
- api/ark/buckets/create.go
- api/ark/common/common.go
- cluster/hooks.go
- internal/providers/objectstore.go
Get bucket location in backup services if `location` field is empty in request
In case of empty location field we cannot enable backup
> Get location for bucket(s) in case of backup enable/create

- templates/pke/master.cf.yaml
| Related tickets | no
Specifying Subnet and AZ can lead to a condition where the master instance is unable to fulfil. To prevent this we will only use subnet as parameter.
> remove AvailabilityZone parameter from instance definition

- cluster/nodelabels.go
This PR fixes the service name for cloudinfo request in nodepool label section.
> Fix acsk service name in cloudinfo request

- cluster/hooks.go
- cluster/hooks_tiller.go
This PR refactors Tiller waiting posthook to use a backoff library. It also solves a recurring Helm install problem on Alibaba ACK.
After installing Tiller, we try to connect to the Tiller pod to check it's version. In some cases, the port forward connects to the (still running) old pod. The version check permanently stopped the backoff loop before. This has been fixed in this PR.
> Fix waiting for tiller

- .gitignore
- config/config.toml.dist
Update the default version for the following components in the default dev config:
- Tiller
- Logging Operator image
- Istio Operator chart
Also, relocated the default path for the helm cache.
> Update versions, change default helm cache path

- helm/helm.go
| Bug fix?        |yes|
| New feature?    |no|
| API breaks?     |no|
Remove break which prevented to collect all tagged deployment which caused errors in Spotguide when trying to list notes.txt on a deployment which does not have one.
> Remove break which prevented to collect all tagged deployments

- helm/helm.go
Reverts banzaicloud/pipeline#1936
We need to add Spotguide specific helm chart tags to all Spotguides before merging this commit. Ci client tags all deployments even the ones in the requirements which can cause unnecessary Spotguide summary if the requirements has a notes.txt.
> Revert "Remove break which prevented to collect all tagged deployments"

- go.mod
- go.sum
Update bank-vaults to latest pre-release to support wildcard certification creation.
Update Alibaba-cloud-sdk to the latest released one
> Update bank-vaults and alibaba-cloud-sdk dependency

- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/GetClusterStatusResponse.md
- client/model_get_cluster_status_response.go
- docs/openapi/pipeline.yaml
The `version` field is returned by the API but it was missing from the OpenAPI descriptor, this PR adds it.
We need this field to determine the cluster version and make decisions based on that in `ci-pipeline-client`, which parses responses with the help of the generated client library.
> client: add version field to GetClusterStatusResponse

- api/cluster_create.go
- api/cluster_create_test.go
Unit test PKE-on-Azure cluster creation request decoding.
Ensure request is always decoded properly into the related struct.
> Unit test for PKE-on-Azure cluster creation request decoding

- cluster/ack.go
- pkg/cluster/ack/action/action_create_nodepool.go
- pkg/cluster/ack/action/action_delete_ssh_key.go
- pkg/cluster/ack/action/action_update_nodepool.go
- pkg/cluster/ack/action/action_utils.go
- pkg/cluster/ack/defaults.go
Enable parallel execution of node pool creation as ACK API supports this now.
Increase ACK Rest API call read timeout setting to 30seconds
The parallel execution of node pool creation speeds up cluster creation.
The increased ACK Rest API call read timeout setting mitigates cases when the API is slow to respond and times out while the server still continues to process the request.
> Ack parallel crud nodepool operation

- secret/verify/google.go
Fixes GKE secret validation error handling
Useful information was lost, because new error was created instead of wrapping the raised provider error.
> Fix GKE secret validation error handling

- cmd/pipeline/main.go
Turn off imagescan api endpoints in case of disabled anchore.
If anchore isn't enabled, the related endpoints should be disabled.
> Turn off api endpoint if anchore isn't enabled

- cluster/hooks_istio.go
Add cluster name and cluster id to the log context of service mesh install post hook.
The additional log context helps to identify easier which cluster a failed service mesh install is related to.
> Add cluster name and id to install service mesh posthook logs

- client/SHA256SUMS
- client/api/openapi.yaml
- client/api_clusters.go
- client/docs/ClustersApi.md
- docs/openapi/pipeline.yaml
- spotguide/cicdconfig.go
- spotguide/spotguide.go
- spotguide/spotguide_test.go
Do not restrict the format of the CreateCluster request to support the new request format in spotguides (i.e. to make it possible to create azure/pke clusters).
As oneOf is not supported by openapi-generator, and the possible request formats are
incompatible, we have to fall back to type:object (map[string]interface{}).
The request is composed by the UI during spotguide creation, by the same routines that submit requests for new clusters. The request format is validated at the end by Pipeline cluster API.
See banzaicloud/ci-pipeline-client#83
> Unrestricted CreateCluster request formats in OpenAPI

- dns/route53/route53.go
> Fix: cluster deletion failes if route53 domain name is empty

- cmd/worker/main.go
- internal/cluster/workflow/common.go
- internal/cluster/workflow/delete_helm_deployments_activity.go
- internal/cluster/workflow/delete_k8s_resources.go
- internal/cluster/workflow/delete_namespace_resources_activity.go
- internal/cluster/workflow/delete_namespace_services_activity.go
- internal/cluster/workflow/delete_user_namespaces_activity.go
- internal/providers/azure/pke/driver/cluster_deleter.go
- internal/providers/azure/pke/workflow/delete_cluster.go
- internal/secret/kubernetes.go
Pass k8s config secret IDs to activities instead of k8s configs.
Security reasons.
> Pass k8s config secret IDs to activities instead of k8s configs

- cluster/hooks.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/workflow/create_infra.go
Pass initial node taints through the user data script instead of setting taints on already joined nodes. 
Setting taints through user data script has the advantage of having those taints placed automatically on the new nodes are created by the VMSS.
> Set taint on headnode through VMSS user datascript

- cluster/hooks.go
- helm/install.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/pke/pkeworkflow/set_master_taint_activity.go
- pkg/cluster/pke/types.go
- pkg/common/common.go
- pkg/helm/helm.go
Use node affinity instead of node selector to schedule tiller pod master or system node where available as node affinity allows soft placement rule.
This allows for scheduling tiller for a non-worker node to ensure that tiller is scheduled to a node that has enough resources.
> Schedule tiller pod to desired node using node affinity

- dns/route53/hostedZone.go
- dns/route53/route53.go
Set a low NTTL value of 60 seconds to the created hosted zones' soa record.
If we create an ingress, and the end user tries to load the page earlier than the correct record is synced to route53, the negative response will be cached by the caching recursors or the user's machine for `min(SOA.ttl=900, SOA.nttl=86400)=900` seconds by default.
> route53: set low NTTL value to hosted zone's soa

- cluster/hooks.go
pke-tool creates a default storageclass by default, and the posthook creates one more. there shouldn't be more than one.
- long-term solution
> 0.18: hotfix duplicate default storageclass on aws/pke

- internal/istio/prometheus.go
Change Istio components scrape time to 5 seconds for quicker telemetry.
> Change Istio components scrape time to 5 seconds

- internal/cluster/workflow/wait_pvs_deletion_activity.go
In case the cluster deletion is re-executed on a cluster that is in an incomplete state creating a watcher for persistent volumes may fail. This error must be handled gracefully.
> Fix: unhandled error if no watcher for persistent volumes can be created

- internal/istio/istiofeature/reconcile_remoteistios.go
Wrong label was used to determine which cluster ID the Remote Istio CR belongs to.
> Fix clusterID label

- internal/clustergroup/deployment/deployment.go
- internal/clustergroup/deployment/manager.go
> clustergroup deployments: fix merge problem when global values are nil

- internal/clustergroup/deployment/manager.go
…lues specifed in request
Always save empty global values even if no global values are specified in request, fixing eventual merge problems at deployment update with reuseValues = true.
> Upd rvalues 0.19.x

- internal/providers/azure/pke/driver/commoncluster/cluster.go
Don't panic in unimplemented CommonCluster methods of Azure PKE
Azure/PKE is in prod now, and should not panic instead of error reporting, not even in edge cases.
> Don't panic in unimplemented CommonCluster methods of Azure PKE

- api/cluster_auth.go
- cmd/pipeline/main.go
| Related tickets | completion of #2043 
> dex: make insecure configurable in ClusterAuthAPI as well

- api/secrets.go
- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/CreateSecretResponse.md
- client/model_create_secret_response.go
- docs/openapi/pipeline.yaml
- secret/store.go
Use the generated `CreateSecretResponse` type from the `client` package in the API instead of the one from the `secret`.
It's redundant to have the type repeated. Also, the `secret` package in the project root should not exist, and this is a step toward removing it.
> Use client/CreateSecretResponse

- cmd/pipeline/main.go
Add `example.com` check to the decision whether auto DNS is enabled or not.
`example.com` is the default external DNS domain. In order to make auto DNS opt-in.
> Add example.com default to the auto dns check

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/pke/config.go
- internal/providers/pke/cri.go
- internal/providers/pke/kubeadm.go
- internal/providers/pke/network.go
- internal/providers/pke/nodepool.go
- internal/providers/pke/pkeworkflow/create_cluster.go
Implementing a more DB neutral Scan method. Also bump PKE version (TLS insecure fix).
The MySQL driver scans strings as `[]uint8`, the Postgres driver scans them as `string`.
> fixing mysql/postgres text vs. varchar type mismatch issues

- cluster/gke.go
| Related tickets | fixes #2055
Return error if the cluster status after GKE cluster creation is ERROR
> quick fix for GKE cluster creation in case of its status is ERROR

- spotguide/scm/gitlab.go
| Related tickets | See trace below. 👇 
Fixing panic when gitlabTag is not tied to a gitlab release.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3044c71]
goroutine 108 [running]:
github.com/banzaicloud/pipeline/spotguide/scm.(*gitLabSCM).ListRepositoryReleases(0xc0000b8eb0, 0xc00082de10, 0xa, 0xc00123fcb0, 0xb, 0x0, 0xc000869440, 0x7, 0x8, 0x0)
/build/spotguide/scm/gitlab.go:111 +0x181
github.com/banzaicloud/pipeline/spotguide.(*SpotguideManager).scrapeSpotguides(0xc000582300, 0xc000708480, 0x45fa680, 0xc0000b8eb0, 0x0, …
```
> spotguide: gitlabTag.Release can be nil, use .Name instead

- spotguide/spotguide.go
This PR adds the repoconfig in base64 format to error context, to ease debugging
> Add repoConfig to error if spotguide config fails to marshall

- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/UpdateNodePoolsAzure.md
- client/model_update_node_pools_azure.go
- cluster/aks.go
- docs/openapi/pipeline.yaml
Fixing the regexp match indexing in the AKS subnet validation logic.
Off-by-one error that hasn't manifested yet because apparently the web UI never posted the subnet field (in the right place).
> fix regexp match indexing in AKS subnet validation

- api/common_stuff.go
Filter out Unauthorized response code in case of Amazon specific errors
We want to list Amazon networks: `{url}/pipeline/api/v1/orgs/{orgId}/networks?cloudType=amazon&region=us-west-2` with a wrong Amazon secret. Pipeline response (with 401 status code):
```
{
"code": 401,
"message": "AWS was not able to validate the provided access credentials",
"error": "AuthFailure: AWS was not able to validate the provided access credentials\n\tstatus code: 401, request id: 0cb63d3f-aa66-4647-81e6-2f24e51033a2"
}
```
The UI will logout the user after this request without any information. I think in these cases when we communicate with …
> Filter out Unauthorized response code in case of Amazon specific errors

- api/spotguide.go
| Bug fix?        |no|
| New feature?    |yes|
Use errorHandler instead of simple log.error to display available contexts.
> Use errorHandler instead of simple log.error in case of LaunchSpotguide

- api/bucket.go
- database/migrations/mysql/1559301886_oracle_bucket_add_namespace.down.sql
- database/migrations/mysql/1559301886_oracle_bucket_add_namespace.up.sql
- database/migrations/postgres/1559301886_oracle_bucket_add_namespace.down.sql
- database/migrations/postgres/1559301886_oracle_bucket_add_namespace.up.sql
- internal/objectstore/objectstore.go
- internal/providers/oracle/objectstore.go
- internal/providers/oracle/objectstore_model.go
- pkg/providers/oracle/objectstore/objectstore.go
Add namespace field to Oracle bucket.
Oracle buckets should be referred with namespace like bucketName@namespace at least when accessing through HDFS Connector for Object Storage which is used by Spark. When using Oracle storage buckets for Spark Event Logs we need to know the namespace for each bucket.
> bucketAPI: save namespace for Oracle buckets

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/driver/common.go
Add the `kubernetes-master-mode` command line argument to the user data script of Azure PKE cluster master nodes.
> Azure PKE master HA user data script fix

- api/secrets.go
- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/CreateSecretResponse.md
- client/model_create_secret_response.go
- docs/openapi/pipeline.yaml
| Related tickets | fixes #2097 
Add `tags` field to SecretCreateResponse struct
> Add tags field to SecretCreateResponse

- api/secrets.go
Add tags field to update secret response
In case of secret update the `tags` field is missing
> Add tags field to update secret response

- internal/istio/istiofeature/helm.go
- internal/istio/istiofeature/reconcile_istio_operator.go
- internal/istio/istiofeature/reconcile_uistio.go
Adds support for helm package upgrade in Istio cluster group feature reconcile logic
We must support package upgrade to deploy newer version of an already deployed chart to the cluster
> Support helm upgrade in Istio clustergroup feature

- cluster/ec2_pke.go
- cluster/eks.go
- cluster/log.go
- cmd/worker/aws.go
- internal/providers/pke/pkeworkflow/cluster.go
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/create_master_activity.go
- internal/providers/pke/pkeworkflow/get_vpc_default_sg_activity.go
- internal/providers/pke/pkeworkflow/pkeworkflowadapter/cluster_manager.go
- internal/providers/pke/pkeworkflow/update_cluster.go
- pkg/providers/amazon/ec2/network.go
- templates/pke/master.cf.yaml
- templates/pke/masters.cf.yaml
- templates/pke/worker.cf.yaml
Support of creating the node pools of a cluster in different subnets of an existing VPC.
In order to be able to deploy certain nodes to private subnets we need to support deploying nodepools into a specific subnet of an existing VPC.
An example create a request for deploying a cluster where the master nodes are in a different subnet than the worker nodes that belong to pool1 using `banzai cli`.
```
banzai cluster create <<EOF
{
"name": "pke-cluster1",
"location": "eu-west-1",
"cloud": "amazon",
"secretId": "<aws-credentials-secret-id>",
"properties": {
"pke": {
"nodepools": [
{
"name": "master",
"roles": [
"master"
], …
```
> PKE on AWS: support creating node pools across different subnets of existing VPC

- auth/authn.go
- auth/oidc.go
- config/config.toml.dist
- config/configuration.go
- config/dex.yml.dist
- docker-compose.yml
- go.mod
- go.sum
| Related tickets | https://github.com/banzaicloud/banzai-cli/pull/85
This PR adds the ability to register and login from the `banzai` CLI tool with the `banzai login` subcommand. This is implemented mostly in the CLI, so it creates a web flow with the OIDC provider and posts the IDToken to Pipeline directly, which returns a Pipeline token which expires after 30 days automatically.
https://github.com/banzaicloud/banzai-cli/pull/85
> cli oidc login flow

- cluster/hooks.go
- cmd/worker/main.go
- config/configuration.go
- dns/dns.go
- dns/route53/route53.go
- internal/federation/reconcile_ext_dns.go
Upgrade external-dns to version 0.5.15.
The external-dns helm chart used by Pipeline was quite outdated which had no support for the latest version of external-dns components
> Upgrade external-dns to version 0.5.15

- go.mod
- go.sum
Upgrade nodepool labels operator package to get rid of the old emperror package.
> Upgrade nodepool labels operator

- cluster/manager_delete.go
- internal/cluster/kubernetes/user_namespace_deleter.go
In case of force delete remove imported cluster regardless if its kubeconfig is invalid or the  kubeconfig  relies on an external authenticator that is not available to Pipeline.
Imported clusters with invalid kubeconfig or kubeconfig that relies on an external authenticator that is not available to Pipeline can't be removed from Pipeline.
> Fix: imported cluster can not be deleted if it's kubeconf is invalid

- cluster/kubernetes.go
- secret/verify/common.go
- secret/verify/kubernetes.go
Validate Kubernetes config secret by trying to query API server version using it.
Kubernetes config passed to Pipeline might be syntactically correct while unusable in Pipeline's context for various reasons (e.g. it uses an external auth provider that is not available to Pipeline). The passed Kubernetes config must be verified that Pipeline can use it to interact with Kubernetes cluster references in the config.
> Validate KubeConf secret when added and when used at cluster import

- .circleci/config.yml
https://discuss.circleci.com/t/docker-convenience-images-updates-july-2019/31239
> The apt-get index cache is no longer present in images. If your image uses sudo apt-get install, after this update it will fail unless you first run sudo apt-get update. It’s often best to do is do this all in one command—for example, sudo apt-get update && sudo apt-get install <my-package>.
> Debian 10-based images. Debian 10 “Buster” was released on July 6th. For our images that offer variant distros, -buster will be an option.
> circleci: fix install dependencies step

- Dockerfile
- Dockerfile.debug
- Dockerfile.local
Fixes Go's netgo implementation when running on Alpine.
There is no default `nsswitch.conf` on Alpine.
https://github.com/gliderlabs/docker-alpine/issues/367#issuecomment-424546457
> Add nsswitch.conf to Docker image

- cluster/ack.go
- cluster/eks.go
- cluster/kubernetes.go
> Fix: type parameter is missing from default storage class on ACK

- auth/authn.go
- auth/oidc.go
- auth/util.go
Error messages are cleanly returned as JSON now.
```json
{
"error": "failed to query github login name: GET https://api.github.com/user/23779: 401 Bad credentials []"
}
```
Also, deregister call got added back (this was broken since the Dex migration).
These messages were propagated through flash messages but sometimes they got lost or got scrambled in a bad HTML page, and the user didn't know why the login failed. This response is much cleaner and straightforward.
> authn: cleaner error handling during login/register

- cmd/worker/config.go
Fix missing dialect in worker config.
Worker uses it's own Viper instance. Every configuration parameter must be registered in it's instance as well.
> Fix dialect config

- pkg/k8sclient/client.go
This PR fixes in-cluster k8s clients.
The new k8s client helper methods introduced IP filtering to limit
where the client can connect.
In case of in-cluster clients however this is not necessary.
> Fix in-cluster Kubernetes client

- .circleci/config.yml
Try to use a GOPROXY in the circle build and possibly replace the go module cache.
To speed up the build.
> Use goproxy in circle

- internal/providers/azure/pke/workflow/create_infra.go
- internal/providers/azure/pke/workflow/update_cluster.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/delete_cluster.go
- internal/providers/pke/pkeworkflow/update_cluster.go
| Related tickets | fixes #2155
Future map structures are converted to slices to ensure iterations are deterministic.
In some cases the implementation itself was affected. Please take that into account when reviewing.
~~- [-] Implementation tested (with at least one cloud provider)~~
> Fix non-deterministic map iterations in Cadence workflows

- internal/providers/pke/pkeworkflow/delete_cluster.go
> Fix: delete PKE on AWS cluster failes due to nil pointer dereference

- config/configuration.go
- go.mod
- go.sum
- internal/federation/federation.go
- internal/federation/reconcile_controller.go
- internal/federation/reconcile_dns_cluster_role.go
- internal/federation/reconcile_ext_dns.go
Use latest patched kubefed image: v0.1.0-rc5-bzc.1 from banzai repo. Change group names of federated objects (from: kubefed.k8s.io --> kubefed.io) to align with latest changes.
ReplicaSchedulingPreference is not working correctly in v0.1.0-rc5.
> fedv2: use latest patched version of rc5 image

- cmd/pipeline/main.go
- cmd/worker/config.go
- cmd/worker/main.go
- config/configuration.go
- spotguide/spotguide.go
- spotguide/sync_spotguides_workflow.go
| Related tickets | fixes https://github.com/banzaicloud/pipeline/issues/2158
Instead of a Go routine shared spotguides are scraped now in a Cadence Cron Workflow.
More elegant, and when in running in HA mode - more correct. :)
Currently the first decision task fails in a CronWorkflow, but then it finishes properly.
There is a pending issue in Cadence: uber/cadence#2100
> spotguide: scrape shared spotguides in cron workflow

- cmd/pipeline/main.go
- cmd/worker/clusterfeature.go
- cmd/worker/main.go
- database/migrations/mysql/1565680687_add_cluster_feature_unique_index.down.sql
- database/migrations/mysql/1565680687_add_cluster_feature_unique_index.up.sql
- database/migrations/postgres/1565680706_add_cluster_feature_unique_index.down.sql
- database/migrations/postgres/1565680706_add_cluster_feature_unique_index.up.sql
- internal/clusterfeature/clusterfeatureadapter/async_feature_manager.go
- internal/clusterfeature/clusterfeatureadapter/cluster_service.go
- internal/clusterfeature/clusterfeatureadapter/gorm_feature_repository.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_activate_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_deactivate_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_delete_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_job_workflow.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_set_spec_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_set_status_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_update_activity.go
- internal/clusterfeature/feature_manager.go
- internal/clusterfeature/features/dns/manager.go
- internal/clusterfeature/repository.go
- internal/clusterfeature/repository_test.go
- internal/clusterfeature/service.go
- internal/clusterfeature/service_test.go
Generic Candence workflow for executing asynchronous cluster feature actions (activate, deactivate, update).
> Generic cluster feature workflow

- internal/global/uuid.go
- internal/providers/azure/pke/workflow/create_lb_activity_test.go
- internal/providers/azure/pke/workflow/create_nsg_activity_test.go
- internal/providers/azure/pke/workflow/create_public_ip_activity_test.go
- internal/providers/azure/pke/workflow/create_route_table_activity_test.go
- internal/providers/azure/pke/workflow/create_vmss_activity_test.go
- internal/providers/azure/pke/workflow/create_vnet_activity_test.go
- internal/providers/azure/uuid.go
| Related tickets | fixes #2193
Fixes and unifies Pipeline UUID resource label name.
Cloud providers support resource labeling with different restrictions.
> Fix UUID resource label

- cluster/middleware.go
| Related tickets | fixes #2213 
Allow cluster API calls with cluster name like:
`{url}/api/v1/orgs/{clusterId}/clusters/colin0149h5d?field=name`
> Allow cluster API calls with cluster name

- api/custom.go
- api/custom_test.go
- api/images.go
- api/security.go
- pkg/helm/helm.go
Consider beside label 'release' also 'app.kubernetes.io/instance' when trying to determine which helm release a Kubernetes resource belongs to.
Most of the helm charts use 'release' label to stamp a Kubernetes resource with the Helm release name. According to  https://helm.sh/docs/chart_best_practices/#standard-labels, the new recommendation is to use 'app.kubernetes.io/instance' thus Pipeline should handle both.
> Support both 'release' and 'app.kubernetes.io/instance' labels to link objects to Helm releases

- internal/clusterfeature/clusterfeatureadapter/async_feature_manager.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_job_workflow.go
- internal/clusterfeature/feature_manager.go
- internal/clusterfeature/service.go
- internal/clusterfeature/service_test.go
Move cluster feature state (persistence) management up to the service.
Cluster feature persistence is independent of the feature's operation.
> Move repository operation to service

- auth/user.go
Adds support for org creation for all IdP.
GitHub and Gitlab orgs were sourced only until now, we need to support LDAP and others as well.
N/A
> auth: support org creation on all providers

- internal/clusterfeature/features/dns/spec.go
Set dns provider to `aws` in case of route53
This is the valid `provider` value to external dns chart
> Set valid DNS provider in case of Route53

- cmd/worker/config.go
Add missing database TLS config default to worker config.
AutomaticEnv only works for keys defined.
> Fix worker database config

- config/dex.yml.dist
The Dex LDAP group search filter contained a typo.
> dex: fix ldap filter in sample config

- Makefile
In case of LDAP upstream IdP enabled in Docker Compose, there is a custom volume `ldap-config`, down leaves there so it should be destroyed as well.
> docker-compose: down should remove named volumes declared in the `volumes` like ldap-config

- helm/helm.go
Remove break to collect all tagged deployments
Currently the deployment list (in case of tag filter) doesn't collect all tagged (and matched) deployment:
```json
[
{
"releaseName": "spotguide1",
"supported": true,
"whiteListed": false,
"rejected": false
}
]
```
After this change:
```
[
{
"releaseName": "spotguide1",
...
"supported": true,
"whiteListed": false,
"rejected": false
},
{
"releaseName": "spotguide2",
...
"supported": true,
"whiteListed": false,
"rejected": false
}
]
```
Because of this `break` wrong notes shown on summary page of Spotguide (if 1 cluster has more Spotguide)
> Remove break to collect all tagged deployments

- internal/dashboard/api.go
- pkg/k8sclient/client.go
Set 5 secs timeout for k8s client connection from dashboard to avoid waiting too much for clusters temporarily or not reachable anymore.
> set timeout for dashboard k8s client connections

- .circleci/config.yml
| Related tickets |  -
Replace Docker Hub's auto build.
```
master -> banzaicloud/pipeline:latest
tag    -> banzaicloud/pipeline:<tag>
branch -> only build
```
To make it faster.
> Build docker image with CircleCI

- auth/authn.go
- cluster/hooks.go
- config/configuration.go
- go.mod
- go.sum
- internal/hollowtrees/hollowtrees.go
This PR adds support to Pipeline so it can deploy instance termination handler to a Hollowtrees enabled cluster in such a way that it will be able to report back instance termination events directly to the Hollowtrees instance running on the control plane.
This feature uses an internal api which needs an internal user, this PR also moves that internal user from DB to code.
> Hollowtrees direct report back with JWT auth support

- .circleci/config.yml
> circleci: skip pushing latest tag if version unstable

- templates/eks/amazon-eks-nodepool-cf.yaml
Pods running on EKS clusters worker nodes get IPs from the same subnet as the nodes, we should allow any traffic from the cluster control plane towards the nodes.
> Allow any traffic from cluster control plane to nodes

- Makefile
- config/dex.yml.dist
- database/docker-init-mysql.sql
- database/docker-init-postgres.sql
- docker-compose.override.yml.dist
- docker-compose.yml
| Deprecations?   | `$PIPELINE_DIR/.docker/volumes/dex`
Use MySQL by default from local Dex, and added Postgres example.
To use and browse the same DB as for other services.
You are most probably using the SQLite backend currently. If you want to use the MySQL or Postgres backend right now, you have to create the `dex` database manually (if you don't want to loose your date), or
```bash
make down
rm config/dex.yml
make up
```
> dex: use the same db locally as other services

- auth/github.go
- auth/gitlab.go
- auth/user.go
- database/migrations/mysql/1567509964_change_user_organization_default_role.down.sql
- database/migrations/mysql/1567509964_change_user_organization_default_role.up.sql
- database/migrations/postgres/1567509964_change_user_organization_default_role.down.sql
- database/migrations/postgres/1567509964_change_user_organization_default_role.up.sql
Save the user's role in an organization
- The PR contains a regression for user orgs: the user becomes a member in it's own organization. It will be fixed in a later PR.
- Organization sync will be refactored so that Github and Gitlab providers are not used directly.
- Role binding will be added as part of the organization sync
> User role binding

- api/organization.go
- auth/authn.go
- auth/oidc.go
- auth/user.go
This PR stores OAuth refresh tokens from the OIDC provider (Dex) and sync new user group information in via redeeming this token instead of skipping Dex from the picture.
This is a much cleaner and reusable solution.
> auth: refresh orgs with dex

- internal/dashboard/api.go
- internal/dashboard/dashboard.go
Add missing `resourceSummary` field to dashboard cluster API response
UI can't show nodes under nodepools because of this missing field. After this change the the node appears on cluster details page
> Add missing resourceSummary field to dashboard cluster API response

- internal/clusterfeature/features/dns/operator.go
- internal/clusterfeature/features/dns/operator_test.go
- internal/clusterfeature/features/dns/spec.go
Region and batch change size configuration for the external dns configuration are processed from the posted feature specification
the above entries from the spec were ignored
testing
> DNS feature: region, batch change size taken from the spec

- cluster/eks.go
- pkg/cluster/eks/action/actions.go
- pkg/cluster/eks/action/network.go
- pkg/providers/amazon/ec2/network.go
Search for network interfaces that were created by EKS CNI plugin and are no longer "in-use" and delete them prior starting to delete subnets and vpc at cluster deletion.
EKS CNI plugin allocates native AWS VPC IPs addresses for PODs. Behind the scenes what happens is that multiple network interfaces (ENIs) are created and attached to the nodes with multiple pre-allocated IPs. Pods running on the node will get an IP from these.
When pods and nodes are deleted the ENIs of which IPs are not used any more are deleted. However, it may happen that some of these ENIs are left behind (detached state) holding a reference to the …
> EKS: delete unused ENIs that were not released by EKS CNI plugin during cluster delete operation

- cmd/pipeline/config.go
- cmd/pipeline/main.go
- cmd/worker/config.go
- config/config.toml.dist
- pkg/viperx/alias.go
| Related tickets | Fixes #2324
Fix configuration aliases
`viper.RegisterAlias` does not handle nested configuration.
> Config improvements

- internal/providers/azure/pke/driver/preparers.go
Fix conditions checking string set equality of roles and zones of existing node pools.
The conditions were checking for equality instead of inequality, thus emitting warnings wrongly.
> Fix Azure PKE prepare conditions

- internal/clusterfeature/features/vault/client.go
- internal/clusterfeature/features/vault/common.go
- internal/clusterfeature/features/vault/manager.go
- internal/clusterfeature/features/vault/operator.go
Closing the Vault client (stop token renewal) after feature work is done.
Also the mount path should be changed since `kubernetes/` is already taken.
To prevent resource leaks.
> vault-feature: close client after work

- internal/clusterfeature/features/vault/manager.go
- internal/clusterfeature/features/vault/manager_test.go
| Related tickets | https://github.com/banzaicloud/banzai-cli/pull/144
Instead of rolePath, the role is enough for client consumption.
> vault-feature: simplify role output

- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_apply_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_deactivate_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_job_workflow.go
- internal/clusterfeature/clusterfeatureadapter/workflow/common.go
Check retry errors after `apply` and `deactivate` and return with a `customError` (and reason) of Candence. After this we can easily check this type of error in the workflow
Currently we cannot activate/deactivate the features properly while the cluster is not in ready state. Because of this the feature actions will be failed
> Fix Activity retry process in case of features

- cluster/common.go
- cluster/create_workflow.go
- cluster/ec2_pke.go
- cluster/hookfunctions.go
- cluster/hooks.go
- cluster/manager_create.go
- cmd/worker/main.go
- internal/providers/azure/pke/driver/commoncluster/cluster.go
- pkg/cluster/base.go
Remove k8s config download from posthooks.
Config download is highly distribution/cloud dependent and can hardly be implemented in a generic way. The legacy cluster create flow is basically the only flow still using it.
With the new cluster init manifest we are moving towards a cluster bootstrap/setup workflow which installs every generic component/manifest required by pipeline. K8s config download was basically the last step of the posthook/legacy cluster setup flow not running inside the cluster. Once it's gone, we can start building the generic cluster setup flow from existing posthooks.
~~- [-] Error handling code …
> Move k8s config download to a separate workflow

- cluster/hooks.go
Metrics Server - required if not already deployed by managed K8S, like GKE etc. - fails with RBAC problems:
```
ERROR: logging before flag.Parse: E1008 09:26:20.601059       1 memcache.go:153] couldn't get resource list for metrics.k8s.io/v1beta1: an error on the server ("Internal Server Error: \"/apis/metrics.k8s.io/v1beta1\": subjectaccessreviews.authorization.k8s.io is forbidden: User \"system:serviceaccount:pipeline-system:hpa-operator-metrics-server\" cannot create resource \"subjectaccessreviews\" in API group \"authorization.k8s.io\" at the cluster scope") …
```
> enable RBAC for hpa-operator dependency: metrics-server (PR#2361)

- cluster/eks.go
- cluster/gke.go
- cluster/hooks.go
- cluster/hooks_tiller.go
- config/config.toml.dist
- config/configuration.go
- helm/install.go
- pkg/helm/helm.go
- pkg/providers/oracle/oci/ce_cluster.go
Removes configurable retry configuration options and replaces them with constants.
As far as we can tell, we don't need to be able to configure these. Most of the options became obsolete anyway. They can be added back later if necessary.
> Config remove attempts

- auth/authz.go
- auth/authz_test.go
Allow HEAD requests for organization members.
Organization members should be able to read resources.
> Allow HEAD requests for members

- config/config.toml.dist
- config/configuration.go
- helm/helm.go
- helm/install.go
- pkg/helm/helm.go
Add a new deafult Helm repository with name `loki` from `https://grafana.github.io/loki/charts` url 
`Loki` component of the `Logging` feature will be apply from this new repository
> Add Loki to deafult Helm repositories

- .gen/pipeline/README.md
- .gen/pipeline/SHA256SUMS
- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_create_cluster_request_v2.go
- .gen/pipeline/pipeline/model_create_pke_on_azure_cluster_request.go
- .gen/pipeline/pipeline/model_pke_cluster_http_proxy.go
- .gen/pipeline/pipeline/model_pke_cluster_http_proxy_options.go
- api/cluster/pke_azure.go
- apis/pipeline/pipeline.yaml
- cmd/worker/main.go
- cmd/worker/pke.go
- database/migrations/mysql/1569937443_add_http_proxy_to_pke_azure.down.sql
- database/migrations/mysql/1569937443_add_http_proxy_to_pke_azure.up.sql
- database/migrations/postgres/1569937443_add_http_proxy_to_pke_azure.down.sql
- database/migrations/postgres/1569937443_add_http_proxy_to_pke_azure.up.sql
- internal/pke/http_proxy.go
- internal/pke/workflow/adapter/secret_store.go
- internal/pke/workflow/assemble_http_proxy_settings_activity.go
- internal/pke/workflow/assemble_http_proxy_settings_activity_test.go
- internal/providers/azure/pke/adapter/gorm_store.go
- internal/providers/azure/pke/cluster.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/driver/common.go
- internal/providers/azure/pke/store.go
- internal/providers/azure/pke/workflow/create_cluster.go
- internal/providers/azure/pke/workflow/create_infra.go
- internal/providers/azure/pke/workflow/create_vmss_activity.go
Add HTTP(S) proxy settings for Azure PKE clusters. The following are added:
* REST API extensions to receive proxy settings
* persist proxy settings with cluster data
* add environment variables to user data scripts defining the necessary proxy settings
The tasks in the user data script should be modified if necessary to make use of the settings.
In closed network environments (or for other reasons) users should be able to set an HTTP(S) proxy to be used for PKE installation and other initialization tasks.
> HTTP proxy for Azure PKE

- cluster/manager_get.go
- cmd/worker/main.go
- docker-compose.yml
- internal/clusterfeature/clusterfeatureadapter/cadence_feature_operation_dispatcher.go
- internal/clusterfeature/clusterfeatureadapter/cluster_getter.go
- internal/clusterfeature/clusterfeatureadapter/cluster_service.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_apply_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_deactivate_activity.go
- internal/clusterfeature/clusterfeatureadapter/workflow/cluster_feature_job_workflow.go
- internal/clusterfeature/clusterfeatureadapter/workflow/common.go
- internal/clusterfeature/features/dns/common_test.go
- internal/clusterfeature/features/dns/manager_test.go
- internal/clusterfeature/features/dns/operator_test.go
- internal/clusterfeature/features/monitoring/common_test.go
- internal/clusterfeature/features/monitoring/manager_test.go
- internal/clusterfeature/features/monitoring/operator_test.go
- internal/clusterfeature/features/vault/common_test.go
- internal/clusterfeature/features/vault/manager_test.go
- internal/clusterfeature/features/vault/operator_test.go
- internal/helm/service.go
- internal/providers/azure/pke/workflow/delete_infra.go
- internal/security/resource_service.go
| Related tickets | fixes #2404 
Cluster readiness is checked by polling the cluster status and waiting until the cluster is "RUNNING".
Cluster feature activation failed when the feature was activated during cluster creation because the readiness condition was wrong
> Fix pending cluster feature activation

- internal/providers/azure/pke/driver/cluster_updater.go
- internal/providers/azure/pke/workflow/update_vmss_activity.go
A custom optional uint type that is properly serializable.
The imported optional uint type was not properly serializable because it does not implement marshaler/unmarshaler and all its fields are private.
> Use serializable optional uint type

- internal/clusterfeature/features/monitoring/spec.go
Replace parseDuration with regex match in case of retention field
In case of `time.ParseDuration` valid time units are `"ns", "us" (or "µs"), "ms", "s", "m", "h"` but we need `"ms", "s", "m", "h", "d", "w", "y'`
> [Monitoring] Add regex check to retention field

- internal/clusterfeature/features/monitoring/operator.go
Add Alertmanager to the values in case of disabled state too
To avoid deploy errors
> [Monitoring] Add deafult Alertmanager values

- config/config.yaml.dist
cadence: createNonexistentDomain should default to true
> cadence: createNonexistentDomain should default to true

- cluster/hooks_ingress.go
Use `banzaicloud.io` as a cert domain when there is no base domain configured.
Ingress posthook requires a default CA.
When it's missing the posthook generates one on it's own.
In order to do that, it needs a DNS name which is usually the base domain.
There is no base domain though when the platform DNS is disabled.
> Use banzaicloud.io when there is no base domain

- internal/clusterfeature/features/monitoring/common.go
- internal/clusterfeature/features/monitoring/operator.go
- internal/clusterfeature/features/monitoring/spec.go
Make providers of Alertmanager optional
> [Monitoring] Make providers of Alertmanager optional

- internal/istio/istiofeature/reconcile_backyards.go
- internal/istio/istiofeature/reconcile_canary_operator.go
- internal/istio/istiofeature/reconcile_istio_operator.go
Fix Backyards helm chart names
The config contains fully qualified chart names. Previous code manually prefixed chart names with repository.
> Fix Backyards helm chart names

- internal/clusterfeature/features/monitoring/operator.go
- internal/clusterfeature/features/monitoring/operator_secret.go
Remove readonly tag from generated secrets in case of Monitoring feature
We can't delete these secrets with readonly tag
> [Monitoring] Remove readonly tag from generated secrets

- config/config.yaml.dist
- go.mod
- go.sum
- internal/cmd/config.go
- internal/istio/istiofeature/api.go
- internal/istio/istiofeature/reconcile.go
- internal/istio/istiofeature/reconcile_backyards.go
- internal/istio/istiofeature/reconcile_istio_cr.go
Add support for the latest Backyards release.
Backyards is configured to use its own prometheus and grafana deployment, the integration with Pipeline monitoring feature will be added in the near future.
> Use the latest Backyards release for the service mesh cluster group feature

- spotguide/merge.go
- spotguide/merge_test.go
* Fix a panic when `dst` and `src` are both slices, but `src` is longer than `dst`.
* Simplify existing code.
* Add tests covering modifications.
> Fix object merge

- spotguide/merge.go
- spotguide/merge_test.go
| Bug fix?        | maybe
* Check for nil objects
* Return errors on invalid arguments
* A few more test cases
If a `map[string]interface{}` typed `nil` was passed in `dst` the code panicked. This was possible, because the code only checked for `interface{}` typed `nil`s, and the problem did not manifest before because unmarshal- and decode-like functions never return `map[string]interface{}` typed `nil`s.
> Add check for nil objects (map[string]interface{} typed nils)

- cmd/worker/main.go
- internal/clusterfeature/features/securityscan/operator.go
- internal/clusterfeature/features/securityscan/resource_service.go
- internal/clusterfeature/features/securityscan/spec.go
- The PR covers the include-all (include + *) scenario for the security scan webhook configuration
- It also adds error handler for the feature operator used for cases when the activation of the feature encounters  (minor) errors (eg.: inexistent ns is passed through the api) 
fixes #2435
> Security scan feature - handle include-all scenario

- internal/clusterfeature/features/logging/operator.go
- internal/clusterfeature/features/logging/values.go
Add  `IfNotPresent` `pullPolicy` to Fluentbit and Fluentd image values
`pullPolicy` in body is required in case of non empty image object
> [Logging] Add pullPolicy to Fluentbit and Fluentd image values

- docs/cluster-feature.md
- internal/clusterfeature/features/dns/manager.go
- pkg/any/value.go
- pkg/any/xform.go
Rename `opaque` package to `any`.
`any` is a better name for `interface{}` than `opaque`
> Rename opaque to any

- internal/security/anchore_service.go
useing createorupdate method to avoid version errors when storing generated user secrets
> fix secret handling for generated anchore users

- internal/clusterfeature/features/securityscan/operator.go
internal service existence should not depend on flags set on the cluster instance (internal services related to a cluster can be retrieved independently)
the PR removes the code that manages the securityscan flag in the internal service
> remove securityscan flag handling from the internal service

- internal/clusterfeature/features/logging/operator.go
- internal/clusterfeature/features/logging/values.go
Set service monitor values in case of logging-operator-logging
> [Logging] Set service monitor in case of logging-operator-logging

- cmd/worker/main.go
- internal/clusterfeature/features/logging/common.go
- internal/clusterfeature/features/logging/operator.go
- internal/clusterfeature/features/logging/operator_test.go
- internal/clusterfeature/features/logging/output_definition.go
- internal/clusterfeature/features/logging/output_definition_azure.go
- internal/clusterfeature/features/logging/output_definition_gcs.go
- internal/clusterfeature/features/logging/output_definition_oss.go
- internal/clusterfeature/features/logging/output_definition_s3.go
- use `ClusterOutput` definitions instead of `Output`
- create `ClusterFlow` resources
- create `ClusterOutput` definitions and `ClusterFlow` resources for Loki
> [Logging] Improvements

- api/hpa.go
- cmd/pipeline/main.go
Use monitoring feature in HPA instead of the old `Get[FEATURE]` api.
We would like to get rid of feature setters/getters. This is the last dependency on them.
> Use monitoring feature in HPA

- cluster/eks.go
- Add back `RbacEnabled = true` to EKS.
```go
2019/11/19 12:55:38 Storing encryption key in a secret
panic: secrets is forbidden: User "system:serviceaccount:pipeline-system:dashboard-kubernetes-dashboard" cannot create resource "secrets" in API group "" in the namespace "kube-system"
goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc4203a6800)
/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/key …
```
> eks: RBAC should be always enabled

- internal/clusterfeature/features/logging/common.go
- internal/clusterfeature/features/logging/operator.go
- internal/clusterfeature/features/logging/operator_flow_resource.go
- internal/clusterfeature/features/logging/operator_output_definition.go
- internal/clusterfeature/features/logging/output_definition.go
- internal/clusterfeature/features/logging/output_definition_azure.go
- internal/clusterfeature/features/logging/output_definition_base.go
- internal/clusterfeature/features/logging/output_definition_bucket.go
- internal/clusterfeature/features/logging/output_definition_loki.go
- internal/clusterfeature/features/logging/output_definition_oss.go
- internal/clusterfeature/features/logging/output_definition_s3.go
In case of enabled `Loki` and `cluster output` we currently create 2 `ClusterFlow`. After these changes we only create just one with name `banzai-logging-flow`
```yaml
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
creationTimestamp: 2019-11-20T10:08:27Z
generation: 1
name: banzai-logging-flow
namespace: pipeline-system
resourceVersion: "510377"
selfLink: /apis/logging.banzaicloud.io/v1beta1/namespaces/pipeline-system/clusterflows/banzai-logging-flow
uid: aaaaaa-bbbb-cccc-dddd-eeefffrree
spec:
outputRefs:
- s3-output
- loki-output
selectors: {}
status: {}
kind: List
metadata: …
```
> [Logging] Create only one ClusterFlow resource

- internal/clusterfeature/features/logging/common.go
- internal/clusterfeature/features/logging/operator_flow_resource.go
- internal/clusterfeature/features/logging/operator_output_definition.go
- internal/clusterfeature/features/logging/output_definition.go
Add service labels to output definitions and flow
In case of service update now we delete all previously created `ClusterOutput`-s and `ClusterFlow`. With this change we can granted to delete only those `ClusterOutput`-s and `ClusterFlow` that we created with Pipeline
> [Logging] Add service labels to output definitions and flow

- cluster/hookfunctions.go
- cluster/hooks.go
- pkg/cluster/base.go
Remove PVC operator posthook
According to @stoader this isn't actually used anywhere at the moment. We may add this back later as an integrated service.
Removing this will also allow us to shorten the list of required Azure permissions.
> Remove PVC operator posthook

- cluster/hooks.go
- cluster/hooks_nodelabels.go
- internal/clusterfeature/features/logging/operator.go
- internal/clusterfeature/features/monitoring/operator.go
- internal/clustergroup/deployment/deployment.go
- pkg/jsonstructure/encode.go
- pkg/jsonstructure/encode_test.go
- pkg/mirror/struct_iter.go
- spotguide/spotguide.go
A function to replace json.Marshal+json.Unmarshal combos.
It looks better. (And its probably faster.)
> Replace consecutive json.Marshal+Unmarshal calls

- internal/providers/azure/pke/workflow/create_cluster.go
| Related tickets | fixes #2535
This PR fixes the Azure PKE cluster create flow to pass a BRN to the cluster setup workflow.
Cluster setup workflow needs a BRN formatted secret ID.
> Fix config secret ID in azure PKE cluster setup

- cluster/hookfunctions.go
- cluster/hooks.go
- internal/cluster/clustersetup/activity_label_kube_system_namespace.go
- internal/cluster/clustersetup/activity_label_kube_system_namespace_test.go
- internal/cluster/clustersetup/integration_test.go
- internal/cluster/clustersetup/workflow.go
- internal/cluster/clustersetup/workflow_test.go
- pkg/cluster/base.go
- pkg/k8sutil/namespace.go
Relocate kube system label posthook to cluster setup workflow
Posthooks are deprecated
> Relocate kube system label posthook

- api/cluster_update.go
- cluster/eks.go
- cluster/manager_delete.go
- cmd/worker/eks.go
- internal/providers/amazon/eks/workflow/amazon.go
- internal/providers/amazon/eks/workflow/create_cluster_test.go
- internal/providers/amazon/eks/workflow/create_cluster_user_access_key_activity.go
- internal/providers/amazon/eks/workflow/create_infra.go
- internal/providers/amazon/eks/workflow/delete_cluster.go
- internal/providers/amazon/eks/workflow/delete_cluster_user_access_key_activity.go
- internal/providers/amazon/eks/workflow/delete_control_plane_activity.go
- internal/providers/amazon/eks/workflow/delete_infra.go
- internal/providers/amazon/eks/workflow/delete_infra_test.go
- internal/providers/amazon/eks/workflow/delete_orphan_nic_activity.go
- internal/providers/amazon/eks/workflow/delete_ssh_key_activity.go
- internal/providers/amazon/eks/workflow/delete_stack_activity.go
- internal/providers/amazon/eks/workflow/get_nodepool_stacks.go
- internal/providers/amazon/eks/workflow/get_orphan_nics_activity.go
- internal/providers/amazon/eks/workflow/get_owned_elbs_activity.go
- internal/providers/amazon/eks/workflow/get_subnet_stacks_activity.go
- internal/providers/amazon/eks/workflow/get_vpc_config_activity.go
- internal/providers/amazon/eks/workflow/update_asg_activity.go
- internal/providers/amazon/eks/workflow/update_cluster.go
- internal/providers/amazon/eks/workflow/wait_elbs_deletion_activity.go
EKS cluster update & delete flow re-implemented using Cadence workflow
Cadence workflow adds more resiliency to EKS cluster delete & update and ability to continue the flow in case an error occurred after the error has been remedied.
> Eks deleteflow cadence

- api/cluster/pke/commands.go
- cluster/ack.go
- cluster/aks.go
- cluster/common.go
- cluster/create_workflow.go
- cluster/dummy.go
- cluster/ec2_pke.go
- cluster/eks.go
- cluster/gke.go
- cluster/hookfunctions.go
- cluster/hooks.go
- cluster/kubernetes.go
- cluster/manager_common_updater.go
- cluster/oke.go
- cmd/worker/main.go
- internal/providers/azure/pke/driver/commoncluster/cluster.go
- pkg/cluster/base.go
- pkg/common/common.go
Relocate label nodes posthook to legacy cluster create workflow
Posthooks are deprecated
It's moved to legacy cluster create instead of cluster setup, because it's limited to AKS and ACK.
After https://github.com/Azure/AKS/issues/1088 it will be ACK only.
> Relocate label nodes posthook

- docs/developer.md
- pkg/cluster/eks/defaults.go
Update used EKS AMIs to the latest version. Tested with K8s 1.14.
> Update EKS AMIs

- docs/postman/e2e_test.postman_collection.json
Remove ttlMinutes example value from update cluster as users may inadvertently delete clusters.
> remove ttlMinutes from cluster updates postam examples

- internal/providers/pke/pkeworkflow/wait_for_cf_completion_activity.go
> Fix: collecting AWS stack failures when PKE VPC creation fails is broken

- internal/clusterfeature/features/logging/operator.go
Add service label to Logging resource
We add this label to `ClusterFlow`-s and `ClusterOutput`-s too
> [Logging] Add service label to Logging resource

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/workflow/create_cluster.go
Pass cluster distribution to cluster setup workflow in Azure PKE cluster creation workflow.
Without the distribution value the Tiller install activity does not get executed correctly.
> Pass missing field to cluster setup workflow

- src/cluster/eks.go
Let through user-provided custom AMI in EKS create cluster request
User-provided custom AMIs were checked against AMIs published by AWS during cluster create and rejected not matched any of those. This verification is not needed to allow users to pass their own custom AMIs.
> Fix: EKS create flow doesn't accept user provided custom AMI

- internal/clusterfeature/features/logging/common_test.go
- internal/clusterfeature/features/logging/kubernetes.go
- internal/clusterfeature/features/logging/operator.go
- internal/clusterfeature/features/monitoring/common_test.go
- internal/clusterfeature/features/monitoring/kubernetes.go
- internal/clusterfeature/features/monitoring/operator.go
- internal/clusterfeature/features/vault/common_test.go
- internal/clusterfeature/features/vault/kubernetes.go
- internal/clusterfeature/features/vault/operator.go
- internal/kubernetes/service.go
- Use own Kubernetes service in each intergrated service
- Add `Update` to Kubernetes service
Currently we can't update our Kubernetes resources. The next PR will contain these changes in each intergrated service (where it's needed)
> Add update to Kubernetes service

- cmd/pipeline/main.go
- cmd/worker/azure.go
- cmd/worker/main.go
- internal/providers/azure/pke/adapter/gorm_store.go
- internal/providers/azure/pke/adapter/gorm_store_test.go
- internal/providers/azure/pke/cluster.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/driver/cluster_deleter.go
- internal/providers/azure/pke/driver/cluster_updater.go
- internal/providers/azure/pke/driver/common.go
- internal/providers/azure/pke/driver/commoncluster/cluster.go
- internal/providers/azure/pke/driver/ssh.go
- internal/providers/azure/pke/store.go
- internal/providers/azure/pke/workflow/delete_cluster_from_store_activity.go
- internal/providers/azure/pke/workflow/delete_nodepool_from_store_activity.go
- internal/providers/azure/pke/workflow/set_cluster_status_activity.go
- internal/providers/azure/pke/workflow/update_cluster_accesspoints_activity.go
- src/api/cluster.go
- src/api/cluster/pke_azure.go
- src/api/cluster/pke_azure_test.go
- src/cluster/autoscale.go
- src/cluster/common.go
Removed `AzurePKE` and `PKEOnAzure` prefixes where they were unnecessary.
Their package already indicates the same thing.
> Remove superfluous Azure PKE prefixes

- internal/integratedservices/services/logging/common_test.go
- internal/integratedservices/services/logging/kubernetes.go
- internal/integratedservices/services/logging/operator.go
- internal/integratedservices/services/logging/operator_flow_resource.go
Update `Logging` and `ClusterFlow` resources instead of deleting and recreating
> [Logging] Update resources instead of deleting and recreating

- internal/cluster/endpoints/endpoints.go
Change service url format. After this change the service url will look like this: `loki.pipeline-system.svc:3100`
> Change Service URL format

- cmd/pipeline/main.go
- cmd/worker/main.go
- pkg/cadence/client_error.go
- src/api/cluster.go
- src/api/secrets.go
- src/cluster/create_workflow.go
- src/cluster/manager.go
- src/cluster/manager_create.go
Set error status when the legacy workflow fails, and don't retry config download 30 times when permission errors occur.
> Fix error handling of legacy cluster create workflow

- internal/providers/amazon/eks/workflow/amazon.go
- internal/providers/amazon/eks/workflow/create_asg_activity.go
- internal/providers/amazon/eks/workflow/create_eks_control_plane_activity.go
- internal/providers/amazon/eks/workflow/create_iam_roles_activity.go
- internal/providers/amazon/eks/workflow/create_infra.go
- internal/providers/amazon/eks/workflow/create_subnet_activity.go
- internal/providers/amazon/eks/workflow/create_vpc_activity.go
- internal/providers/amazon/eks/workflow/delete_control_plane_activity.go
- internal/providers/amazon/eks/workflow/delete_infra.go
- internal/providers/amazon/eks/workflow/delete_stack_activity.go
- internal/providers/amazon/eks/workflow/update_asg_activity.go
- src/cluster/eks_update_cluster.go
- send heartbeat when waiting for AWS CF stack create, update, delete complete and meanwhile waiting for spot fulfilment
- set heartbeat timeout for related actions
At the moment we set 5 minute timeout most of stack related actions and 20 minutes for EKS control plane create, which means in case of a worker restart these actions are not retried until this time out occurs. By setting a short heartbeat timeout 45 sec and sending heartbeats each 30 sec, meanwhile waiting these action are retried in a much shorter timeframe. There are no separate actions created for stack complete wait, as it would over complicate the …
> EKS: send heartbeats when waiting for stack create, update

- internal/providers/amazon/eks/workflow/update_asg_activity.go
- pkg/providers/amazon/autoscaling/prometheus.go
- src/cluster/eks_update_cluster.go
- use workflow id as token base for update actions
- exit from update activity when there's no change in stack
- add mutex to ASG fulfilment wait timer map
> EKS update: use workflow id as token base, add mutex to ASG fulfilment wait

- .vscode/launch.json
Otherwise templates are not found.
> set CWD for VSCode launch targets

- internal/providers/azure/pke/driver/commoncluster/cluster.go
- internal/providers/pke/pkeworkflow/pkeworkflowadapter/cluster_manager.go
- pkg/k8sutil/configtemplate.go
- pkg/k8sutil/configtemplate_test.go
- src/api/cluster.go
- src/cluster/ack.go
- src/cluster/aks.go
- src/cluster/common.go
- src/cluster/dummy.go
- src/cluster/ec2_pke.go
- src/cluster/eks.go
- src/cluster/gke.go
- src/cluster/kubernetes.go
- src/cluster/oke.go
It uses a separate Kubernetes config to return to users over the API. Not all provider implementations support this right now, but gradually we will upgrade all of them. Until then, they will provide the same config as before.
This is necessary from a security perspective, because the Kubernetes config used internally has cluster admin privileges and contains non-expiring, explicit credentials that should not be exposed and shared between users.
In the current implementation the EKS kubeconfig is produced from the endpoint data available in the admin config, but we can expect to have implementations that will go to the …
> Return a separate k8s config through the API that is used internally

- internal/integratedservices/services/logging/operator_flow_resource.go
Create `ClusterFlow` resource in case of non empty output list
to avoid this type of errors:
```
failed to create cluster flow resource: failed to create Object: ClusterFlow.logging.banzaicloud.io \"banzai-logging-flow\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"logging.banzaicloud.io/v1beta1\", \"kind\":\"ClusterFlow\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2020-01-21T12:27:48Z\", \"generation\":1, \"labels\":map[string]interface {}{\"banzaicloud.io/service\":\"logging\"}, \"name\":\"banzai-logging-flow\", \"namespace\":\"pipeline-system\", …
```
> [Logging service] Create flow resource in case of non empty output list

- internal/integratedservices/service.go
- internal/integratedservices/service_test.go
| Bug fix?        | maybe
| New feature?    | maybe
Return an error when the user is trying to activate an already active service.
Integrated services have an "activate once, update many" semantic.
> Check for service re-activation

- charts/pipeline/Chart.yaml
- charts/pipeline/values.yaml
- cmd/pipeline/main.go
- internal/cmd/config.go
- internal/global/nplabels/label_validator.go
- internal/providers/azure/pke/driver/preparers.go
- pkg/cluster/aks/aks.go
- pkg/cluster/eks/eks.go
- pkg/cluster/gke/gke.go
- pkg/cluster/pke/types.go
- pkg/common/common.go
- pkg/kubernetes/label_validator.go
- pkg/kubernetes/label_validator_test.go
- pkg/providers/oracle/cluster/cluster.go
- src/cluster/ack.go
- src/cluster/common_test.go
- src/cluster/ec2_pke.go
| Related tickets | partially related to [#2172](https://github.com/banzaicloud/pipeline-web/issues/2172)
- remove kubernetes.io from forbidden domains
- add validation for known forbidden label keys like  kubernetes.io labels used by kubelet 
- use the same labelValidator in all cluster node pool validations
UI needs to be modified so that reserved labels (banzacloud.io) are filtered out from a cluster update request which is addressed by  [#2172](https://github.com/banzaicloud/pipeline-web/issues/2172)
> remove kubernetes.io from forbidden domains & add forbidden labels list

- src/api/cluster.go
Return admin kubernetes config for the AWS EKS clusters as before.
AWS does not provide a clean way to manage users other than configuring the auth configmap on the cluster, which requires admin privileges (and a shared secret) to access the cluster, which we wanted to avoid in the first place.
> revert returning k8s user config 

- src/cluster/nodelabels.go
In case of cluster update, label map is not sent if there are no changes in labels, however in case of an empty label map all existing user labels should be deleted.
> delete node pool labels in case Label map is empty

- config/config.yaml.dist
- internal/cmd/config.go
- internal/global/config.go
- src/api/cluster.go
- src/cluster/eks.go
Adds a configuration flag to remove credentials from EKS kubeconfig exposed through the API.
To avoid exposing shared secrets accidentally in case the administrator explicitly wants this.
> Optionally enable removing credentials from EKS kubeconfigs

- internal/integratedservices/services/logging/output_definition_loki.go
- internal/integratedservices/services/monitoring/operator.go
- internal/integratedservices/services/monitoring/values.go
Add `datasources` field to Grafana chart values
> [Monitoring] Add datasources field to Grafana chart values

- charts/pipeline/values.yaml
Bugfix to set the `strategy.rollingUpdate` field to avoid a conflict on upgrades from rollingUpdate strategy.
> Fix: set rollingUpdate to null if type is Recreate

- charts/pipeline/Chart.yaml
Version 0.5.2 has been tagged accidentally, thus skipped.
Bump chart version
> Bump chart version

- internal/integratedservices/services/monitoring/operator.go
- internal/integratedservices/services/monitoring/values.go
Add explicit datasource under the sidecar key and remove from the global config where it was causing the grafana container to fail.
> Add sidecar key

- cmd/worker/main.go
Register cluster deleter for imported k8s clusters with cloud `kubernetes` and distribution `unknown`.
The deleter for imported k8s clusters was registered under the wrong key.
> fix k8s cluster deleter registration key

- internal/providers/azure/pke/driver/cluster_creator.go
- Bump PKE version to support Kubernetes 1.17 on Azure
Current version only support Kubernetes up to 1.16
> Bump PKE version to support Kubernetes 1.17 on Azure

- internal/providers/amazon/eks/workflow/amazon.go
- internal/providers/amazon/eks/workflow/create_iam_roles_activity.go
- internal/providers/amazon/eks/workflow/create_iam_roles_activity_test.go
- templates/eks/amazon-eks-iam-cf.yaml
The EKS code couldn't handle IAM resources defined by full path, this PR fixes that.
To handle resources under paths (other than "/").
Also this fixes `packageCFError` formatting.
Splitting is possible in CF as well and also selection from an array, but selecting the last element from and array/list is not possible easily, so the extraction is done in the surrounding Go code.
> eks: fix resource id path handling in IAM

- internal/integratedservices/services/securityscan/manager.go
- internal/integratedservices/services/securityscan/operator.go
…re version removed (to be populated with direct call)
| Bug fix?        |no
- the security scan service output is provided with the correct image validator (chart) version
- the anchore engine version is removed from the output
the servicce related output was wrong (and statically added)
the anchore version can be retrieved dinamically instead of using wired or configuratio-provided value
> security scan integrated service - output provided with more precise information

- internal/integratedservices/services/monitoring/operator.go
- internal/integratedservices/services/monitoring/values.go
- Enable service monitor in pushgateway
- Change install process, firstly we install Prometheus operator and then Pushgateway
> [Monitoring] Enable service monitor in pushgateway

- internal/providers/amazon/eks/workflow/bootstrap_activity.go
| Related tickets | https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/268, https://github.com/banzaicloud/pipeline/pull/2699
The aws-iam-authenticator doesn't handle path currently in role mappings: https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/268
Once this bug gets fixed our code won't work, so we are making it future compatible by adding the role id with and without a path to the mapping. Since IAM role IDs are unique within an account this is not a security concern.
> eks: make aws-auth ConfigMap future compatible

- internal/kubernetes/client_factory.go
- pkg/helm/client.go
Closing `tillerTunnel` even when an error is returned, because it can be possibly open:
```go
// New creates a new and initialized tunnel.
func New(namespace string, client kubernetes.Interface, config *rest.Config) (*kube.Tunnel, error) {
podName, err := GetTillerPodName(client.CoreV1(), namespace)
// in this case there is no leak
if err != nil {
return nil, err
}
t := kube.NewTunnel(client.CoreV1().RESTClient(), config, namespace, podName, environment.DefaultTillerPort)
// in this case there is a tunnel even if ForwardPort returns an error,
// and that tunnel is …
```
> tiller: eliminate possible tunnel leaks

- internal/providers/pke/pkeworkflow/delete_cluster.go
…re version removed (to be populated with direct call)
| Related tickets | fixes #2683
Timing out activities have been provided with rety policy in the cluster delete workflow
Timing out activities caused the workflow to quit, leaving resources undeleted in the cloud
Affects PKE clusters
> add retry policy to the cluster delete workflow activities

- internal/providers/amazon/eks/workflow/create_eks_control_plane_activity.go
Catch nil pointer errors when there's no cluster info returned in details and error is different than ErrCodeResourceNotFoundException.
> EKS: fix nil reference when creating EKS control plane

- go.mod
- go.sum
- internal/cmd/config.go
| Related tickets | related to #2688 
Use latest v0.1.0-rc6.1 kubefed image.
> kubefed: use latest banzai image

- .circleci/config.yml
Fixes:
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD for the superuser. Use
"-e POSTGRES_PASSWORD=password" to set it in "docker run".
You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
without a password. This is *not* recommended. See PostgreSQL
documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
Exited with code 1
```
> ci: postgres needs explicit grant now

- internal/integratedservices/services/vault/common_test.go
- internal/integratedservices/services/vault/operator.go
| Related tickets | fixes #2726 
Retrying to query the service account token for vault for doing token reviews until the actual token material becomes visible in the Data field.
**squash please**
> vault-is: fix service account token visibility race-condition

- cmd/worker/aws.go
- internal/ark/client/client.go
- internal/providers/pke/pkeworkflow/delete_aws_pool_activity.go
- internal/providers/pke/pkeworkflow/delete_cluster.go
- internal/providers/pke/pkeworkflow/delete_nlb.go
- internal/providers/pke/pkeworkflow/delete_vpc_activity.go
- internal/providers/pke/pkeworkflow/heartbeat_option.go
- internal/providers/pke/pkeworkflow/update_cluster.go
On cluster deletions (aws - pke) waiting for the deletion to complete is factored out into a dedicated activity. The activity sends heartbeats to the cadence server while waits for the aws lib specific blocking call.
The deletion workflow gets more robust with this approach; the possibility of failures due to timeouts is reduced.
This is a WIP it is to be extended to other blocking calls too
> wait for deletion to complete (aws-pke) - long running activities

- internal/providers/azure/pke/driver/commoncluster/cluster.go
- src/cluster/ec2_pke.go
When cluster is not ready, like there's no k8s secret yet, node pool labels are not available as they are stored on cluster. They are only fetched in case the cluster isReady, which is not implemented yet on PKE clusters, resulting in errors codes, instead of 206 StatusPartialContent codes.
> fix nodepool API returning 500 errors when PKE clusters are not ready

- Makefile
- Use the downloaded `protoc` binary.
- Save the includes as well to allow the usage of predefined custom types (like Timestamp).
> protoc: use the bin version and use includes

- src/api/secrets.go
| Related tickets | fixes #2770
This PR fixes the Secret API and returns 404 for GET requests when a secret cannot be found.
> Return 404 when a secret cannot be found

- internal/providers/pke/pkeworkflow/delete_vpc_activity.go
Fix the delete VPC activity return value and made error messages cleaner
Delete VPC activity erroneously reported error when initiating deletion
> improve / fix misleading error messages while deleting VPC stacks

- internal/app/pipeline/secrettype/types.go
- internal/secret/types/type_azure_storage_account.go
- internal/secret/types/type_azure_storage_account_test.go
- internal/secret/types/types.go
We store azure storage accounts in the public secret store. This PR adds a new secret type for that.
> Add missing azure storage account secret type

- internal/providers/pke/pkeworkflow/delete_cluster.go
fix error variable scope in the cluster delete workflow
due to the too wide scope of a declared error variable error flow was handled inconsistently
> fix error variable scope in the cluster delete workflow

- internal/providers/pke/pkeworkflow/delete_cluster.go
fix error variable scope in the cluster delete workflow
due to the too wide scope of a declared error variable error flow was handled inconsistently
> fix (err) variable scope in the cluster delete workflow

- internal/clustergroup/manager.go
- internal/federation/reconcile_member_clusters.go
| Related tickets | fixes #2026 
Return all validation errors combined instead of returning only the first one.
> clustergroupAPI: combine validation errors

- config/config.yaml.dist
- internal/cmd/config.go
- src/api/hpa.go
- src/cluster/hooks.go
| Related tickets | fixes #2785 2748
- Use latest hpa-operator & kube-metrics-adapter chart, which is basedon latest controller runtime, custom metrics endpoint is no longer used
- Fix Prometheus url setup for kube-metrics-adapter 
Some helm based operators may fail, in case custom metrics endopoint exists, but doesn't return any items, as described in: https://github.com/banzaicloud/pipeline/issues/2748
> hpa: use latest hpa chart, fix Prometheus url

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_eks_node_pool_all_of.go
- .gen/pipeline/pipeline/model_node_pool.go
- apis/pipeline/pipeline.yaml
- apis/pipeline/postman.json
- internal/cluster/clusterworkflow/activity_create_node_pool.go
- internal/cluster/distribution/eks/eksadapter/node_pool_processor.go
- internal/cluster/distribution/eks/eksadapter/node_pool_validator.go
- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- internal/cluster/distribution/eks/node_pool.go
The cluster create API supports guessing subnet IDs for node pools
when the subnet is created during cluster create
(based on CIDR an AZ).
In the subnet API this is not necessary,
because it does not allow adding new subnets to the cluster.
Guessing the correct subnet ID is necessary when the subnet is not yet created.
It's not necessary when adding new node pools.
> Remove subnet guessing from node pool API

- internal/cmd/config.go
| Bug fix?        |no
| Related tickets | https://github.com/banzaicloud/anchore-image-validator/pull/55
Updating `anchore-policy-validator` chart to 0.5.6 which contains `anchore-engine` version 0.6.x support.
> Update anchore-policy-validator chart version

- internal/cmd/config.go
| Related tickets | https://github.com/banzaicloud/anchore-image-validator/pull/55
Updating `anchore-policy-validator` chart to 0.5.6 which contains `anchore-engine` version 0.6.x support.
> Anchore-policy-validator upgrade

- go.mod
- go.sum
- internal/platform/log/k8s_logger.go
Override klog logger to make sure that kubernetes logs are in the same format in the output
Logs should have the same format to make sure that the log processing system can process all logs properly.
> Override klog logger output

- internal/security/anchore_client_test.go
| Related tickets | https://github.com/banzaicloud/pipeline-installer/pull/89
Fix `anchore-engine` URL in the TestMakeAnchoreClient.
> Fix anchore-engine URL in TestMakeAnchoreClient.

- config/config.yaml.dist
- internal/cmd/config.go
Use latest cluster autoscaler with latest RBAC to fix RBAC problem on latest K8s 1.17.
> cluster-autoscaler: use latest chart

- internal/clustergroup/manager.go
- internal/federation/reconcile_member_clusters.go
Delete cluster group when somebody want's to delete a cluster which is the last member of a cluster group.
Initially we didn't want to allow to delete last member cluster of a cluster group, because if the cluster group has no member it will be invisible on the UI, users can not attach new cluster to it, so the the flow was to delete the cluster group first. Apparently this creates too much confusion, it's easier to delete the whole cluster group in case somebody want to remove it's last cluster.
> allowing deleting of a cluster when it's last member of a cluster group

- src/auth/serviceaccount.go
| Related tickets | #2805
Fix panic when non-TLS clients call Pipeline, was introduced by #2805 
We need to support non-TLS requests as well.
> auth: fix non-tls calls

- internal/providers/vsphere/pke/workflow/create_cluster.go
- internal/providers/vsphere/pke/workflow/delete_cluster.go
Set missing cluster error status in case of Vsphere cluster create and delete
To avoid clusters stuck in `CREATING` and `DELETING` states
> [Vsphere] Set missing cluster error status  

- internal/providers/vsphere/pke/workflow/delete_cluster.go
Add force delete check to every error case in case of Vsphere cluster delete
To delete Vsphere clusters in case of errors too
> [Vsphere] Add force delete check to error handling

- .circleci/config.yml
| Deprecations?   |yes
Re-enabling Postgres schema diffs with migra.
The current Postgres differ (pgdump + plain diff) shows a lot of false positives (negatives?). Migra works better and is a widespread Postgres differ tool: https://github.com/djrobstep/migra
> db: diff postgres migrations with migra

- cmd/pipeline/main.go
Make cicdDB optional.
If CICD is not enabled, we still try to connect to its database.
> cicdDB is optional

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_create_pke_on_vsphere_cluster_request.go
- .gen/pipeline/pipeline/model_create_pke_on_vsphere_cluster_request_all_of.go
- .gen/pipeline/pipeline/model_pke_on_vsphere_node_pool.go
- apis/pipeline/pipeline.yaml
- cmd/worker/vsphere.go
- database/migrations/mysql/1586548268_add_storage_secret_column_from_vsphere_pke_clusters_table.down.sql
- database/migrations/mysql/1586548268_add_storage_secret_column_from_vsphere_pke_clusters_table.up.sql
- database/migrations/postgres/1586548268_add_storage_secret_column_from_vsphere_pke_clusters_table.down.sql
- database/migrations/postgres/1586548268_add_storage_secret_column_from_vsphere_pke_clusters_table.up.sql
- internal/providers/vsphere/pke/adapter/gorm_store.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/store.go
- internal/providers/vsphere/pke/workflow/create_cluster.go
- internal/providers/vsphere/pke/workflow/create_node_activity.go
- internal/secret/secrettype/secret.go
- internal/secret/types/type_vsphere.go
- src/api/cluster/pke_vsphere.go
Add a separate secret id/name field to vSphere create request to allow using different url, username, pwd, datacenter, datastore, res. pool, folder settings for vSphere storage class setup. This is optional, by default all these setting come from the main cluster secret.
> vsphere: add storage secret field to cluster create request

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/helm/helmadapter/helm_service.go
- internal/helm/service.go
- internal/helm2/service.go
- internal/helm2/service_test.go
- internal/integratedservices/services/dns/operator.go
- internal/integratedservices/services/helm.go
- internal/integratedservices/services/ingress/manager.go
- internal/integratedservices/services/ingress/traefik.go
- internal/integratedservices/services/logging/operator.go
- internal/integratedservices/services/monitoring/operator.go
- internal/integratedservices/services/securityscan/operator.go
- internal/integratedservices/services/vault/operator.go
- src/api/cluster.go
- src/api/cluster_update.go
- src/cluster/autoscale.go
- src/cluster/hook_workflow.go
- src/cluster/hookfunctions.go
- src/cluster/hooks.go
- src/cluster/hooks_ingress.go
- src/cluster/manager_common_updater.go
Provide a unified helm releaser interface that can be used in integrated services, posthooks and clustersetup jobs as well.
> helm3 unfied service adapter

- src/auth/authn.go
| Related tickets | https://github.com/banzaicloud/banzai-cli/pull/229
Send the initial login token in a header instead of a Cookie.
So the CLI login flow can work.
> auth: send initial token for cli in header

- .gen/pipeline/pipeline/model_helm_repos_add_request.go
- internal/cmd/helm.go
- internal/helm/helmadapter/gorm_repo_store.go
- internal/helm/helmadapter/helm2_env_service.go
- internal/helm/helmdriver/transport_http.go
- internal/helm/helmdriver/zz_generated.endpoint.go
- internal/helm/service.go
- internal/helm/service_test.go
- internal/helm/zz_generated.mock_test.go
- src/helm/install.go
- Make the helm2 envservice get an ensuringEnvResolver as well and backport the legacy functionality into it
- Make helm2's ListRepositories work by returning what is in the repo file instead of returning the defaults.
- Make a separate ModifyRepository handler to distinguish modifications from repo updates. 
- PatchRepository is removed until a use case comes up to implement it properly
> Helm repository api regression fixes

- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
- pkg/providers/amazon/cloudformation/cloudformation.go
- src/cluster/eks_update_cluster.go
Fixes stack update waiting to not retry final state errors.
Stacks in final state, completing with an error won't change, so retrying the wait operation does not make much sense.
> Do not retry failed stack errors

- internal/cmd/config.go
- internal/cmd/config_test.go
| Related tickets | https://github.com/banzaicloud/banzai-charts/pull/1090
The old traefik version (1.7.9) doesn't work properly with K8s version 1.18.
> Update traefik chart version

- internal/cmd/helm.go
- internal/helm/envresolver.go
- internal/helm/helmadapter/helm2_env_service.go
- internal/helm/helmadapter/helm3_env_service.go
- internal/helm/service.go
- internal/helm/zz_generated.mock_test.go
- src/helm/helm.go
- src/helm/install.go
* org level helm repositories (added by users) are restored when the helm environment is (re)created (eg.: pipeline-restart)
* password secrets for repositories are resolved during repository addition
* previously on pipeline application restart user added repositories were lost
* password secrets were not resolved when adding repositories
> Reconcile helm repos / Password credential resolution for helm repositories

- cmd/pipeline/main.go
- internal/helm/helmdriver/transport_http.go
- internal/helm/helmdriver/zz_generated.endpoint.go
- internal/helm/releaser.go
- internal/helm/service.go
- internal/helm/zz_generated.mock_test.go
- src/api/helm.go
- src/api/security.go
This PR decouples the helm version dependencies from the get image deployments operation (part of the security scan api)
This is required in order to support helm3 libraries too.
> decouple the helm version / implementation from security scan apis

- .circleci/config.yml
- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/helm/envresolver.go
- internal/helm/envresolver_test.go
- internal/helm/helmadapter/releaser_service.go
- internal/helm/releaser.go
- internal/helm/service.go
- internal/istio/istiofeature/api.go
- internal/istio/istiofeature/handler.go
- internal/istio/istiofeature/helm.go
- internal/istio/istiofeature/helm_test.go
- internal/istio/istiofeature/helm_values_test.go
- internal/istio/istiofeature/mesh.go
- internal/istio/istiofeature/reconcile_backyards.go
- internal/istio/istiofeature/reconcile_canary_operator.go
- internal/istio/istiofeature/reconcile_istio_operator.go
- internal/istio/istiofeature/reconcile_node_exporter.go
- pkg/k8sclient/config.go
Helm3 support for the Backyards integration by replacing existing helm2 calls with the generic implementation.
Fixes for the helm3 implementation:
- add wait if configured
- explicit timeouts for release operations
- create namespace if it does not exist
To be able to switch to helm3,  and still support helm2 in the meantime.
> Helm3 support for the Backyards integrated service

- internal/istio/istiofeature/reconcile_canary_operator.go
- internal/istio/istiofeature/reconcile_istio_operator.go
Fix the options provided to the canary operator
Without that option the operator chart cannot be upgraded.
> Fix backyards canary operator options

- internal/helm/charter.go
- internal/helm/helmadapter/helm2_env_service.go
Fixes a bug: when listing charts for a given helm repo the backend ignored the sent in regexp boundaries (so no exact match was applied on repo name)
Charts were returned for all helm repos that matched the sent in repo name (eg: stable, banzai-stable)
> Repos name filter handled properly when listing charts

- cmd/pipeline/capabilities.go
Add helm version to capabilities API
CLI should be able to query the currently used Helm version.
> Add helm version to capabilities API

- internal/providers/vsphere/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/driver/cluster_updater.go
- Set node template name in cluster create and update flows
- Override template name from secret if it isn't present in the request
- Allow the user override node template in the request(s)
- Store node template name in DB to help UI cluster update flow to show the right node template name for the user
> Set template name in cluster create and update flows

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/cluster/clustersetup/workflow.go
- internal/cluster/clustersetup/workflow_test.go
- internal/cluster/workflow/delete_helm_deployments_activity.go
- internal/cmd/helm.go
- internal/helm/helmadapter/releaser_service.go
- internal/helm/releaser.go
- src/api/cluster.go
- src/api/secrets.go
- src/cluster/manager.go
- src/cluster/manager_delete.go
- src/helm/helm.go
* Remove tiller related activities from the cluster setup workflow
* Amendments to the Releaser implementation to handle all namespaces
* Decoupled delete all releases call from the helm version (affects cluster deletion)
No tiller is needed for helm 3
> ClusterSetup workflow enhanced not to install Tiller in case helm v3 is switched on 

- internal/helm/helmadapter/helm3_env_service.go
- internal/helm/helmadapter/releaser_service.go
- src/helm/helm.go
The helm chartlist response is made similar to the legacy (helm2)
Each helm chart version was displayed on the UI (broken backwards compatibility)
> List helm charts operation made backwards compatible

- internal/integratedservices/services/dns/common_test.go
- internal/integratedservices/services/helm.go
- internal/integratedservices/services/logging/common_test.go
- internal/integratedservices/services/logging/operator.go
- internal/integratedservices/services/logging/values.go
- internal/integratedservices/services/monitoring/common_test.go
- internal/integratedservices/services/vault/common_test.go
Make the logging integrated service aware whether it's running on helm3 or helm2 and set the appropriate `createCustomResource` flag accordingly
> Make the logging integrated service helm3 aware

- internal/istio/istiofeature/reconcile.go
Fix backyards uninstall order
Helm3 is sensitive on missing CRDs when trying to delete an object, therefore the removal of CRDs should be last
> Fix uninstall order for backyards components

- src/api/cluster_update.go
Fix condition before JSON bind in case of cluster update
The cluster update flow not started in case of `Amazon PKE`
Tested with
- Amazon PKE
- Amazon EKS
- vSphere PKE
> Fix Amazon PKE cluster update workflow

- internal/helm/api_service.go
- internal/helm/helmadapter/helm2_env_service.go
- internal/helm/helmadapter/helm3_env_service.go
- internal/helm/helmadapter/releaser_service.go
- internal/helm/helmdriver/transport_http.go
- internal/helm/helmdriver/zz_generated.endpoint.go
- internal/helm/service.go
- internal/helm/zz_generated.mock_test.go
- internal/integratedservices/services/zz_generated.mock.go
| API breaks?     |no
The PR has a series of amendments to the release api:
* releases in the response are decorated with the supported flag
* added new abstraction layer for high level service logic required by the rest API (to be refined / refactored later)
* other fixes related to the releases API (base64 encode fields, add missing information to the response)
H3 implementation in pipeline tries to remain backwards compatible with previous versions. Testing is underway, risen issues are being continuously fixed
> Release api related amendments

- cmd/pipeline/capabilities.go
Do not return helm capabilities if v3 is not enabled for backwards compatibility.
Latest banzai-cli uses the capabilities API to setup helm shims and it mistakenly sets up helm3 as the default even if it's not enabled on the pipeline instance yet.
> Fix logging integrated service helm3 upgrade issue

- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
Adding MaximumAttempts to the activity retryPolicy otherwise it fails with for the open-source version:
```
Id  Name           Distribution  Location   CreatorName  CreatedAt                  Status   StatusMessage                                                                                                                                 
1   nandi-options  eks           eu-west-1  bonifaido    2020-05-22T16:03:58+02:00  WARNING  failed to update node pool: both MaximumAttempts and ExpirationIntervalInSeconds on retry policy are not set, at least one of them must be …
```
> add processlog and MaximumAttempts to CalculateNodePoolVersionActivity

- Makefile
- cmd/worker/main.go
- go.mod
- go.sum
- internal/cmd/config.go
- internal/integratedservices/services/dns/common_test.go
- internal/integratedservices/services/helm.go
- internal/integratedservices/services/logging/common_test.go
- internal/integratedservices/services/monitoring/common_test.go
- internal/integratedservices/services/monitoring/migrator.go
- internal/integratedservices/services/monitoring/migrator_test.go
- internal/integratedservices/services/monitoring/operator.go
- internal/integratedservices/services/monitoring/operator_test.go
- internal/integratedservices/services/monitoring/values.go
- internal/integratedservices/services/vault/common_test.go
Fixes a typical CRD handling issue to support the helm v3 path, and upgrade the prometheus operator chart to avoid an upgrade issue that has been fixed in the grafana chart: https://github.com/helm/charts/commit/a63e6819b8acc4617cd480acd0d5094e482de2b5
Also add a migration step to avoid helm upgrade failures due to changed label selectors and api groups.
The integrated service should be upgraded as usual with the "save all changes" or cli `cluster service monitoring update` commands.
> Fix monitoring integrated service for helm3 support

- internal/clustergroup/deployment/helm.go
- internal/clustergroup/deployment/integration_test.go
- internal/clustergroup/deployment/manager.go
- src/api/clustergroup/deployment/create.go
- src/api/clustergroup/deployment/sync.go
- src/api/clustergroup/deployment/upgrade.go
Adds missing orgId from the chart description retreiver method of the clustergroup helm service. Without it the multicluster deployment feature will not be able to find a chart to deploy.
> Clustergroup deployment fix

- charts/pipeline/Chart.yaml
- charts/pipeline/values.yaml
Updates the chart version to release latest changes and upgrade to latest pipeline version
The pipelinectl drain command is broken in the previous chart version, thus we need at least a patch release, but since the pipeline version got outdated I decided to add it into this bump as well and make it a minor release instead.
> Bump chart version with latest pipeline version included

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
- templates/pke/master.cf.yaml
- templates/pke/masters.cf.yaml
- templates/pke/worker.cf.yaml
| Related tickets | fixes #2938
Use preinstalled PKE binary in the user data script.
It might make sense to also validate if the binary is executable. In this case the condition would look like:
```bash
if ! [ -x "$(command -v pke)" ]; then
fi
```
> Use preinstalled PKE binary

- internal/clustergroup/deployment/helm.go
- internal/clustergroup/deployment/manager.go
- internal/federation/deployment.go
- internal/federation/reconcile_controller.go
- internal/federation/reconcile_ext_dns.go
- internal/federation/reconcile_ext_dns_test.go
- internal/helm/helmadapter/helm_service.go
- internal/helm/integration_test.go
- internal/helm/service.go
- internal/helm2/service.go
- internal/istio/istiofeature/helm.go
- internal/istio/istiofeature/reconcile_backyards.go
- internal/istio/istiofeature/reconcile_canary_operator.go
- internal/istio/istiofeature/reconcile_istio_operator.go
- internal/istio/istiofeature/reconcile_node_exporter.go
Cluster group deployments made aware of the organisation which' member is performing operations. Relevant interface operations are provided with the orgID in order to use the proper repositories where appropriate. (These generic interface modifications propagated to the using modules as well)
Cluster group deployments only could be made from the builtin helm repositories
> Made cluster group deployments aware of the organizationID

- internal/cluster/distribution/eks/defaults.go
- internal/cluster/distribution/eks/ekscluster/eks.go
| Related tickets | https://github.com/banzaicloud/cloudinfo/pull/323
Update amis in case of EKS 1.14 and 1.15
> Update amis in case of EKS 1.14 and 1.15

- internal/cmd/config.go
- internal/global/config.go
- internal/helm/envresolver.go
- internal/helm/envresolver_test.go
- pkg/helm/helm.go
- src/helm/install.go
- src/helm/install_test.go
Made Helm home directory layout cleaner:
```
var/cache/
└── helm
├── orgs
│   └── myorg
│       ├── cache
│       │   ├── discovery-cache
│       │   └── http-cache
│       └── repository
│           └── cache
└── platform
└── repository
└── cache
```
Update: the old (helm2) implementation had also been moved to the new layout for consistency reasons.
The new structure is cleaner
> Change Helm home directory layout

- Dockerfile
- Dockerfile.alpine
- Dockerfile.debug
- Dockerfile.local
Until bzr is available in 3.12 or an alternative installation method is provided
> Pin Alpine version to 3.11

- templates/eks/amazon-eks-iam-cf.yaml
- templates/eks/amazon-eks-nodepool-cf.yaml
| Related tickets | fixes #2948 
Update EKS CloudFormation templates to align with latest EKS node group template: https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-05-08/amazon-eks-nodegroup.yaml
> EKS: update node pool CF template to latest EKS node group template

- internal/cluster/distribution/eks/defaults.go
- internal/cluster/distribution/eks/ekscluster/eks.go
Enable Kubernetes version 1.16 on EKS and add default ami image id for 1.16.
> EKS: enable K8s version 1.16

- templates/eks/amazon-eks-nodepool-cf.yaml
| Related tickets | fixes #2968 
Remove default image param from node pool CloudFormation template since it's unnecessary because Pipeline always sets default image in case it's not provided while it requires additional access rights for user.
> EKS: remove default image param from node pool CF

- internal/helm/helmadapter/releaser_service.go
- internal/helm/helmdriver/transport_http.go
* Release values are coalesced during release details retrieval (backwards compatibility reasons)
* Release name is generated when not explicitly sent in (release install failed)
* Release Version is passed to the backend (was omitted)
Overrides were not presented on the UI
> Coalesce values while retrieving release details

- docker-compose.yml
- go.mod
- go.sum
Revert the cadence client update
Looks like the latest SDK doesn't work with older Cadence versions.
> Revert cadence upgrade

- cmd/pipeline/main.go
- internal/helm/helmdriver/transport_http.go
Namespace information is passed to the backend when operating releases
Releases were always deployed to the default namespace regardless the selected one. Deletion failed on releases other than the default namespace.
The PR aligns the implementation to the helm 3 namespace handling
> Pass namespace information when installing, retrieving and deleting releases

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/cmd/config.go
- internal/secret/types/type_amazon.go
- internal/secret/types/types.go
Use the configured default region for amazon secret verification
Depending on the account, the hard-coded default region might not be available everywhere.
> Fix amazon secret default region

- docs/developer.md
This PR fixes the AWS IAM Authenticator binary install command, the EKS ami image query script and updates the same script's Kubernetes versions.
Because the original AWS IAM Authenticator command yielded an error, the image query script failed/didn't run properly with the incorrect region field and the Kubernetes versions lacked the current ones while included years-old deprecated versions.
See the individual commit messages for more details.
> docs(developer): fix EKS doc issues (AWS IAM auth binary install, EKS ami image query script)

- config/config.dev.yaml
- config/config.yaml.dist
- internal/cmd/config.go
Makes json the default log format in configuration
In production environments, we should log everything in json
Certain underlying libraries (looking at you client-go) thinks it's a good idea to define a global, non-overrideable logger,
so some log lines might not be encoded as JSON. AFAIK that's not a problem though, Fluentbit/D can convert those log entries to JSON (cc @tarokkk to confirm)
> Make json the default log format

- cmd/pipeline/main.go
Make audit log sensitive URL path filters more strict
> Make audit log sensitive patterns more strict

- internal/platform/gin/auditlog/auditlogdriver/log.go
- internal/platform/gin/auditlog/auditlogdriver/log_test.go
| Related tickets | related #3003
Fix request body when using logfmt log format
The logfmt formatter printed the memory address of the pointer
Not even sure why the request body is a pointer. We should take a look at this
> Fix request body when using logfmt log format

- internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/error.go
- internal/cluster/distribution/eks/eksworkflow/error.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
- src/cluster/eks_update_cluster.go
I introduced a `decodeCloudFormationError()` function to all 3
packages where cadence activities are used which would employ the
`packageCFError()` function to pack their returned
error in order to decode it before sending upwards.
Unfortunately there are 3 different "states" of the AWS/EKS distribution workflows with multiple instances of code duplication which made me implement the above mentioned functionality at 3 different places.
If anyone sees a good location for the single definition of this functionality, let me know and I will migrate these instances there.
In case of CloudFormation errors …
> fix: decoded CloudFormation error detail for logging purposes

- docs/developer.md
- internal/cluster/distribution/eks/defaults.go
- internal/cluster/distribution/eks/ekscluster/eks.go
Enable Kubernetes version 1.17 on EKS and add default AMI ids for 1.17.
> add support for eks 1.17

- cmd/pipeline/main.go
| Bug fix?        |  yes
If the basepath is configured incorrectly (with a trailing slash), the sensitive paths are not detected, so secrets can appear in the audit log. This is fixed with this PR.
```
{"application":"pipeline","channel":"audit","correlationID":"70b50df1-0d65-4dc1-a4a5-1b7d272e7a4c","http.clientIP":"3.133.90.137","http.method":"POST","http.path":"/pipeline//api/v1/orgs/1/clusters/59/pke/ready","http.requestBody":"{\"config\":\"YXBpVmV
```
> audit: fix sensitive path regexps for prefix with //

- .circleci/config.yml
Using Python 3 for `migra` (testing Postgres schema diffs).
Otherwise `migra` fails with (migra needs Python 3 now):
```bash
#!/bin/bash -eo pipefail
migra postgresql://postgres:postgres@localhost/pipeline_migrations postgresql://postgres:postgres@localhost/pipeline_automigrate --unsafe
Traceback (most recent call last):
File "/usr/local/bin/migra", line 7, in <module>
from migra import do_command
File "/usr/local/lib/python2.7/dist-packages/migra/__init__.py", line 4, in <module>
from .command import do_command
File …
```
> migra: use python3 explicitly

- internal/cmd/config.go
- internal/cmd/config_test.go
| Related tickets | n/a
Enable RBAC in traefik integrated service chart installation.
```
E0723 12:57:51.764291       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:pipeline-system:default" cannot list resource "ingresses" in API group "extensions" at the cluster scope
E0723 12:57:51.771417       1 reflector.go:205] github.com/containous/traefik/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: …
```
> traefik: rbac should be enabled

- internal/integratedservices/services/vault/manager_test.go
Fixes the vault address used in vault integrated service functional tests
In some cases Vault might not listen on a standard port, so hard-coding it in tests is a bad idea.
> Fix vault address in vault service tests

- cmd/worker/aws.go
- cmd/worker/main.go
- internal/cluster/distribution/pke/pkeaws/image_selector.go
- internal/cluster/distribution/pke/pkeaws/image_selector_defaults.go
- internal/cluster/distribution/pke/pkeaws/pkeaws.go
- internal/cluster/distribution/pke/pkeaws/pkeawsadapter/image_selector.go
- internal/providers/pke/pkeworkflow/cluster.go
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/create_master_activity.go
- internal/providers/pke/pkeworkflow/pkeworkflowadapter/cluster_manager.go
- pkg/cloudinfo/services.go
- src/cluster/ec2_pke.go
| Related tickets | fixes #3030
Integrate new image selector into PKE AWS create workflow
This is an intermediate step to better support GPU nodes.
> Integrate new image selector into PKE AWS create workflow

- BUILD.plz
Regular go tools look for go files in all directories.
This causes issues in case of please, because it actually stores
Go files in its plz-out directory.
The solution is to make it a dummy module,
because Go's package filtering (eg. ./...) ignores submodules.
> Automatically add go.mod to plz-out

- cmd/pipeline/main.go
- internal/cluster/distribution/eks/image_selector.go
- internal/cluster/distribution/eks/image_selector_test.go
| Related tickets | fixes #3051
Use GPU images for GPU instances
> EKS GPU support

- internal/cluster/distribution/eks/node_pool.go
- internal/cluster/distribution/eks/node_pool_test.go
| Related tickets | fixes #3017 
* Allow zero-sized autoscaled node pools (like at the time of cluster creation)
* Check if desired count is between the min and max size
> Fix create nodepool validation

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_eks_auth_config_roles.go
- .gen/pipeline/pipeline/model_eks_auth_config_users.go
- apis/pipeline/pipeline.yaml
- internal/cluster/distribution/eks/ekscluster/eks.go
- internal/cluster/distribution/eks/eksprovider/workflow/bootstrap_activity.go
- Fix OpenAPI `groups` field
- Fix request decode
- Fix `mapAccounts` field merge to avoid these type of errors:
```
ERRO[2020-08-04T14:48:49+02:00] cluster create workflow failed: failed to merge config map: failed to unmarshal mapAccounts from: - account1
- otheraccount
: error unmarshaling JSON: json: cannot unmarshal string into Go value of type map[string]interface {}  clusterID=0 clusterName=pregnor-local-200804-aws-auth-config-success-3 organizationID=1
```
> Auth config fixes

- cmd/worker/main.go
- internal/cluster/distribution/pke/pkeaws/image_selector_defaults.go
- internal/cluster/distribution/pke/pkeaws/image_selector_gpu.go
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- src/cluster/ec2_pke.go
| Related tickets | fixes #3050
Select GPU images for GPU instance types
To support GPU workloads better
> Add GPU image selector for PKE

- cmd/pipeline/main.go
- cmd/pipelinectl/main.go
- internal/app/pipelinectl/cli/commands/telemetry/telemetry.go
- internal/security/anchore_client.go
- src/api/anchore_proxy.go
- src/api/cluster_auth.go
- src/auth/oidc.go
- src/auth/tls.go
Setting TLS minimum version to 1.3 everywhere.
To improve security standards throughout the project.
> fix(TLS): configure TLS MinVersion to 1.3

- src/auth/oidc.go
Dex doesn't support TLS 1.3 yet.
Downgraded TLS 1.2 on OIDC provider to support old Dex.
Because old Dex does not support TLS 1.3 yet.
> fix(oidc): downgraded TLS to 1.2

- Makefile
Added waiting (and restarting) logic to `make start` in order to ensure both Dex and Cadence are properly initialized before the target returns successfully.
Dex sometimes restarts a couple times before it can start serving its content.
Cadence sometimes stops entirely and doesn't restart when it runs into an issue which will be fixed in version 0.11.0.
- [~Related Helm chart(s) updated (if needed)~
> chore(make): improved start target DX

- config/config.yaml.dist
- internal/cmd/config.go
- internal/global/config.go
- internal/pke/kubernetes.go
- pkg/cluster/pke/types.go
Allow changing the default network provider
In some environments cilium can't be used, so it makes sense to change the default to something else (eg. calico).
> Allow changing the default network provider

- internal/cluster/clusterworkflow/activity_create_node_pool.go
- internal/cluster/clusterworkflow/activity_delete_node_pool.go
- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_eks_control_plane_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_iam_roles_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_subnet_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_vpc_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_infra_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_stack_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/delete_aws_pool_activity.go
- internal/providers/pke/pkeworkflow/delete_vpc_activity.go
- pkg/providers/amazon/client_request_token.go
- src/cluster/eks_update_cluster.go
| Related tickets | fixes #3016 
Replaced cluster UUID, generated UUID and empty AWS client request tokens with Cadence workflow ID.
To provide a client request token that is unique among different "requests", but are the same between activity retries so AWS can handle same-stack requests in an idempotent fashion. ActivityID is not used, because it would be different for the same same-stack operation between activity retries.
> fix(AWS): added unique client request token

- internal/cluster/clusterworkflow/activity_create_node_pool.go
- internal/cluster/clusterworkflow/workflow_create_node_pool.go
- internal/cluster/clusterworkflow/workflow_delete_node_pool.go
| Related tickets | fixes #3031
1. Unwrapped Cadence errors at cluster node pool creation/deletion.
2. Removed all residue resources when an AWS/EKS node pool creation fails, including deleting failed-to-create CloudFormation stacks.
There were a couple minor issues such as 
- error details not being displayed and 
and one major issue namely 
- when the CF node pool / ASG stack creation failed, a non-describable (but list-able) failed stack was left behind which couldn't be deleted on the pipeline API due to shortcutting the request response due to no node pool entry in the database and also couldn't be recreated because …
> fix(EKS): removed node pool create failure residue

- Makefile
- README.md
- config/config.dev.yaml
- docker-compose.yml
- etc/docker/uiproxy/Dockerfile
- internal/secret/secrettype/secret.go
- internal/secret/types/type_google.go
- internal/secret/types/type_oracle.go
1. Removed Cadence workaround logic from `make start`
2. Replaced beta environment references with try environment references.
1. Because the Cadence 0.13 update brought stability to the corresponding docker image starting process and the workaround logic is not needed anymore.
2. Because the beta environment is being discontinued.
> chore: replaced beta env with try references, removed Cadence workaround

- Makefile
1. Added plz BUILD configuration backup for file generations regarding Anchore and CloudInfo clients.
2. Fixed the backup/restore message.
1. To preserve the plz BUILD configuration file.
2. It lacked the exact path being backed up
> chore(Makefile): added generation plz BUILD file backups, fixed backup/restore message

- config/config.yaml.dist
- go.mod
- go.sum
- internal/cmd/config.go
- internal/federation/config.go
- internal/federation/deployment.go
- internal/federation/reconcile_controller.go
- internal/helm/integration_test.go
| Related tickets | closes #3115 
Replaced custom Banzai Cloud kubefed chart usage with the official one.
The official chart now supports Helm v3, so we discontinue the custom chart.
Kubefed brought some other transitive dependency updates with itself. Checked the release notes, haven't seen potentially breaking changes.
[This](https://github.com/kubernetes-sigs/kubefed/pull/1261) PR changed the official kubefed chart value handling by putting the common image values under a `controller` and `webhook` fields in the main values file to provide separated control over the two.
|             Previous              |  ->   | …
> chore(kubefed): updated version (0.3.1-banzai.1->)0.4.0

- internal/cluster/distribution/eks/eksprovider/driver/cluster_creator.go
- internal/cluster/distribution/eks/eksprovider/driver/cluster_creator_test.go
Clarified the error message content.
Because the details are not added to the response returned to the user and this seemed a much less risky short-term solution than trying to find out whether we can add each detail to the response automatically. That approach requires more consideration.
> fix(EKSEncryptionConfig): clarified error message

- templates/eks/amazon-eks-nodepool-cf.yaml
Increase default node volume size to 50GB
This is a temporary fix to solve ephemeral storage issues.
We use 50GB as a default for PKE as well
> Increase EKS node volume size

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_amazon_provider_config.go
- .gen/pipeline/pipeline/model_create_eks_properties_eks.go
- .gen/pipeline/pipeline/model_update_node_pools_pke.go
- apis/pipeline/pipeline.yaml
Fixed OpenAPI specification typos
Because it grinds my gears to have typos in the public API specification.
I decided not to touch path elements and field names for now because it requires deeper examination as we unfortunately seems to rely on them elsewhere such as YAML `rolearn`/`userarn` for AWS auth configuration, `K8Sconfig` direct field manipulation across the code and there were `orgid` references found as well.
These need more care and I'm postponing these efforts.
- ~Related …
> fix(OpenAPI): fixed specification typos

- config/config.yaml.dist
Removed the `kubernetes.namespace` value from the exhaustive config example.
This configuration value is never referenced from the code and is very hard to understand the coexistence of this and `cluster.namespace` and what they might be affecting.
I assume based on the comment for the removed field, at some point we switched from `kubernetes.namespace` to `cluster.namespace` but the former reference remained.
- ~Related Helm chart(s) …
> chore(config.dist): removed `kubernetes.namespace`

- cmd/worker/eks.go
- cmd/worker/main.go
- config/config.yaml.dist
- internal/cluster/clusterworkflow/activity_create_node_pool.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/ec2.go
- internal/cluster/distribution/eks/eksprovider/workflow/get_ami_size_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/select_volume_size_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cmd/config.go
- src/cluster/eks_update_cluster.go
- templates/eks/amazon-eks-nodepool-cf.yaml
| Related tickets | closes #3129, closes #3130 
Added default node volume size configuration option and propagation to node pool creation from both cluster and node pool create requests. Also added AMI size check logic to ensure only bigger volume sizes are allowed.
To support configurable default node volume sizes. See the tickets for details.
Changed the discussed implementation plans because the cluster creation request doesn't go through the `NodePoolProcessor.ProcessNew()` function and has no access to AWS activities at API server side which made me realize the difference between the image and volume size defaults is …
> feat(EKS): added default node volume size configuration

- cmd/pipeline/main.go
- internal/cluster/distribution/eks/eksadapter/cluster_manager.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_cluster.go
- src/cluster/autoscale.go
| Related tickets | https://github.com/banzaicloud/pipeline-enterprise/pull/101
Starting the enterprise EKS cluster update workflow in case of an enterprise deployment.
Removing the autoscaler update skip in case of EKS.
Has to be merged after: https://github.com/banzaicloud/pipeline-enterprise/pull/101
> eks: enterprise cluster update workflow

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_eks_node_pool_all_of.go
- .gen/pipeline/pipeline/model_node_pool.go
- apis/pipeline/pipeline.yaml
EKS node pool list volume size type float32->int32
It's an integer value, using number instead of integer in the OpenAPI sepcification was a mistake.
> fix(OpenAPI/EKS/NPList): fixed volume size type

- internal/providers/vsphere/pke/adapter/gorm_store.go
- internal/providers/vsphere/pke/cluster.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/driver/preparers.go
- internal/providers/vsphere/pke/workflow/create_node_activity.go
VCPU and RAM inputs were missing from the clone specification when creating nodes.
> vsphere: pass vcpu and ram to cloneSpec

- internal/cmd/config.go
| Related tickets | related: https://github.com/banzaicloud/anchore-image-validator/pull/60
Update `anchore-policy-validator` chart version.
https://github.com/banzaicloud/anchore-image-validator/releases/tag/anchore-policy-validator%2F0.6.0
The new version of the chart doesn't deploy the default policy creator job.
> Bump anchore-policy-validator chart version

- internal/cluster/distribution/eks/eksadapter/node_pool_manager.go
- internal/cluster/distribution/eks/eksadapter/node_pool_manager_test.go
- internal/cluster/distribution/eks/service.go
Added missing subnet ID value to the node pool list output.
Because it is a creation field, but was missing.
CLI [PR](https://github.com/banzaicloud/banzaicloud.github.io/pull/1839).
Documentation [PR](https://github.com/banzaicloud/banzaicloud.github.io/pull/1839).
> fix(ListNodePools): added subnet ID retrieval

- internal/common/secret.go
- internal/platform/appkit/transport/http/problem_service.go
- internal/platform/appkit/transport/http/problems.go
- internal/platform/appkit/transport/http/problems_test.go
- src/secret/store.go
Fixed 3 issues around API error response and its logging.
1. Implemented the `NotFound` error interface on the `SecretNotFoundError` service error type so the corresponding status problem matcher would catch it and turn it into a special (404) status error.
2. Implemented the `BadRequest` error interface on the `MismatchError` service error type so the corresponding status problem matcher would catch it and turn it into a special (400) status error.
3. Errors not having API level problem matchers (e.g. errors without dedicated response encoder) returned `500 Internal server error, something went …
> fix(API): error logging and error response handling

- go.mod
- go.sum
Upgrade mapstructure library
The recent upgrade of the Cadence client library changed the default data encoder to use `json.Number` for numeric values:
https://github.com/uber-go/cadence-client/pull/988
The mapstructure version we used before (1.1.2) didn't handle this well:
```
expected type 'uint', got unconvertible type 'json.Number'
```
but the latest version supports `json.Number`.
> Upgrade mapstructure

- .github/workflows/ci.yml
Remove `set-env` from CI config
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> ci: remove deprecated set-env

- cmd/worker/eks.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_node_pool_workflow.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_node_pool_workflow_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_stack_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/list_stored_node_pools.go
- internal/cluster/distribution/eks/eksprovider/workflow/list_stored_node_pools_test.go
| Related tickets | #3185 
Added an optional `StaackID` input parameter and a `DescribeStack` call to the EKS `DeleteStackActivity` and created a `ListStoredNodePoolsActivity` to provide the stack ID for the node pool stack deletion calls.
In order to determine if a stack exists before trying to delete it, so never-existed-stacks, deleting stacks and already deleted stacks are not going to receive another `DeleteStack` request.
Manual testing is going to include an EKS cluster creation with multiple node pools, deleting the AWS CloudFormation stack of the node pool manually and then requesting a node pool delete with any …
> Fixed node pool deletion to only delete existing CF stacks

- .github/workflows/ci.yml
This PR adds a number of improvements to the Docker image build job:
- image layer caching
- skip logging into registries when not necessary
- remove unused qemu step (copy&paste error)
Caching might speed up the Docker image build (time will tell).
Removing unnecessary steps from the workflow might have the same effect.
The cache size might not fit into the [limits](https://github.com/actions/cache#cache-limits)
> Improve docker build

- cmd/worker/aws.go
- cmd/worker/main.go
- config/config.yaml.dist
- internal/cmd/config.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/select_image_and_volume_size.go
- internal/providers/pke/pkeworkflow/select_volume_size_activity.go
- internal/providers/pke/pkeworkflow/update_cluster.go
| Related tickets | resolves #3101 
Added PKE AWS default node volume size configuration to the Pipeline configuration at `distribution.pke.amazon.defaultNodeVolumeSize` and incorporated it into the PKE volume size selection logic.
To make the default PKE AWS node volume size configurable.
```yaml
defaultNodeVolumeSizeValues:
- 0/unspecified
- < AMI size
- == AMI size
- > AMI size
explicitVolumeSize:
- not set
- set
operations:
- cluster create
- cluster update
```
<details>
<summary>0 default volume size</summary>
```yaml
distribution:
pke:
amazon:
defaultNodeVolumeSize: 0 # GiB, 0/fallback: max(50, AMISize)
---
name: …
```
> feat(PKE/AWS): added default node volume size configuration

- cmd/worker/eks.go
- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_infra_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_node_pool_workflow.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_node_pool_workflow_test.go
- internal/cluster/infrastructure/aws/awsworkflow/amazon.go
- internal/cluster/infrastructure/aws/awsworkflow/delete_stack_activity.go
| Related tickets | #3151 #3242 
.
Refactor DeleteStackActivity to the infrastructure/aws/awsworkflow package to make it resuseable for #3242.
Also added AWSCommonActivityInput for future usage.
> Refactor DeleteStackActivity

- docs/developer.md
- internal/cluster/distribution/eks/image_selector.go
- internal/cluster/distribution/eks/image_selector_defaults.go
- internal/cluster/distribution/eks/image_selector_test.go
| Related tickets | fixes #3271 
Add automatic AMI selection for ARM instances in EKS clusters.
> eks: support for ARM images

- src/api/ark/backupservice/enable.go
| Related tickets | fixes #3262 
Set the name of the cluster as prefix for backups instead of `cluster-backup` which is used currently as it's more meaningful as user friendly when for ex. user has to select from a list of backups.
<!-- Additional information we should know about (eg. edge cases, steps you followed to test the implementation) (Please
> set the cluster name as backup name

- cmd/worker/eks.go
- cmd/worker/main.go
Moved `DeleteNodePoolLabelSetActivity` from `cmd/worker/eks.go` to `cmd/worker/main.go`
After recently refactoring the node pool label set deletion activity it is once again a generic activity, but it was located at a distribution specific initialization place.
> chore: relocated misplaced activity init

- internal/cluster/infrastructure/aws/awsworkflow/delete_stack_activity.go
Handled pre-creation failure non-existent CloudFormation stack properly.
| Related tickets | resolves #3280 
Fixed the handling of non-existent CloudFormation stack handling in `AWSCommon.DeleteStackActivity` by adding the corresponding validation error to the non-existent stack error handling branch on the existence check.
Because there are different errors for already deleted and never created stacks, only the former was handled before.
Unfortunately I couldn't find any predefined error code/message for this case in https://github.com/aws/aws-sdk-go.
- ~User guide and …
> fix(#3280/AWS/DeleteStack): fixed existence check

- pkg/providers/amazon/objectstore/objectstore_test.go
My short research about failing integration test runs showed that this single API call fails most of the time. This may be caused by the kind of eventual consistency of bucket creation.
No idea about other low effort solution.
> objectstore_test: retry the most flaky part

- pkg/auth/token.go
- pkg/auth/token_test.go
Fixed the JWT token storing and thus validation with the new go-jose JWT implementation.
The cluster tokens are non-expiring, but they were stored with an explicit expiration set to 0 explicit time (0001-01-01T00:00:00Z), because at one point where we converted between non-pointer to pointer expiration the address of the zero value time was taken instead of setting expiration to nil.
Example: (token saved with no expiration/zero time value)
```json
{
"token": {
"expiresAt": "0001-01-01T00:00:00Z",
"id": "c81ee9e4-e925-40b6-8034-9e8b7d0b79b8",
"name": "clusters/1/14",
"value": …
```
> fix(Token): fixed cluster token validation

- internal/ark/backups_model.go
| Related tickets | fixes #X
Backport `cluster backup: fix possible nil issue (#3304)` from master.
> cluster backup: fix possible nil issue (#3304)

- templates/eks/amazon-eks-nodepool-cf.yaml
| Related tickets | fixes #3294 
Add new param `CustomSecurityGroup` to EKS node pool CF template.
> Add custom security group to EKS node pool template (#3294)

- config/config.yaml.dist
- internal/cmd/config.go
- internal/federation/deployment.go
- internal/federation/reconcile_controller.go
- internal/helm/helmadapter/helm_service.go
- internal/helm/integration_test.go
- internal/helm/service.go
- kube-fed repository added as platform repository
- cleanup unecessary code (that added the above repository programatically)
Platform repositories are not persisted; the above approach caused problems as it added the repo to the database (and no synchronisation logic is executed for platform repositories)
> Add kube-fed to the list of platform helm repositories

- internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_node_pool_workflow.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_node_pool_workflow_test.go
Added `shouldCreateNodePoolLabelSet` input field propagation to `EKS.CreateNodePoolWorkflow`.
Missed an input field in a wrapper function in the `EKS.CreateNodePoolWorkflow` functions.
> fix(EKS/CNPWF): fixed input field propagation

- templates/eks/amazon-eks-nodepool-cf.yaml
| Related tickets | fixes #3313  
Possibility  to send a list of comma separated list of custom node security groups in CustomNodeSecurityGroupIds paramter for EKS node pool template.
> Ability to set multiple custom node security groups to EKS node pool CF template

- templates/eks/amazon-eks-nodepool-cf.yaml
Fixed the EKS node pool CloudFormation template's metadata parameter listing regarding the newly introduced security groups.
Because the parameter was renamed, but the template was not consolidated.
This doesn't affect the behavior of the template, it only affects the listing of the resulting parameters on the stack.
#3300 depends on this
- ~Related Helm …
> fix(template/EKS/NP): fixed parameter metadata

- templates/eks/amazon-eks-nodepool-cf.yaml
Renamed the EKS node pool CloudFormation template's `SecurityGroups` to `CustomNodeSecurityGroups`.
After multiple discussions with involved parties this is the preferable naming convention for now.
- ~Implementation tested (with at least one cloud provider)~ (currently this parameter is not used)
> Renamed EKS node pool CloudFormation template's SecurityGroups to CustomNodeSecurityGroups

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_eks_node_pool.go
- .gen/pipeline/pipeline/model_eks_node_pool_all_of.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request_all_of.go
- .gen/pipeline/pipeline/model_node_pool.go
- .gen/pipeline/pipeline/model_node_pool_summary.go
- .gen/pipeline/pipeline/model_update_node_pool_request.go
- apis/pipeline/pipeline.yaml
| Related tickets | fixes #3314 
Add 'securityGroups' field to EKS node pool properties (create, update)
> API: add custom node security group list to EKS nodepools (#3314)

- internal/cluster/distribution/eks/eksadapter/node_pool_manager_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/templates.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
- internal/cluster/distribution/eks/service_test.go
- templates/eks/amazon-eks-nodepool-cf.yaml
| Related tickets | resolves #3257 
Updated the EKS CloudFormation node pool template to the latest available version.
Due to the number of changes, see the change list at the additional notes.
To keep the corresponding CloudFormation template up to date with the latest official recommended one.
The changes are well separated in their dedicated commits so we can easily revert any of those if we wish to do so for any reason. The PR is advised to be reviewed by commit because the changes had been introduced iteratively and it's much easier to follow them that way then comparing the original state to the result.
Detailed …
> Updated the EKS CloudFormation node pool template to the latest official available state

- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/node_pool.go
- internal/cluster/distribution/eks/service_test.go
| Related tickets | resolves #3329 
Propagated user provided custom node security groups from the API request to the node pool CloudFormation stack creation in `EKS.NodePoolAPI.CreateNodePool`.
To add a feature to the `EKS.NodePoolAPI.CreateNodePool` endpoint of user specified node pool node security groups.
> Added user security group propagation to EKS.NodePoolAPI.CreateNodePool

- internal/cluster/distribution/eks/ekscluster/eks.go
- internal/cluster/distribution/eks/eksprovider/driver/cluster_creator.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra_test.go
| Related tickets | resolves #3330 
Propagated user provided custom node security groups from the API request to the node pool CloudFormation stack creation in `EKS.ClusterAPI.CreateCluster`.
To add a feature to the `EKS.ClusterAPI.CreateCluster` endpoint of user specified node pool node security groups.
Depends on #3332 
> Added user security group propagation to EKS.ClusterAPI.CreateCluster

- internal/cluster/distribution/eks/eksprovider/driver/cluster_updater.go
- internal/cluster/distribution/eks/eksprovider/driver/cluster_updater_test.go
- src/cluster/eks_update_cluster.go
Refactored EKS `ClusterAPI.UpdateCluster` to use `CreateNodePoolWorkflow` for new node pools.
So all the `NodePoolAPI.CreateNodePool`,`ClusterAPI.CreateCluster`, `ClusterAPI.UpdateCluster` endpoint implementations use the "same" logic for creating new node pools (couple flags might differ due to the nature of cluster status handling and higher level operations, but it's still hell of a lot better and deduplicates a lot of code).
This was the last milestone of the "EKS NodePoolAPI.CreateNodePool refactor" task.
Now only the `UpdateNodePool` implementation remains outdated/duplicated in `EKS …
> Refactored EKS ClusterAPI.UpdateCluster to use CreateNodePoolWorkflow for new node pools

- internal/cluster/distribution/eks/eksprovider/driver/cluster_updater.go
- internal/cluster/distribution/eks/eksprovider/driver/cluster_updater_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- src/cluster/eks_update_cluster.go
Propagated user provided custom node security groups from the API request to the node pool CloudFormation stack creation/modification in `EKS.ClusterAPI.UpdateCluster`.
To add a feature to the `EKS.ClusterAPI.UpdateCluster` endpoint of user specified node pool node security groups.
Depends on #3326 , #3332, #3333 (technically these are convenience dependencies to avoid double work, especially in case changes are requested, but we are not in a rush, so it's best to do this orderly).
- ~Related …
> Added user security group propagation to EKS.ClusterAPI.UpdateCluster

- cmd/pipeline/config.go
- cmd/pipeline/main.go
- cmd/worker/main.go
Bail out in case the cadence client cannot be created, otherwise execution will fail with a nil pointer dereference.
Also add default cadence configuration for the pipeline process, otherwise only the worker will be able to create the `pipeline` domain if `createNonexistentDomain` is enabled. This behaviour, that the pipeline process can also create the domain if it doesn't exist was introduced in https://github.com/banzaicloud/pipeline/pull/3319
> Cadence client error check and default config for the pipeline process

- internal/cmd/config.go
- src/cluster/hooks.go
Use latest hpa operator chart with updated metrics server dependency.
> update hpa operator version

- templates/eks/amazon-eks-nodepool-cf.yaml
Fixed EKS node pool CloudFormation template `KeyName` type.
To avoid AWS type to bypass [implicit validation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) for Pipeline-allowed empty value in certain environments.
> Fixed EKS node pool CloudFormation template KeyName type

- templates/eks/amazon-eks-nodepool-cf.yaml
Stylistically fixed EKS node pool CloudFormation template parameter order.
To restore parameter ordering.
> Stylistically fixed EKS node pool CloudFormation template parameter order

- .plzconfig.ci
Increment build timeout to avoid the build fail intermittently. This is only a temporary workaround to let the cache populated and make subsequent builds more efficient.
> Increase please build timeout in CI

- internal/cluster/distribution/eks/eksadapter/node_pool_manager_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_node_pool_workflow_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/get_cf_stack_activity_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/templates.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
- internal/cluster/distribution/eks/service.go
- internal/cluster/distribution/eks/service_test.go
- pkg/sdk/providers/amazon/cloudformation/cloudformation.go
- pkg/sdk/providers/amazon/cloudformation/cloudformation_test.go
- pkg/sdk/semver/compared.go
- pkg/sdk/semver/compared_test.go
- pkg/sdk/semver/error.go
- pkg/sdk/semver/error_test.go
- pkg/sdk/semver/version.go
- pkg/sdk/semver/version_test.go
- pkg/sdk/semver/versions.go
- pkg/sdk/semver/versions_test.go
- templates/eks/amazon-eks-nodepool-cf.yaml
Fixed a bug which caused the current template version not being retrieved for the node pool stacks which are updated when all node pool version attributes were changed during the update due to a left in condition for old value retrieval.
Refactored the EKS node pool CloudFormation template version handling.
1. Simplified `TemplateVersion` handling and make it easier to use/update.
Single point to track the latest node pool version as the default value of the `TemplateVersion` parameter in the template itself, keeping the update requirement local when the template changes, so no manual setting/update …
> Fixed an edge case bug + Refactored the EKS node pool CloudFormation template version handling

- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- src/cluster/eks_update_cluster.go
Fixed EKS UpdateCluster's node pool version.
When SecurityGroup was added to EKS UpdateCluster, it was left out of the node pool version calculation.
This PR was built on top of #3357 in order to not introduce the same edge case bug here.
> Fixed EKS UpdateCluster to include SecurityGroups in node pool version calculation

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_enable_ark_request.go
- apis/pipeline/pipeline.yaml
- internal/ark/api/deployments.go
- internal/ark/api/posthook.go
- internal/ark/config.go
- internal/ark/deployments_svc.go
- internal/ark/posthook/posthook.go
- src/api/ark/backupservice/enable.go
| Related tickets | fixes #3362 
Add serviceAccountRoleARN field to Enable backup API call.
When enabling Velero backups, the user should have the options to pass a service account role ARN. Pipeline will annotate Velero Service Account with this value, which will be a third options beside using cluster secret deployment or NodeInstancreProfile.
> Velero API: add option to pass service account role ARN when enabling backups

- lib/integrated-service-sdk/Makefile
- lib/integrated-service-sdk/config/crd/bases/integrated-service.banzaicloud.io_serviceinstances.yaml
Disables the `preserveUnknownFields` feature for the CRD.
If preserveUnknownFields is enabled then unknown fields of the CRD are not validated by clients which can lead to hard to debug issues.
> Do not preserve unknown fields of the ServiceInstance CRD

- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- templates/eks/amazon-eks-nodepool-cf.yaml
| Related tickets | fixes #3352 
Adds an additional parameter to EKS node pool CF template `UseIntanceStorage` which works as follows:
- UseIntanceStorage = true and number of available NVMe disks on instance type (for ex. i3.large) > 0, user data script will try to list available NVMe disks, format and mount on /media/local path. This path will be set as root dir for kubelet. In case of multiple disks they will be mounted as a RAID device.
- UseIntanceStorage = true and there are no available NVMe disks on instance type (for ex. c3.large) or UseIntanceStorage = false, no root dir is set for kubelet, bootstrap should work …
> Add UseIntanceStorage param to EKS node pool CF template

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/integratedservices/functional_suite_test.go
- internal/integratedservices/integratedserviceadapter/serviceconversion.go
- internal/integratedservices/integratedserviceadapter/serviceconversion_test.go
- internal/integratedservices/service_v2.go
- internal/integratedservices/services/dns/outputresolver.go
Adds a new abstraction `OutputResolver` to the `ServiceConversion` component to allow filling the service output field as appropriate with values based on the current `ServiceInstance` for v2 services.
The current form of service output resolution is not suitable for v2 integrated services.
> Add output resolvers to handle v2 service output

- .idea/runConfigurations/Debug_Worker_IS_test.xml
- .idea/runConfigurations/Debug_Worker_IS_test_V2.xml
- cmd/pipeline/main.go
- cmd/worker/clusterfeature.go
- cmd/worker/main.go
- go.mod
- internal/integratedservices/functional_suite_test.go
- internal/integratedservices/functional_test.go
- internal/integratedservices/integratedserviceadapter/cadence_integrated_service_operation_dispatcher.go
- internal/integratedservices/integratedserviceadapter/cadence_integrated_service_operation_dispatcherV2.go
- internal/integratedservices/integratedserviceadapter/reconciler.go
- internal/integratedservices/integratedserviceadapter/reconciler_test.go
- internal/integratedservices/integratedserviceadapter/workflow/common.go
- internal/integratedservices/integratedserviceadapter/workflow/integrated_service_job_workflow.go
- internal/integratedservices/interface.go
- internal/integratedservices/registry.go
- internal/integratedservices/servicerouter.go
- internal/integratedservices/servicerouter_test.go
Separation of workflows for the new version of integrated services
Legacy and new implementation should be available during the transition to the new version, this separation facilitates this approach.
> Separate integrated service workflows for the v1 (legacy) and v2 implementations

- internal/cmd/config.go
| Related tickets | related: https://github.com/banzaicloud/anchore-image-validator/pull/63
The updated chart is using `anchore-image-validator` image version `0.4.5`, which was built on to of alpine:3.12.3
Some vulnerabilities were found in the previous version of the alpine image.
> chore: update anchore-image-validator chart

- config/config.yaml.dist
- internal/cmd/config.go
| Related tickets | related: banzaicloud/bank-vaults#1231, related: banzaicloud/bank-vaults#1227
Update `vault-secrets-webhook` chart version
The base image was updated in the webhook image tag 1.10.1
> chore: update vault-secrets-webhook chart version

- config/config.yaml.dist
- internal/cmd/config.go
- internal/cmd/config_test.go
- internal/federation/reconcile_ext_dns_test.go
- internal/helm/service_test.go
Added ARM support to external DNS integrated service.
We want to support ARM only or taintless mixed managed clusters.
Major version change release notes:
External DNS:
[0.6.0](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.6.0)
[0.7.0](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.7.0)
Chart:
[4.0.0](https://github.com/bitnami/charts/pull/4284)
[3.0.0](https://github.com/bitnami/charts/pull/2589)
Nothing seems to be breaking Pipeline functionality or user experience (renamed parameters are not used).
- ~User guide …
> Added ARM support to external DNS integrated service

- config/config.yaml.dist
- internal/cmd/config.go
- internal/helm/integration_test.go
- internal/helm/service_test.go
- internal/integratedservices/services/monitoring/operator.go
Added partial ARM support for Monitoring integrated service
We would like to support pure ARM and mixed managed clusters in the future, this is a step towards that direction.
The reason behind partial support is that we decided to wait for the kube-state-metrics 2.0.0 verion (for ARM support) and official chart.
Prometheus alertmanager:
[v0.20.0](https://github.com/prometheus/alertmanager/releases/tag/v0.20.0)
[v0.21.0](https://github.com/prometheus/alertmanager/releases/tag/v0.21.0)
Prometheus node exporter:
[v1.0.0](https://github.com/prometheus/node_exporter/releases/tag/v1.0.0)
Prometheus …
> Added partial ARM support for Monitoring integrated service

- internal/integratedservices/registry.go
- internal/integratedservices/servicerouter.go
- internal/integratedservices/servicerouter_test.go
Integrated service activation is only executed once
Activation returns early if it has already been called (modification is possible through the update operation)
> Check Integrated services before activation; activation only performed once

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_eks_node_pool.go
- .gen/pipeline/pipeline/model_eks_node_pool_all_of.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request_all_of.go
- .gen/pipeline/pipeline/model_node_pool.go
- .gen/pipeline/pipeline/model_node_pool_summary.go
- .gen/pipeline/pipeline/model_update_node_pool_request.go
- apis/pipeline/pipeline.yaml
- internal/cluster/distribution/eks/eksadapter/node_pool_manager.go
- internal/cluster/distribution/eks/ekscluster/eks.go
- internal/cluster/distribution/eks/eksprovider/driver/cluster_creator.go
- internal/cluster/distribution/eks/eksprovider/driver/cluster_updater.go
- internal/cluster/distribution/eks/eksprovider/workflow/activity_calculate_node_pool_version.go
- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
- internal/cluster/distribution/eks/node_pool.go
- internal/cluster/distribution/eks/service.go
- src/cluster/eks_update_cluster.go
| Related tickets | fixes #3381 
Add `useInstanceStore` property to EKS node pool in create / update cluster, create / update node pool API.
Setting `useInstanceStore: true` for a node pool means in case there's available storage for a given instance type that will used by Kubelet and EmptyDir volumes will be provisioned on these storages.
Tested scenarios:
- create cluster with old CF template (Pipeline version: 0.64.0) then upgrade node pool to with image, don't set useInstanceStore
- update node pool, set useInstanceStore = true for a c5.large image. CF param UseInstanceStore will be set to true however there will be …
> Instance storage api

- .gen/anchore/api/openapi.yaml
- .gen/anchore/api_registries.go
- Makefile
- apis/anchore/swagger.yaml
- internal/integratedservices/services/securityscan/operator.go
- internal/integratedservices/services/securityscan/spec.go
- internal/security/anchore_client.go
| API breaks?     |yes
| Related tickets | related: https://github.com/banzaicloud/banzai-cli/pull/338
In the case of `securityscan` integrated service, multiple image registries can be set.
- The swagger file is fixed within the `pipeline` repo and downloading the upstream one is disabled, until the [pull-request](https://github.com/anchore/anchore-engine/pull/846) in the `anchore-engine` will merge.
- Using DeleteRegistry and AddRegistry instead of UpdateRegistry as workaround because of the [anchore-engine issue](https://github.com/anchore/anchore-engine/issues/847).
> feat(securityscan): add multiple registries

- config/config.yaml.dist
- internal/cmd/config.go
Updating node pool labelset operator chart.
To use the latest, most secure alpine base image with the operator.
Notable [changes](https://github.com/banzaicloud/nodepool-labels-operator/compare/v0.0.5...v0.1.1):
1. Alpine base image version update (3.7.x->3.13.0)
2. Builder Golang version update (1.11.y->1.13.z)
3. Dropping pinned builder image tool versions.
> Updated node pool labelset operator chart to version 0.1.1

- internal/helm/envresolver.go
- internal/integratedservices/functional_suite_test.go
- internal/integratedservices/functional_test.go
| Related tickets | fixes #3368
Persisted Helm repositories added by users are reconciled during helm operations
> Reconcile user-added helm repositories during helm environment resolution on each helm operation

- internal/ark/config.go
- internal/ark/config_test.go
- internal/ark/deployments_svc.go
| Related tickets | fixes #3411 
Set node affinity for Velero operator pod to schedule only on amd64 nodes.
In order to be able to use mixed architecture clusters while only single architecture Velero and Velero-pluging-for-aws images are available, we want to add a node selector/affinity to Velero operator pod which forces the containers onto amd64 nodes.
> Add amd64 architecture node selector to velero (#3411)

- config/config.yaml.dist
- internal/cmd/config.go
- src/cluster/autoscale.go
| Related tickets | #3410 
Extension of  src/cluster/autoscale.go.autoscalingInfo with a nodeSelector map which  populated accordingly in the corresponding createAutoscalingFor...() functions based on k8s version (package local getK8sVersion() is used to obtain a structured k8s version).
From the ticket:
"In order to be able to use mixed architecture clusters while using k8s version < 1.20, we want to add a node selector to cluster-autoscaler which forces the container onto amd64 nodes on these versions. (ARM container support is available from CA 1.20, supporting k8s 1.20)."
> Add amd64 architecture node selector to cluster autoscaler based on k8s version

- internal/cmd/config.go
- internal/cmd/config_test.go
- internal/integratedservices/services/dns/config.go
- internal/integratedservices/services/dns/operator.go
Fixes the external-dns chart configuration to allow specifying a registry independently from the repository.
The current config with the latest chart renders an invalid configuration where the registry is not properly recognized and added as part of the repo with the default registry docker.io.
> Update configuration for external dns

- internal/cmd/config.go
Update instanceTerminationHandler chart version
To use latest ith image containing: https://github.com/banzaicloud/instance-termination-handler/pull/29
> update instanceTerminationHandler chart version

- internal/integratedservices/integratedserviceadapter/serviceconversion.go
- internal/integratedservices/interface.go
- internal/integratedservices/service_v2.go
| Related tickets | fixes #3427
Only Integrated service instances that are managed by [pipeline are allowed to be updated and deactivated
In a cluster there might exist integrated service custom resources that are not added and managed by pipline.
> chore(is-v2):  only allow update and deactivation of integrated services managed by pipeline

- .circleci/config.yml
- charts/pipeline-logs/.helmignore
- charts/pipeline-logs/Chart.yaml
- charts/pipeline-logs/templates/_helpers.tpl
- charts/pipeline-logs/templates/fileoutput.yaml
- charts/pipeline-logs/templates/flows.yaml
- charts/pipeline-logs/templates/logging.yaml
- charts/pipeline-logs/values.yaml
This PR contains a chart that can be used as the Flow configuration interpreted by the [Logging operator](https://github.com/banzaicloud/logging-operator) (from version v3.6.0).
It contains all the Pipeline components' log sources identified by label selectors when installed using the [official Pipeline installer](https://banzaicloud.com/docs/pipeline/quickstart/install-pipeline/prod/)
Parse configuration is added where appropriate.
To make logging configuration simpler for Pipeline components.
This chart is supposed to be used in an environment where the base logging system and the outputs are already configured …
> Helm chart with component level logging flow configurations

- docker-compose.yml
Upgraded local Cadence server to 0.14.1.
To converge towards supporting the latest Cadence version.
Tested using local Pipeline control plane, workflows and activities tested: [EKS] cluster create (node pool create), node pool update, cluster delete (node pool delete).
> chore(Cadence): upgraded local server to 0.14.1

- .gen/pipeline/api/openapi.yaml
- apis/pipeline/pipeline.yaml
- internal/ark/backups_repository.go
- internal/ark/backups_svc.go
- internal/ark/sync/backups_sync_svc.go
- internal/ark/sync/buckets_sync_svc.go
- src/api/ark/backups/list.go
| Related tickets | fixes #3449 
- fix OpenAPI  path for backup / restore sync per cluster
- BackupsSyncService.SyncBackupsForCluster: delete backups not found on cluster. 
- sync backups from bucket only for inactive deployments (backup service disabled or cluster already  deleted)
- add ListForACluster to BackupService to optimise listing of buckets for a cluster
Syncing backups both from cluster (Velero Backup CRD) and from objectstorage might cause different problems in case there are discrepancies between them, like backups hanging in InProgress or Deleting mode, when they are not yet created or already deleted …
> Velero sync api fix

- src/api/ark/backupservice/enable.go
| Related tickets | fixes #3451 
Enable backup also creates the first backup, however backupOptions specified in Enable request are not propagated to create backup call.
> Backup enable does not propagate backupOptions to create bucket call

- internal/cluster/distribution/eks/ekscluster/eks.go
- internal/cluster/distribution/eks/image_selector_defaults.go
| Related tickets | fixes #3438
- Update EKS optimized AMIs
- add K8s version 1.19 support
Cloudinfo PR: https://github.com/banzaicloud/cloudinfo/pull/398
> Eks: K8s 1.19 support

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_enable_ark_request.go
- apis/pipeline/pipeline.yaml
- internal/ark/api/deployments.go
- internal/ark/config.go
- internal/ark/deployments_svc.go
- internal/cluster/clustersetup/velero/restore_backup_activity.go
- pkg/cluster/base.go
- src/api/ark/backupservice/enable.go
| Related tickets | fixes #3456 
- add useProviderSecret option to enable backup request
- if useProviderSecret = true configure the same provider secret used for bucket access by setting the same profile = bucket in volumeSnapshot config as in backupLocation config.
When enabling backup we have different options like useClusterSecret, or specify service account role to use for taking
volume snapshots. There should be a third option to configure the same secret used for bucket access.
> Velero provider secret

- .circleci/config.yml
Fix failing migrapg to use pinned versions.
> migrapg: install fixed versions of migrapg packages

- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- templates/eks/amazon-eks-iam-cf.yaml
- templates/eks/amazon-eks-nodepool-cf.yaml
Propagated EKS NP CF stack tags to volumes.
Customer feature request.
Note: manually applying stack tags onto root EBS volumes, because automatic tag propagation for Amazon EBS volumes created from block device mappings is not supported as of 2021-03-11, [source](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html)
> All stack-level tags, including automatically created tags, are propagated to resources that CloudFormation supports. Currently, tags aren't propagated to Amazon EBS volumes that are created from block device mappings.
Requires an additional …
> Propagated EKS NP CF stack tags to volumes

- internal/ark/config.go
- internal/cmd/config.go
| Related tickets | fixes #3496 
- upgrade Velero image to 1.6.0
- upgrade Velero plugin images to 1.2.0
- remove amd64 node restriction affinity for Velero pod as these images already have multi arch support.
To be able to run Velero pod on arm nodes as well.
Azure and GCP plugins have no multi arch support yet, so in case someone wants to store backups on Azure or GCP in a cluster contaning nodes other than amd64 he has to add the following affinity to Velero deployment:
```
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: ubernetes.io/arch
operator: …
```
> Upgrade Velero images

- internal/cluster/clustersetup/velero/BUILD.plz
- internal/cluster/clustersetup/velero/restore_backup_activity.go
- internal/cluster/clustersetup/workflow.go
| Related tickets | fixes #3495 
Throw a non retriable error from RestoreBackupActivity when restore status is 'PartiallyFailed' or 'Failed'.  
If restore has a status of 'Failed' or 'PartiallyFailed' there no reason to retry RestoreBackupActivity 30 times since it fail constantly.
> set restore failures as non retriable errors

- .github/workflows/ci.yml
Added CI integrity checks for Go modules, Please Go dependencies and generated files.
Time and time again we run into issues where these manual steps are not done and occasionally the occurring error messages are not clear about the origin of the issue caused by this.
Thought this could be made easier if we checked them before doing anything else in the CI as they are build requirements.
A further step would be a checked in Git commit/push hook, but a lot of people despise mandatory client side Git hooks, so I don't want to push it further for now.
I was itching to do this for a while and I just want …
> Added CI integrity checks

- internal/cluster/distribution/pke/pkeaws/pkeaws.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
| Related tickets | related: https://github.com/banzaicloud/pke/pull/142, https://github.com/banzaicloud/pke-image/pull/25
Update PKE version to 0.8.0 (supports k8s 1.20, 1.21)
- PKE has been released
- AWS pre-built images have been created
> update pke version

- Makefile
- docker.images.list
| Related tickets | fixes #3505
Add scan-docker-images target to Makefile which runs a security scan on a list of container images deployed by Pipeline.
> add scan-docker-images target to Makefile

- .github/workflows/ci.yml
Fixed CI integrity check.
Missed the multiple module monorepository setup, fumbled on the printf formatting with backticks and there was a missed backslash in the original command at a line break, but as run can handle multiline commands it was possible to convert it to a more easily readable and writable state.
Tested for both `go mod tidy` and `please tidy` failure, looks good now.
- ~User guide and …
> Fixed CI integrity check

- Dockerfile
- Dockerfile.alpine
- Dockerfile.debug
- Dockerfile.local
- docs/developer.md
- internal/helm/helmadapter/helm3_env_service.go
| Related tickets | fixes #3489 
Add helm-s3 plugin to Pipeline image and set HELM_PLUGINS environment variable to point to that location.
Fix Helm3EnvService.getDetailedCharts to support different download protocols.
To be able to add s3 helm chart repositories to Pipeline and install helm charts from such repositories.
> install helm-s3 plugin

- Makefile
Fixed etcd, kube-apiserver binary sources.
The integration test was broken, because the old binary URLs didn't work anymore.
> Fixed etcd, kube-apiserver binary sources

- internal/cluster/distribution/eks/ekscluster/eks.go
| Related tickets | fixes #3523 
Set EKS min version to 1.16 & max version to 1.20.
> EKS: update version restrictions

- Makefile
- docker.images.list
Updated image scan images list:
1. Added GHCR auth.
2. Added traefik (core image).
3. Added vault-secrets-webhook (core image).
4. Updated IS operator version to what Pipeline uses.
5. Updated NPLS version to what Pipeline uses.
1. Required by some images.
2. Traefik image is currently used by default in managed clusters.
3. Vault-secrets-webhook is a commonly used image (unless explicitly configured not to).
4. To make sure the correct version tag is analyzed.
5. To make sure the correct version tag is analyzed.
- ~Code meets the [Developer …
> Updated image scan images list

- templates/eks/amazon-eks-nodepool-cf.yaml
Updated EKS node pool CloudFormation template.
1. Added last used upstream reference link.
2. Fixed ordering of upstream parameters to upstream order.
3. Fixed node instance type ordering to upstream order (now alphabetical, previously it was custom based on instance family and size).
4. **Updated the template default node instance type t2.medium->t3.medium. This value is currently not used, because instance type is a required argument of node pool creation configuration.**
5. Added new instance types according to upstream.
6. Fixed formatting (including comment explanations) to upstream.
To be up to …
> Updated EKS node pool CloudFormation template

- internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go
| Related tickets | fixes #3528 
Update EKS cluster create workflow to save K8s config right after EKSCluster create has completed.
K8s config is available once EKSCluster has been created successfully, so we can download and save right away before starting any other additional activity to make sure we can access the cluster even if latest some bootstrap activity may fail.
> Save K8s config right after EKSCluster create has completed

- cmd/worker/eks.go
- config/config.yaml.dist
- internal/cluster/distribution/eks/eksprovider/workflow/bootstrap_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra_test.go
- internal/cluster/distribution/eks/eksworkflow/BUILD.plz
- internal/cluster/distribution/eks/eksworkflow/activity_update_addon.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_addon_test.go
- internal/cluster/distribution/eks/eksworkflow/activity_wait_update_addon.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_cluster.go
- internal/cmd/config.go
| Related tickets | fixes #3529 
- EKS bootstrap activity: create `coredns` addon  if configuration property `distribution.eks.enableAddons` is set true and kubernetes version is >= 1.18.
- add eks-update-addon activity to update addon to the latest available version
- add eks-wait-update-addon acitvity to wait for update to finish
- cluster update: upgrade coredns to the latest available version in case it's already present on cluster
Add possibility of creating and updating core-dns as an EKS addon.
To manage EKS addons the following privileges has to added to minimum privileges required to provision an EKS cluster with …
> Create and update core-dns as an EKS addon

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_node_item_status_images.go
- apis/pipeline/pipeline.yaml
Changed the node's container image's `sizeBytes` property in the API spec from `int32` to `int64` and regenerated the corresponding model in order to handle node images over 2GB size returned from `ListNodes`.
A customer tried to use a 8.3 GB container image and the node listing API returns a parsing error because the byte size cannot fit into the Golang `int32` type during the internal parsing.
Related to https://github.com/banzaicloud/banzai-cli/pull/348.
- ~User …
> Handle container images over 2GB size returned from `ListNodes`

- cmd/worker/eks.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_addon.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_cluster.go
Fixed the EKS addons, UpdateAddon not existing addon handling, UpdateCluster respecting addon feature flag & k8s version.
These 2 issues together cause a cluster update to fail on clusters with no addons.
The UpdateAddon not existing addon case handling fix would probably be enough to handle the <1.18 and no addon cluster cases, but we shouldn't even try to describe the addons in these cases, so I introduced the feature flag and k8s version checking to the UpdateCluster's relevant parts to prevent unnecessary addon operations (as it should be IMO when it is feature flagged).
Also the feature flag …
> Fixed the EKS addons, UpdateAddon not existing addon handling, UpdateCluster respecting addon feature flag & k8s version.

- cmd/worker/eks.go
- internal/cluster/distribution/eks/eksprovider/workflow/bootstrap_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/bootstrap_workflow.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_addon_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra_test.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_addon.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_cluster.go
| Related tickets | fixes #3539 
- create new activity `eks-create-addon` to submit a createAddon request to EKS and waits until addon status is active
- create new workflow `eks-bootstrap-flow` which starts  `eks-create-addon` activities in parallel (to install coredns, kube-proxy and vpc-cni addons) and after all of these are finished lauches `eks-bootstrap` activity. Addon install are started only in case of k8s version >= 1.18 and `distribution.eks.enableAddons` is set to true in Pipeline config.
- in `create-infra` workflow launch `eks-bootstrap-flow` instead of `eks-bootstrap` activity.
To be able to create addons …
> Add vpc-cni and kube-proxy addons in cluster create flow

- .plzconfig
- BUILD.plz
- Makefile
- Makefile.plz
1. Fixed the plz config, Makefile, build target.
2. Updated Makefile's corresponding targets.
1. To use working up to date URLs to fix the plz build command on new machines.
2. To improve the binary acquisition process a bit.
Without these, `plz build` failed with an error on those targets due to the old download URLs responding 404s.
Tested on my new machine and they worked like a charm.
- ~User guide and …
> Fixed Please, Make build test kube-apiserver, etcd binary acquisition

- internal/cmd/helm.go
- internal/cmd/helm_test.go
- internal/helm/chart_config.go
1. Fixed the `orgs/helm/cluster-charts` endpoint to not use the services' `enabled` flag, because it is unreliable, not all services - which can be enabled on the managed cluster - set it to true, so we should list all charts regardless of their enabled flags.
2. Added functionality to list the non-chart values of the configuration as well (values which are not part of the chart name, version, repository and values fields, but are extra fields in the same structure).
The fix was required because the listing was incomplete (velero and traefik were missing).
The non-chart value addition is to give the …
> Fixed/improved cluster-charts endpoint, ignored enabled flag, added non-chart values

- internal/cmd/helm.go
- internal/cmd/helm_test.go
- internal/helm/chart_config.go
1. Fixed the `orgs/helm/cluster-charts` endpoint to not use the services' `enabled` flag, because it is unreliable, not all services - which can be enabled on the managed cluster - set it to true, so we should list all charts regardless of their enabled flags.
2. Added functionality to list the non-chart values of the configuration as well (values which are not part of the chart name, version, repository and values fields, but are extra fields in the same structure).
The fix was required because the listing was incomplete (velero and traefik were missing).
The non-chart value addition is to give the …
> [Backport to 0.76] Fixed/improved cluster-charts endpoint, ignored enabled flag, added non-chart values

- internal/cmd/helm.go
- internal/cmd/helm_test.go
- internal/helm/chart_config.go
1. Fixed the `orgs/helm/cluster-charts` endpoint to not use the services' `enabled` flag, because it is unreliable, not all services - which can be enabled on the managed cluster - set it to true, so we should list all charts regardless of their enabled flags.
2. Added functionality to list the non-chart values of the configuration as well (values which are not part of the chart name, version, repository and values fields, but are extra fields in the same structure).
The fix was required because the listing was incomplete (velero and traefik were missing).
The non-chart value addition is to give the …
> [Backport to 0.77] Fixed/improved cluster-charts endpoint, ignored enabled flag, added non-chart values

- internal/cluster/distribution/eks/eksprovider/workflow/bootstrap_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_addon_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_eks_control_plane_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_control_plane_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_orphan_nic_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/upload_ssh_key_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/validate_iam_role.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_cluster.go
Auto-fixed Go structs by linter/formatter.
I ran into this for 20 times at least already, always reverted my auto-changes.
See no reason why not to commit the auto-fixed format.
> Auto-fixed Go structs by linter/formatter

- internal/cmd/config.go
| Related tickets | fixes #3573 
Update nodepoolLabelOperator and security scan webhook helm chart version to their latest version update to support deprecated Kubernetes API changes. (https://github.com/banzaicloud/anchore-image-validator/pull/96, https://github.com/banzaicloud/nodepool-labels-operator/pull/24)
> Update dependent charts to support k8s version 1.22

- BUILD.plz
Amending the `start` command (which is a dependency of the `up` command) in BUILD.plz with the creation of a `postgres` directory.
Running `plz up` resulted in an error complaining about the lack of this directory:
``` shell
$ plz up
[+] Running 11/12
⠿ Network pipeline_default                 Created                                                                                                                                                                                                                                 0.1s
⠿ Container pipeline_ui_1                  Created …
```
> fix: create postgres directory during plz up

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_amazon_auto_scaling_group.go
- .gen/pipeline/pipeline/model_create_node_pool_request.go
- .gen/pipeline/pipeline/model_eks_node_pool.go
- .gen/pipeline/pipeline/model_eks_node_pool_all_of.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request_all_of.go
- .gen/pipeline/pipeline/model_node_pool.go
- .gen/pipeline/pipeline/model_node_pool_summary.go
- .gen/pipeline/pipeline/model_pke_aws_update_node_pool_request.go
- .gen/pipeline/pipeline/model_pke_aws_update_node_pool_request_all_of.go
- .gen/pipeline/pipeline/model_update_node_pool_request.go
- apis/pipeline/pipeline.yaml
- charts/pipeline/values.yaml
- config/config.yaml.dist
- internal/cluster/distribution/eks/eksprovider/workflow/select_volume_size_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/select_volume_size_activity_test.go
- templates/pke/master.cf.yaml
- templates/pke/masters.cf.yaml
- templates/pke/worker.cf.yaml
GB unit is used throughout the code base for description, while the AWS EC2 instance EBS VolumeSize definition states the unit is GiB instead.
| Related issues | https://github.com/banzaicloud/pipeline/issues/3162
Consolidate EBS volume size measurement units to GiB
GB unit is used throughout the code base for description, while the AWS EC2 instance EBS VolumeSize definition states the unit is GiB instead.
The values are transferred transparently through integer holders so this does not have an impact on code execution, it is merely for clarifying the documentation of the corresponding variables and meeting the end user …
> Consolidate EBS volume size units to GiB

- internal/cluster/distribution/eks/ekscluster/eks.go
- pkg/common/common.go
| Related issues | fixes https://github.com/banzaicloud/pipeline/issues/2622
Adding validation for node pool names (only accept lowercase characters and numbers) for clusters created on AWS.
The `eks-create-asg` Cadence workflow errors if there are special characters because the node pool name gets attached to the stack name; also the `configure-nodepool-labels` workflow errors if there are uppercase characters in the nood pool name resulting in unsuccessful cluster creation, so it is useful if a validator catches these cases even before the cluster creation begins.
Example config.yaml:
```
{
"cloud": "amazon", …
```
> feat: add node pool name validation

- internal/cluster/distribution/eks/ekscluster/nodepools/BUILD.plz
- internal/cluster/distribution/eks/ekscluster/nodepools/wait_for_asg.go
- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- pkg/providers/amazon/autoscaling/autoscaling.go
- pkg/providers/amazon/autoscaling/errors.go
- pkg/providers/amazon/autoscaling/manager.go
| Related issues | https://github.com/banzaicloud/pipeline/issues/1684
Add meaningful worker log message when the AWS autoscaling group creation fails during cluster creation and node pool update.
- ASGs can be determined either by launch configuration or launch template. If the former is not found, handle the existence of the latter before returning a "could not find launch configuration for ASG" error message.
- Include info (status, cause, description) of the last ASG activity in the error response when the ASG creation times out.
When instances in the ASG cannot be created, e.g. because of low spot price in the …
> Fix logging asg failures

- docker-compose.yml
Updated local env Cadence to "chart 0.21.3". (server 0.21.3, web 3.28.4)
Converging towards latest supported version.
> Updated local env Cadence to "chart 0.21.3"

- docker-compose.yml
Updated local env Cadence to "chart 0.22.1" (server 0.22.1, web 3.28.7).
Converging towards latest supported version.
> Updated Cadence env to chart 0.22.1

- .github/workflows/is-test-v2.yml
- .github/workflows/is-test.yml
- Makefile
- internal/integratedservices/testconfig/docker-compose.yml
- Fixed `hashFiles` function in is-test workflows.
- Updated versions of services in test environment to be in sync with what is being used in the dev env.
- Kubernetes version 1.21.1 has been specified in the Makefile to be used by kind when creating a cluster to run tests against.
In a recent change hashfiles function throws an error instead of failing silently causing these is-test workflows to fail.
Also the latest Ubuntu images that are used in the Github actions use the latest Kind version which starts kubernetes v1.23.4 version clusters by default, causing the integrated services v2 test to …
> Fix integrated service tests

- internal/cluster/service.go
Made force delete work on clusters already in deleting status.
If a cluster stuck in deleting status according to the database (even though its resources were terminated), there was no way to make it disappear from the client side.
Tested locally. If a force delete is called on a cluster with a running deletion workflow still unfinished, the second workflow failed but the resources were terminated and the database was updated successfully (tested with PKE on AWS).
- ~Related Helm chart(s) …
> Force delete on cluster in deleting status

- docker-compose.yml
Added platform spec to mysql service in local docker-compose.yaml.
So it would work on ARM devices as well.
> Added platform spec to mysql service in local docker-compose.yaml

- Makefile
- config/config.yaml.dist
- internal/cmd/config.go
- internal/cmd/config_test.go
Updated bitnami/external-dns chart 4.5.0->6.5.1.
The the external-dns chart 4.5.0 version we used (for the DNS integrated service) were pulled down from the bitnami chart repository.
Successful activation tested locally.
> Updated bitnami/external-dns chart 4.5.0->6.5.1

- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- src/cluster/eks.go
Updated client.authentication.k8s.io version v1alpha1 -> v1beta1 in the generated kubeconfig (e.g. on calling `banzai cluster shell` CLI command).
To be compatible with newer kubernetes and kubectl versions.
> Updated client.authentication.k8s.io version

- src/cluster/eks.go
Updated EKS kubeconfig auth apiversion `client.authentication.k8s.io/v1alpha1` -> `client.authentication.k8s.io/v1beta1`, which is returned e.g. as a result of the banzai cli command `banzai cluster shell`.
In kubernetes and kubectl version 1.24 the `client.authentication.k8s.io/v1alpha1` apiversion has been deprecated.
Tested locally. Tested also with kubectl version 1.22 and found no issues either.
> Updated EKS kubeconfig auth apiversion

- src/cluster/eks.go
Reverts banzaicloud/pipeline#3623
It did not deliver the expected behavior on Pipeline instances deployed on AWS EKS.
> Revert "Updated EKS kubeconfig auth apiversion"

- internal/secret/restricted/store_test.go
refactor the TestBlockingTags
Initially, this test was found to be faulty because the subsequent code was unreachable because of `t.FailNow()` in [internal/secret/restricted/store_test.go](https://github.com/banzaicloud/pipeline/pull/3627/files/5c370cf8013765d9e0f195925611e5e932ab71cd#diff-1146d372385f5b72c7c361f87ae0958d6bfd62ad5232eed7439b9fb7165d54bd) line 55, and during the modification process, it was found that the test should be refactored directly.
> refactor: TestBlockingTags

- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- src/cluster/eks.go
1.24 changed the APIVersion of the client.authentication.k8s.io.
Properly generating EKS KUBECONFIG client.authentication.k8s.io APIVersion for aws-iam-authenticator tokens.
Because it was not working well for UI/API downloaded KUBECONFIGs even though banzai CLI solves some of these problems.
> fix(EKS,Authn): fixed aws-iam-authn apiversion

- Dockerfile
- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- src/cluster/eks.go
Properly generating EKS KUBECONFIG client.authentication.k8s.io APIVersion for aws-iam-authenticator tokens.
Because it was not working well for UI/API downloaded KUBECONFIGs even though banzai CLI solves some of these problems.
> Fixed EKS new aws-iam-authn apiVersion

- charts/pipeline/values.yaml
- cmd/pipeline/main.go
- config/config.yaml.dist
- internal/cmd/config.go
- internal/providers/azure/pke/driver/BUILD.plz
- internal/providers/azure/pke/driver/cluster_creator.go
- src/api/BUILD.plz
- src/api/cluster.go
- src/api/cluster_create.go
- src/api/error.go
Added config options to disable starting PKE clusters on Azure or AWS. If PKE is disabled on either of them, the cluster creation request now returns 400 Bad Request with the message `Not supported distribution type`.
It is nice to have more configuration options for Pipeline CP, also PKE on Azure is currently misbehaving, and we decided to drop support for now.
A similar solution is going to be implemented in Cloudinfo to remove the disabled options from the GUI as well.
- ~OpenAPI and Postman files updated (if needed)
> Option to disable PKE on Azure and AWS

- internal/pke/BUILD.plz
- internal/pke/kubernetes.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
- pkg/cluster/base.go
- pkg/cluster/pke/BUILD.plz
- pkg/cluster/pke/types.go
- pkg/errors/errors.go
- src/api/error.go
Added PKE Kubernetes version validation with hard-coded minimum and maximum version numbers. Starting a PKE cluster with higher or lower Kubernetes version than supported now results in a 400 Bad Request error response from the Pipeline API in the case of the following cloud providers:
- Amazon
- Azure
- vSphere
Previously if someone started a PKE cluster with higher K8s version than available, there were no feedback from the API that this is not allowed, although the cluster creation failed later on.
- ~User guide and development docs updated (if …
> PKE K8s version validation

- .plzconfig
- BUILD.plz
- pleasew
- third_party/go/BUILD.plz
- tools/BUILD
Updated packages used by the please build system to a version that supports darwin arm64 architecture.
So `plz` `build`, `tidy`, `test`, `run` commands are usable on M1 Macs.
The version of `golangci-lint` has not yet been increased (so `plz lint` still doesn't work) because its latest version finds a ton of problems to fix, so that will be the topic of another PR. 
> Fix please on darwin arm64

- src/cluster/gke.go
Fixed GKE 1.24 SA handling.
Because it was broken not checking properly whether the SA token secret exists already.
- ~[] OpenAPI and Postman files updated (if needed)~
- ~[] User guide and development docs updated (if needed)~
- ~[] Related Helm chart(s) updated (if needed)~
> fix(GKE,1.24): fixed SA token handling

- src/cluster/gke.go
Fixing error matching for GKE 1.24 create SA token case.
Because it is a generic K8s secret getter error and I matched a GKE error originally.
- ~[] OpenAPI and Postman files updated (if needed)~
- ~[] User guide and development docs updated (if needed)~
- ~[] Related Helm chart(s) updated (if needed)~
> fix(GKE,1.24): fixed error msg match

- .gen/cloudinfo/api/openapi.yaml
- .gen/cloudinfo/api_images.go
- apis/cloudinfo/openapi.yaml
- cmd/worker/main.go
- internal/cluster/distribution/pke/pkeaws/pkeawsadapter/image_selector.go
Added `gpu` and `cr` params to Cloudinfo request listing the available PKE images.
In order to correctly filter the latest, default PKE 0.9.3 images.
> Updated PKE image Cloudinfo request params

- templates/eks/amazon-eks-iam-cf.yaml
- templates/pke/global.cf.yaml
Added EBS CSI driver policy to EKS NodeInstanceRole and PKE AWS WorkerRole.
To make K8s 1.23+ clusters work out of the box with PVCs when the new EBS CSI driver is installed and set to use the role inherited from the nodes (easiest default setup without the additional OIDC burden).
The installation of the new driver is going to be added in another PR.
> Added EBS CSI driver policy to EKS NodeInstanceRole and PKE AWS WorkerRole

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- .github/workflows/helm.yml
| Q               | A      |
| --------------- | ------ |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | - |
| License         | Apache 2.0 |
Replaced `::set-output` with `>> $GITHUB_OUTPUT`
Deprecated, will be removed in 2023-05-31.
Details: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
Tested [in another PR](https://github.com/banzaicloud/koperator/pull/906/files#diff-dce4cd1ca1dc3e5849de0fd3f3c7b132ad537e4ba79ba191f5de4330484b214bR39), worked well.
- ~Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)~
- ~Logging code meets the guideline~
- ~User guide and …
> Replaced GHA `set-output` with `GITHUB_OUTPUT`

- .licensei.toml
- docker-compose.yml
- internal/cmd/config.go
- Updated the Bank-Vaults webhook version (1.10.1->1.16.0) to the latest default in Pipeline config that is also used in the latest community installer (0.36.2).
- Updated Vault (1.6.1->1.6.2), Bank-Vaults (1.10.0->1.16.0) and pipeline-web (0.27.0->0.42.1) to the latest default versions also used in the latest community installer (0.36.2) in the docker-compose file used for local development.
So versions are consolidated across the Pipeline-related repos.
- ~Related Helm chart(s) …
> Updated vault, bank-vaults and pipeline-web versions

- .plzconfig
- config/config.yaml.dist
- docker-compose.yml
- internal/cmd/config.go
- internal/cmd/config_test.go
- internal/integratedservices/testconfig/docker-compose.yml
Updated packages:
- `external-dns` version 6.5.1->6.12.2 (latest) because the Helm chart for the old one got removed from the bitnami repository (an it also broke automated tests).
- `cadence-web` version 3.29.5->3.32.0 in the docker-compose file used for local development because that is what is used in the installer now
- `please` version 16.22.0->16.26.1
- service versions in the docker-compose file used in integration testing to match the version numbers used for local development and by the installer 
- ~User guide and development docs updated …
> Updated packages
