banzaicloud/pipeline

- cloud/utils.go
- helm/helm.go
- main.go
* Option to use specify helm release name
* add ?field=name feature to all api endpoints
> Helm release name change and filter by cluster name

- .circleci/config.yml
- .circleci/images/primary/Dockerfile
- .circleci/images/prod/Dockerfile
- Makefile
- auth/authn.go
- conf/logger.go
- main.go
print semVer it the first arg is `--version`
rigtht now the version number is specified in the Makefile.
TODO:
- later it has to come from a git tag.
- It the actual commit has a tag don't set the ldflags `-X main.GitRev=$(GITREV)" ` in go build.
> Add version

- main.go
> fix cluster PostHook to wait for certificate 

- helm/kubernetes.go
- main.go
> Add deployment state check

- cloud/aws.go
- cloud/azure.go
- cloud/base.go
- cloud/cluster.go
- main.go
- utils/utils.go
Separate aws/aks methods/functions to aws/aks go files
> Separate methods/functions

- main.go
- pods/kubernetes.go
List pods per node on status endpoint and also a small modification in utils.GetConfig to use the config if it's already downloaded.
> PIP-18. List pods per node on status endpoint (magyari_sandor)

- api/cluster.go
- api/custom.go
- api/custom_test.go
- api/defaults.go
- api/helm.go
- auth/authn.go
- auth/github.go
- auth/tokenstore.go
- auth/user.go
- cluster/aks.go
- cluster/aws.go
- cluster/common.go
- cluster/gke.go
- cluster/hooks.go
- cluster/monitor.go
- cluster/promconf.go
- config/configuration.go
- helm/helm.go
- helm/install.go
- helm/kubernetes.go
- main.go
- model/cluster.go
- model/database.go
- model/defaults/aks.go
- model/defaults/aws.go
- model/defaults/base.go
- model/defaults/base_test.go
- model/defaults/gke.go
- utils/utils.go
This PR is suppose to correct this to make pipeline great again by passing go report with a+:)
> Fixing go report issues

- api/helm.go
improved status code + message handling in the helm deployment status call
improved logging
> fixed the helm deployment status call

- cluster/gke.go
grant read/write for object storage
> set permission for object storage

- README.md
- remove duplicated folders
- fix importing error
> Fix v0.3.0 postman collection

- api/meta.go
- main.go
> Create MetaHandler to describe the API as a JSON struct

- cluster/gke.go
> Persist cluster before polling in case of gke

- model/defaults/gke.go
Set default GKE master/node version to `1.9.4-gke.1`.
> Update GKE master/node default version

- api/secrets.go
- api/secrets_test.go
- main.go
- secret/store.go
> New secret API endpoint

- api/secrets.go
- api/secrets_test.go
- main.go
- secret/store.go
> Add allowed secret types (and required keys) endpoint

- README.md
OpenAPI 3.0, Helm via REST, etc updates
> OpenAPI 3.0, Helm via REST, etc updates

- api/cluster.go
- api/secrets.go
- model/cluster.go
- secret/store.go
> Check cluster(s) before delete a secret

- auth/authn.go
- auth/tokenstore.go
Method == POST check is needed to support the deprecated GET method.
> Support access token naming

- api/cluster.go
- api/helm.go
- cluster/aks.go
- cluster/aws.go
- cluster/common.go
- cluster/dummy.go
- cluster/gke.go
- cluster/hooks.go
- helm/helm.go
- helm/install.go
- helm/kubernetes.go
> Remove unnecessary *[]byte from CommonCluster interface

- Gopkg.lock
- api/cluster.go
- cluster/aks.go
- cluster/aws.go
- cluster/byoc.go
- cluster/common.go
- cluster/common_test.go
- cluster/gke.go
- main.go
- model/cluster.go
- secret/store.go
- secret/store_test.go
- utils/utils.go
- vendor/github.com/banzaicloud/banzai-types/components/base.go
- vendor/github.com/banzaicloud/banzai-types/components/byoc/byoc.go
- vendor/github.com/banzaicloud/banzai-types/constants/constants.go
> Build Your Own Cluster

- .circleci/config.yml
- Gopkg.lock
- vendor/github.com/banzaicloud/azure-aks-client/client/aks.go
- vendor/github.com/banzaicloud/azure-aks-client/client/base.go
- vendor/github.com/banzaicloud/azure-aks-client/utils/utils.go
> Update azure sdk

- api/cluster.go
> Dont allow update until cluster is not in RUNNING state

- api/cluster.go
- api/helm.go
- api/secrets.go
- cluster/aws.go
- cluster/common.go
- cluster/monitor.go
> Remove isReadStateStore and fix updatecluster error in case of aws

- Gopkg.lock
- api/cluster.go
- cluster/aks.go
- cluster/aws.go
- cluster/byoc.go
- cluster/common.go
- cluster/common_test.go
- cluster/dummy.go
- cluster/gke.go
- cluster/gke_test.go
- main.go
- model/cluster.go
- model/defaults/aks.go
- model/defaults/base_test.go
- model/defaults/gke.go
- vendor/github.com/banzaicloud/azure-aks-client/cluster/managed.go
- vendor/github.com/banzaicloud/banzai-types/components/azure/azure.go
- vendor/github.com/banzaicloud/banzai-types/components/base.go
- vendor/github.com/banzaicloud/banzai-types/components/google/google.go
- vendor/github.com/banzaicloud/banzai-types/constants/constants.go
> Add nodepool support in case of azure

- api/helm.go
- helm/helm.go
- main.go
- Chart details endpoint
- Chart list refactor
> Chart details endpoint

- Gopkg.lock
- vendor/github.com/kubicorn/kubicorn/cloud/amazon/public/resources/instanceprofile.go
> Fix Pipeline panic's in case of aws cluster update

- Gopkg.lock
- Gopkg.toml
- cluster/supported/aks.go
- cluster/supported/aws.go
- cluster/supported/base.go
- cluster/supported/gke.go
- docs/cloudinfo-howto.md
- model/cluster.go
- vendor/github.com/banzaicloud/banzai-types/components/base.go
- vendor/github.com/banzaicloud/banzai-types/constants/constants.go
> Fix cloudinfo

- Gopkg.lock
- Gopkg.toml
- api/cluster.go
- api/profiles.go
- cluster/common_test.go
- model/defaults/aks.go
- model/defaults/aws.go
- model/defaults/base.go
- model/defaults/gke.go
- vendor/github.com/banzaicloud/banzai-types/components/base.go
- vendor/github.com/banzaicloud/banzai-types/constants/constants.go
> Create cluster with profile

- Gopkg.lock
- cluster/aws.go
- cluster/common_test.go
- main.go
- model/defaults/aws.go
- model/defaults/base.go
- model/defaults/base_test.go
- vendor/github.com/banzaicloud/banzai-types/components/amazon/amazon.go
- vendor/github.com/banzaicloud/banzai-types/components/base.go
> Update aws profiles

- api/user.go
- auth/authz.go
- auth/user.go
- fixes several issues with token based authz
> authz: Change username to userid

- docker-compose-local.yml
See: https://github.com/docker/compose/issues/5675
> Remove vault-configurer restart: on-failure, it is buggy

- cluster/aws.go
- cluster/gke.go
- cluster/supported/aws.go
- docs/cloudinfo-howto.md
> Add credentials to all ec2 call

- docs/developer.md
These are useful developer tools for accessing MySQL and Vault
> Add tool descriptions

- docs/openapi/pipeline.yam
> Pipeline OpenAPI specification

- Gopkg.lock
- Gopkg.toml
- cluster/aws.go
- cluster/common.go
- cluster/common_test.go
- model/cluster.go
- model/defaults/aws.go
- model/defaults/base_test.go
- vendor/github.com/banzaicloud/banzai-types/components/amazon/amazon.go
- vendor/github.com/banzaicloud/banzai-types/constants/constants.go
- vendor/github.com/kubicorn/kubicorn/cloud/amazon/public/resources/launchconfiguration.go
> Fix amazon update

- api/secrets.go
- api/secrets_test.go
- main.go
- secret/store.go
> Add new secrettype repo and allow to list and create them

- Gopkg.lock
- api/cluster.go
- cluster/aks.go
- cluster/aws.go
- cluster/common.go
- cluster/dummy.go
- cluster/gke.go
- cluster/kubernetes.go
- model/cluster.go
- vendor/github.com/banzaicloud/banzai-types/components/base.go
- vendor/github.com/banzaicloud/banzai-types/constants/constants.go
> Validate fields after cluser persist

- Gopkg.lock
- api/custom.go
- api/custom_test.go
- vendor/github.com/banzaicloud/banzai-types/components/helm/helm.go
> Return 202 in case of LoadBalancer is still in pending state

- cluster/hooks.go
- config/config.toml.example
- config/configuration.go
> Make configurable helm tiller image version, and use 2.9.0 by default

- api/cluster.go
Also commonCluster.Persist() error should mean HTTP 500
> Call commonCluster.ValidateCreationFields() before returning HTTP 202

- Gopkg.lock
- Gopkg.toml
- cluster/aws.go
- vendor/github.com/banzaicloud/banzai-types/components/amazon/amazon.go
- vendor/github.com/banzaicloud/banzai-types/constants/constants.go
- vendor/github.com/kubicorn/kubicorn/pkg/script/script.go
- vendor/k8s.io/helm/cmd/helm/installer/install.go
- vendor/k8s.io/helm/pkg/chartutil/files.go
- vendor/k8s.io/helm/pkg/strvals/parser.go
> Remove nodepool limitation in case of aws

- cluster/gke.go
- cluster/gke_test.go
> Allow major.minor K8S version in case of GKE

- Gopkg.lock
- api/cluster.go
- api/secrets.go
- api/secrets_test.go
- main.go
- secret/store.go
- vendor/github.com/banzaicloud/banzai-types/components/base.go
- vendor/github.com/banzaicloud/banzai-types/constants/constants.go
> Add endpoint to install secrets into a cluster's namespaces

- Gopkg.lock
- Gopkg.toml
- auth/authn.go
- auth/authz.go
- auth/user.go
- main.go
- vendor/github.com/qor/auth/auth.go
- vendor/github.com/qor/auth/controller.go
- vendor/github.com/qor/auth/handlers.go
- vendor/github.com/qor/auth/provider.go
- vendor/github.com/qor/auth/providers/github/github.go
> User Deregistration

- Gopkg.lock
- Gopkg.toml
- api/cluster.go
- api/secrets.go
- api/secrets_test.go
- auth/authn.go
- cluster/common_test.go
- cluster/dummy.go
- docs/openapi/pipeline.yaml
- main.go
- secret/store.go
- secret/store_test.go
> Secret handling reconciliation 

- cluster/aws.go
- docs/postman/e2e_test.postman_collection.json
- model/cluster.go
- secret/store.go
- secret/store_test.go
- ssh/ssh.go
> Ssh-key generator with Bank Vaults support

- docs/openapi/pipeline.yaml
- docs/postman/e2e_test.postman_collection.json
> Update OpenApi and Postman collection

- api/cluster.go
- api/secrets.go
- cluster/aks.go
- cluster/aws.go
- cluster/common.go
- cluster/dummy.go
- cluster/gke.go
- cluster/hooks.go
- cluster/kubernetes.go
- helm/helm.go
- model/cluster.go
- secret/store.go
- utils/utils.go
> Store Kubernetes config in vault

- api/cluster.go
- cluster/autoscale.go
- cluster/hooks.go
- helm/helm.go
> #518 - Deploy default cluster-autoscaler after cluster create

- auth/authn.go
This scope is needed for star-ing the repo and writing issues for the Pipeline.
> WIP: Ask for GitHub public_repo scope

- Gopkg.lock
- api/helm.go
- helm/helm.go
- vendor/github.com/banzaicloud/banzai-types/components/helm/helm.go
> Support Namespaces for Deployments (#541)

- docs/openapi/pipeline.yaml
- docs/postman/e2e_test.postman_collection.json
add new fields for autoscaling
> update postman & openapi

- cluster/gke.go
> Gke Cluster destroy timeout

- cluster/gke.go
> Wait until Kubernetes destroys all resources in case of GKE

- audit/audit.go
- main.go
> Add system request level audit

- model/cluster.go
> Change status_message type to `TEXT` on clusters table

- cluster/common.go
- cluster/hooks.go
> Re-download K8S config

- .gitignore
- audit/audit.go
- config/configuration.go
- main.go
> Audit HTTP headers

- .circleci/config.yml
Reverts banzaicloud/pipeline#580
Fixes: #582
> Revert "Temporary CircleCI fix "

- .gitignore
- auth/authn.go
- config/configuration.go
- main.go
```bash
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost'
```
> Gin Listener TLS Support

- Gopkg.lock
- api/supported.go
- cluster/supported/base.go
- docs/cloudinfo-howto.md
- docs/openapi/pipeline.yaml
- docs/postman/e2e_test.postman_collection.json
- main.go
- vendor/github.com/banzaicloud/banzai-types/components/base.go
- vendor/github.com/banzaicloud/banzai-types/components/catalog/catalog.go
> Change cloud info requests method

- Gopkg.lock
- vendor/github.com/banzaicloud/bank-vaults/auth/tokenstore.go
> Update bank-vaults to fix NPE in token parsing

- Gopkg.lock
- docs/cloudinfo-howto.md
- docs/openapi/pipeline.yaml
- docs/postman/e2e_test.postman_collection.json
> Use common instanceType json key

- api/bucket.go
- api/cluster.go
- api/secrets.go
- api/secrets_test.go
- api/supported.go
- cluster/common.go
- cluster/common_test.go
- cluster/secrets.go
- model/cluster.go
- secret/store.go
- ssh/ssh.go
Extract cluster.InstallSecrets function
> secrets: Change organizationID to uint everywhere

- Gopkg.lock
- api/applications.go
- api/catalog.go
- api/cluster.go
- application/applications.go
- catalog/catalog.go
- cluster/aks.go
- cluster/aws.go
- cluster/common.go
- cluster/dummy.go
- cluster/gke.go
- cluster/hookfunctions.go
- cluster/hooks.go
- cluster/kubernetes.go
- config/config.toml.example
- config/configuration.go
- constants/constants.go
- docs/openapi/pipeline.yaml
- helm/helm.go
- helm/install.go
- main.go
- model/application.go
- model/cluster.go
- model/database.go
- vendor/github.com/banzaicloud/banzai-types/components/application/application.go
> Deploy Application API Endpoint

- cluster/gke.go
> Fix GKE cluster update

- auth/authn.go
> Don't store drone session tokens in Vault

- Gopkg.lock
- vendor/github.com/banzaicloud/bank-vaults/auth/tokenstore.go
Includes better "API token not found" handling.
> Update bank-vaults to 0.2.2

- auth/authn.go
- auth/user.go
> Align deregistration SQL query to MySQL (it was MariaDB compatible)

- model/cluster.go
> Delete SSH secret in case of cluster delete

- api/secrets.go
- client/api/openapi.yaml
- client/docs/ClustersApi.md
- client/docs/CreateSecretResponse.md
- client/model_create_secret_response.go
- docs/openapi/pipeline.yaml
- secret/store.go
> Add missing fields to update/create secret responses

- cluster/aws.go
- pkg/cluster/amazon/amazon.go
> Add default image in pools in case of AWS update

- .gitignore
- api/applications.go
- docs/postman/e2e_test.postman_collection.json
Also merge Cluster and Clusters folders
> Postman: add application requests

- api/applications.go
- cluster/aks.go
- cluster/aws.go
- cluster/common.go
- cluster/dummy.go
- cluster/gke.go
- cluster/kubernetes.go
> Fix wrong creatorName in responses

- cluster/monitor.go
> Fix SIGSEGV in UpdatePrometheusConfig

- cluster/common.go
- cluster/hooks.go
- secret/store.go
- Make StoreKubeConfig posthook function idempotent
- Log posthook states as status message during cluster creation
> Posthook fixes

- cluster/hooks.go
- helm/helm.go
> Idempotent helm hooks

- cluster/hookfunctions.go
- cluster/hooks.go
- pkg/cluster/base.go
> Add Install Kubernetes Dashboard posthook

- client/api/openapi.yaml
- client/docs/ClusterDetailsResponse.md
- client/docs/GetClusterStatusResponse.md
- client/model_cluster_details_response.go
- client/model_get_cluster_status_response.go
- cluster/gke.go
- docs/openapi/pipeline.yaml
- model/cluster.go
- pkg/cluster/base.go
> Save region to cluster in case of GKE

- cluster/gke.go
- cluster/hooks.go
> Fix panic in case of GKE cluster autoscaling update

- cluster/hooks.go
- config/config.toml.example
- config/configuration.go
- secret/store.go
- Grafana admin password generator
- CreateOrUpdate secret function
> Grafana admin password generator

- api/cluster.go
> Format CPU and Memory summary in details responses

- Dockerfile
> Add git to Dockerfile's build stage

- cluster/aks.go
- cluster/aws.go
- cluster/common.go
- cluster/dummy.go
- cluster/eks.go
- cluster/gke.go
- cluster/hooks.go
- cluster/kubernetes.go
- cluster/oke.go
- model/cluster.go
> Grafana ingress support

- cluster/eks.go
- pkg/cluster/eks/action/actions.go
- templates/eks/amazon-eks-nodepool-cf.yaml
- templates/eks/amazon-eks-vpc-cf.yaml
Move role creation to CF template. 
Delete node pool stacks first.
> EKS: create iam roles with cf template

- .gitignore
- .idea/modules.xml
- .idea/pipeline.iml
- .idea/runConfigurations/Debug.xml
- .idea/runConfigurations/Tests.xml
JetBrains recommends certain files in the .idea directory to be version controlled (although this is as opinionated as the tabs vs spaces debate): https://intellij-support.jetbrains.com/hc/en-us/articles/206544839
This PR also includes a set of build configurations to easily execute tests and run the application itself from Goland.
WDYT?
> Add idea build configuration

- docker-compose.yml
- main.go
- model/defaults/base.go
- model/defaults/eks.go
This PR fixes some issues I faced during the initial project setup.
> Initial setup

- Dockerfile
The build command in the dockerfile failed ...
> fixed the dockerfile - added the migrate.go file to the build command

- client/api/openapi.yaml
- client/docs/ClusterDetailsResponse.md
- client/docs/ClusterDetailsResponseNodePoolsPool1.md
- client/model_cluster_details_response.go
- client/model_cluster_details_response_node_pools_pool1.go
- cluster/aks.go
- cluster/ec2.go
- cluster/eks.go
- cluster/gke.go
- cluster/oke.go
- docs/openapi/pipeline.yaml
- pkg/cluster/base.go
> Add status and count fields to details response

- docs/postman/e2e_test.postman_collection.json
> Refactor Postman collection params

- docs/postman/e2e_test.postman_collection.json
> Refactor postman variables

- cluster/gke.go
- cluster/gke_operations.go
- cluster/gke_operations_compute_global.go
- cluster/gke_operations_compute_region.go
- cluster/gke_operations_container.go
- cluster/gke_resource.go
- cluster/gke_resource_firewall.go
- cluster/gke_resource_forwarding_rules.go
- cluster/gke_resource_loadbalancer.go
- cluster/gke_resource_target_pools.go
- config/config.toml.example
- config/configuration.go
> Add force delete in case of GKE resources

- api/bucket.go
- internal/objectstore/objectstore.go
- internal/providers/amazon/objectstore.go
- internal/providers/azure/objectstore.go
- internal/providers/google/objectstore.go
- internal/providers/oracle/objectstore.go
- objectstore/alibaba.go
> Return error from CreateBucket

- .pipeline.yml
This is a sample .pipeline.yaml which is capable of build and test the Pipeline project and push a Docker image from it to DockerHub (using secrets)
> Add .pipeline.yml

- api/cluster.go
- cluster/common.go
- cluster/hooks.go
- dns/route53/route53.go
- pkg/secret/secret.go
- secret/restricted_store.go
- secret/restricted_store_test.go
- secret/ssh.go
> Introduce readonly tag on secrets

- cluster/acsk.go
In a different PR I am going to refactor the whole Alibaba cloud integration, but this one is needed to try out the UI end to end.
> Initial version of getting kubeconfig via scp in case of Alibaba

- auth/authn.go
- config/config.toml.example
- config/configuration.go
This solves the missing cookie issue on http://localhost... access.
> Make auth.secureCookie configurable

- pkg/providers/amazon/objectstore/objectstore_test.go
Test running is enabled by adding the relevant environment variables (which I configured in circle)
> Run AWS integration tests for object store

- api/cluster.go
- cluster/manager.go
- cluster/manager_get.go
- main.go
- pkg/model/clusters.go
Next round of cluster refactoring
> Cluster improve

- Gopkg.lock
Fixes the vendor cache issue on master
> Update bank vaults

- api/cluster.go
- api/secrets.go
- auth/user.go
- cluster/error_handler.go
- cluster/hooks.go
- cluster/manager.go
- cluster/manager_delete.go
- cluster/manager_get.go
- cluster/monitor.go
- internal/cluster/clusters.go
- main.go
- model/cluster.go
This PR removes dependency on the model package from a lot of places which is one of the import cycle sources.
> Cluster model dependency

- Gopkg.lock
- Gopkg.toml
- spotguide/dronerepoconfig.go
- spotguide/dronerepoconfig_test.go
- spotguide/spotguide.go
> CICD descriptor structs

- api/helm.go
- client/api/openapi.yaml
- client/docs/CreateUpdateDeploymentRequest.md
- client/model_create_update_deployment_request.go
- cluster/autoscale.go
- cluster/hooks.go
- docs/openapi/pipeline.yaml
- helm/helm.go
- pkg/helm/helm.go
> Deployment API: add support for chart packages

- api/helm.go
If the cluster was not found, both parseCreateUpdateDeploymentRequest()
and Create/UpgradeDeployment() wrote a full json response to the context
resulting in two json top-level dicts sent.
needs testing!
> Create/UpgradeDeployment: fix invalid json response

- api/cluster.go
- api/secrets.go
- api/secrets_test.go
- client/README.md
- client/api/openapi.yaml
- client/api_clusters.go
- client/api_secrets.go
- client/docs/ClustersApi.md
- client/docs/SecretsApi.md
- cluster/hooks.go
- dns/route53/route53.go
- dns/route53/route53_test.go
- docs/openapi/pipeline.yaml
- docs/postman/e2e_test.postman_collection.json
- main.go
- pkg/secret/secret.go
- secret/store.go
> List secrets which belongs to cluster

- cluster/hooks.go
- cluster/secrets.go
- secret/restricted_store.go
Also make InstallSecretWithVaultID idempotent.
> Merge InstallSecrets with InstallOrUpdateSecrets calls

- client/api/openapi.yaml
- client/docs/InstallSecretsRequestQuery.md
- client/model_install_secrets_request_query.go
- cluster/hooks.go
- cluster/secrets.go
- docs/openapi/pipeline.yaml
- pkg/secret/secret.go
- secret/store.go
> Simplify installing secrets to clusters by ID

- cluster/manager_delete.go
> Delete all Kubernetes resources

- .banzaicloud/pipeline.yaml
- client/api/openapi.yaml
- client/docs/LaunchSpotguidesRequest.md
- client/docs/LaunchSpotguidesRequestCluster.md
- client/model_launch_spotguides_request.go
- docs/openapi/pipeline.yaml
- spotguide/dronerepoconfig.go
- spotguide/spotguide.go
> Support passing in CreateClusterRequest to spotguides

- cluster/common.go
- cluster/common_test.go
- cluster/gke.go
- cluster/gke_global.go
- cluster/gke_node_pools.go
- cluster/gke_test.go
- internal/cluster/cluster_model.go
- internal/cluster/log.go
- internal/providers/google/cluster.go
- internal/providers/google/gke_cluster_model.go
- internal/providers/google/gke_cluster_model_test.go
- internal/providers/google/provider.go
- main.go
- model/cluster.go
This PR refactors GKE models:
- Uses the new cluster model
- Inverts the relationship between the cluster model and GKE cluster model
- Moves the model to internal code
- Removes ineffective tests
> Refactor GKE model

- Gopkg.lock
- Gopkg.toml
- cluster/secrets.go
- pkg/secret/secret.go
- secret/store.go
Opaque secret field is a secret field which is not installed into the user Kubernetes cluster as `v1.Secret` just stored in Vault.
> htpasswd secret type support and opaque secret field support

- cluster/acsk.go
- cluster/aks.go
- cluster/common.go
- cluster/dummy.go
- cluster/ec2.go
- cluster/eks.go
- cluster/gke.go
- cluster/hooks.go
- cluster/kubernetes.go
- cluster/oke.go
- dns/route53/route53.go
- dns/route53/route53_test.go
- spotguide/spotguide.go
> Route53 secret region support

- spotguide/spotguide.go
> Add Spotguide Icon and Readme

- internal/audit/middleware.go
So we can send back HTTP 400 instead of internal server error if the JSON is malformed.
Fixes the following error in the logs:
```
time="2018-09-24T16:41:26Z" level=error msg="Error #01: Error 3140: Invalid JSON text: \"Missing a name for object member.\" at position 1 in value for column 'audit_events.body'.\n" correlation-id=f94f97f3-b497-41d0-8674-16ad1db499fc function=func1 ip=10.128.0.11 latency=5.064146ms method=PUT path=/pipeline/api/v1/orgs/2/spotguides status=500 user-agent=PostmanRuntime/7.2.0
```
> audit: validate JSON before saving to DB

- api/bucket.go
- api/hpa.go
- internal/platform/gin/utils/query.go
Fix invalid json response and send not found message if needed
> Small HPA fixes

- spotguide/spotguide.go
> Support private spotguide user repos

- model/cluster.go
> Fix cluster model foreign key

- Gopkg.lock
- Gopkg.toml
- api/spotguide.go
- auth/authn.go
- auth/events.go
- auth/user.go
- config/events.go
- main.go
- spotguide/events.go
- spotguide/spotguide.go
This PR also introduces the idea of general eventing as well to the project to support more loose coupling between modules and support extraction of services to separate processes in the future.
Fixes: #1130
> Add org level spotguide catalog support

- api/bucket.go
- client/api/openapi.yaml
- client/api_storage.go
- client/docs/StorageApi.md
- docs/openapi/pipeline.yaml
> Add secretName support to BucketStatusRequest

- pkg/helm/helm.go
- spotguide/spotguide.go
- spotguide/spotguide_test.go
> Support the more flexible spotguide questionnaire format

- spotguide/spotguide.go
fixes: https://github.com/banzaicloud/pipeline/issues/1110
> Support deleting obsolete spotguides during scraping

- api/helm.go
- client/api/openapi.yaml
- client/api_deployments.go
- client/docs/DeploymentsApi.md
- cluster/autoscale.go
- cluster/hooks.go
- docs/openapi/pipeline.yaml
- helm/helm.go
- internal/ark/deployments_svc.go
> Support deployment filtering by banzaicloud.tags

- Gopkg.lock
- Gopkg.toml
- cluster/secrets.go
- spotguide/dronerepoconfig.go
- spotguide/spotguide.go
Also, fix deeply nested map merging with mergo.
> Fix marshaling issues in spotguide's install secret requests

- Gopkg.lock
- Gopkg.toml
- spotguide/dronerepoconfig.go
- spotguide/spotguide.go
- spotguide/spotguide_test.go
- JSON vs. YAML merging fully covered with unit test.
- Empty and null values can be used in templates.
> Spotguide: support all kinds of Pipeline JSON merging + Unit test

- cluster/hooks.go
- helm/install.go
> Upgrade Helm to the requested version if installed already

- Gopkg.lock
- Gopkg.toml
- api/helm.go
- helm/helm.go
> Cache Helm release details during listing

- cluster/eks.go
- dns/route53/iamUser.go
- dns/route53/route53.go
- pkg/amazon/iamSvc.go
- pkg/cluster/eks/action/actions.go
- templates/eks/amazon-eks-vpc-cf.yaml
Reverts banzaicloud/pipeline#1211
> Revert "Factor out cluster user access key creation"

- cluster/eks.go
- dns/route53/iamUser.go
- dns/route53/route53.go
- pkg/amazon/iamSvc.go
- pkg/cluster/eks/action/actions.go
- templates/eks/amazon-eks-vpc-cf.yaml
> Factor out clusteruser accesskey creation

- client/SHA256SUMS
- client/api/openapi.yaml
- client/api_imagescan.go
- client/docs/ImagescanApi.md
- docs/openapi/pipeline.yaml
Fix imagescan POST request body
> Fix openapi

- pkg/cluster/eks/action/actions.go
> Fix: Pipeline doesn't report CloudFormation errors

- cluster/acsk.go
- cluster/eks.go
- cluster/manager_delete.go
- pkg/cluster/eks/action/actions.go
- pkg/cluster/eks/action/asg_action.go
- pkg/providers/amazon/autoscaling/autoscaling.go
- pkg/providers/amazon/autoscaling/errors.go
- pkg/providers/amazon/autoscaling/instance.go
- pkg/providers/amazon/autoscaling/manager.go
- pkg/providers/amazon/ec2/errors.go
- pkg/providers/amazon/ec2/spotrequest.go
Wait for ASGs to get into desired state in cluster create/update requests
> EKS: wait for ASGs

- auth/authn.go
Now the Pipeline won't redirect after logout (just return 200) and the UI can handle the redirect flow.
> Remove redirect from logout

- api/security.go
- docs/postman/e2e_test.postman_collection.json
Fix httpResponse in case of GetImageDeployments
Fix postman
Fix edge case in case of getting imageDigest
> Fix getimagedeployments

- Gopkg.lock
- Gopkg.toml
- api/user.go
- auth/authn.go
- auth/authz.go
- auth/error_handler.go
- auth/user.go
- internal/platform/database/dsn.go
- main.go
- secret/store.go
- Replace user cookie content from a custom format to the API token format.
- Support for expiring tokens.
- GC expired tokens.
> API token as Cookie

- Gopkg.lock
- Gopkg.toml
https://github.com/banzaicloud/bank-vaults/pull/198
> Update bank-vaults to include tokenstore sigsegv fix

- database/migrations/1541419768_modify_default_objectstore_error_field.down.sql
- database/migrations/1541419768_modify_default_objectstore_error_field.up.sql
- internal/providers/amazon/objectstore_model.go
- internal/providers/azure/objectstore.go
- internal/providers/azure/objectstore_model.go
- internal/providers/google/objectstore_model.go
> Fix Azure create bucket invalid error message and increase database column size for error message

- api/security.go
- client/README.md
- client/SHA256SUMS
- client/api/openapi.yaml
- client/api_scanlog.go
- client/docs/ScanlogApi.md
- cmd/pipeline/main.go
- docs/openapi/pipeline.yaml
- docs/postman/e2e_test.postman_collection.json
fixes: #1280 
- add new scanlog API endpoint
- update swagger
- update postman
> Get scanlog by release

- cluster/acsk.go
- pkg/cluster/acsk/template.go
> Fix Alibaba cluster details API to provide Kubernetes version

- api/helm.go
- api/security.go
- pkg/helm/helm.go
fixes: #1270 
- add rejected flag to deployment in case of listing it
- fix GetWhiteListSet (using whitelist ObjectMeta.Name instead of Spec.ReleaseName)
> Deployment validation status

- internal/providers/alibaba/model.go
- internal/providers/alibaba/objectstore.go
- internal/providers/alibaba/objectstore_model.go
- internal/providers/alibaba/objectstore_test.go
- internal/providers/azure/objectstore.go
- internal/providers/objectstore.go
* added states to the bucket model
* simplified / cleaned the code
* improved logging and error handling
* added `force` delete option
Fixes #1314
> object store management fixes - alibaba 

- spotguide/spotguide.go
otherwise non-text files are getting messed up
> spotguide: post files in base64 encoding to GitHub API

- Gopkg.toml
> remove blackfriday override

- .circleci/config.yml
- Makefile
An example build with failed tests: https://circleci.com/gh/banzaicloud/pipeline/5479
> Fix CircleCI test report collection

- api/issue.go
- auth/authn.go
- auth/github.go
- cmd/pipeline/main.go
- config/config.toml.example
- config/configuration.go
- docs/openapi/internal.yaml
- issue/github.go
- issue/issue.go
- spotguide/spotguide.go
The API adds the ability to submit user issues via the UI to a configurable issue tracking backend, currently, GitHub is implemented.
> Add issues API

- internal/providers/amazon/objectsore_test.go
- internal/providers/amazon/objectstore.go
- pkg/providers/amazon/objectstore/objectstore.go
* buckets being deleted are ignored while retrieving
* sneaked in a few error - related fixes (contextual errors, proper and consistent messages)
> fixed listing buckets-buckets being deleted are ignored

- api/helm.go
- cluster/autoscale.go
- cluster/hooks.go
- helm/helm.go
- internal/ark/deployments_svc.go
Please merge only after today's release
> refactored default options on create deployment

- cluster/hooks.go
This change is dependent on https://github.com/banzaicloud/banzai-charts/pull/495.
> Configure traefik to use self generated certificate

- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/LaunchSpotguidesRequest.md
- client/model_launch_spotguides_request.go
- docs/openapi/pipeline.yaml
- spotguide/spotguide.go
> Support for latent spotguide repos

- README.md
> readme: replace outdated postman collection

- .circleci/config.yml
- docker-compose.override.yml.dist
- docker-compose.yml
- scripts/vault.hcl
**NOTE**: Please update your `docker-compose.override.yml` and add the corresponding Vault volumes.
> Persistent local Vault in docker-compose - just like MySQL

- api/spotguide.go
- auth/events.go
- auth/user.go
- spotguide/spotguide.go
Backport github repo search by topic.
> Backport spotguide repo

- internal/providers/alibaba/objectstore.go
> status and status  message populated in the response

- api/security.go
- api/supported.go
- cmd/pipeline/main.go
- cmd/pipeline/migrate.go
- database/migrations/1543455447_create_notifications.down.sql
- database/migrations/1543455447_create_notifications.up.sql
- docs/openapi/internal.yaml
- docs/postman/e2e_test.postman_collection.json
- internal/auth/access.go
- internal/notification/log.go
- internal/notification/model.go
- internal/notification/notification.go
- internal/notification/notification_model.go
> add notification api

- cluster/hooks.go
Depends on https://github.com/banzaicloud/banzai-charts/pull/526
> Replace spot-termination-exporter with spot-termination-handler

- api/security.go
- cmd/pipeline/main.go
Add API endpoint to check whether security scan is enabled in ENV.
fixes: #1428
> Is security scan enabled globally API

- .banzaicloud/pipeline.yaml
- Gopkg.lock
- Gopkg.toml
- auth/authn.go
- auth/user.go
- client/SHA256SUMS
- client/api/openapi.yaml
- cmd/pipeline/main.go
- config/config.toml.example
- config/configuration.go
- config/database_cicd.go
- docker-compose.anchore.yml.dist
- docker-compose.override.yml.dist
- docker-compose.yml
- docs/developer.md
- docs/openapi/pipeline.yaml
- docs/postman/e2e_test.postman_collection.json
- internal/auth/middleware.go
- spotguide/cicdconfig.go
- spotguide/cicdrepoconfig_test.go
- spotguide/spotguide.go
- spotguide/spotguide_test.go
Database renaming will take place later on.
> drone -> CICD renaming

- auth/user.go
- cmd/pipeline/main.go
- config/config.toml.example
- config/configuration.go
- spotguide/spotguide.go
Reverts banzaicloud/pipeline#1485
```
runtime error: index out of range```
> [wip] Revert "Sync per organization & shared spotguides"

- Gopkg.lock
- Gopkg.toml
- cluster/hookfunctions.go
- cluster/hooks.go
- pkg/cluster/base.go
> cluster: install allow-all whitelist for image validation (0.8)

- config/config.toml.example
- docker-compose.override.yml.dist
- docker-compose.yml
Make sure to update your local environment:
- Update config.toml
- Update docker-compose.override.yml (`make -B docker-compose.override.yml`)
- Update cicd docker image: `docker pull banzaicloud/cicd:master`
- Change the pipeline basepath to `/pipeline`
> Add UI to docker-compose

- config/config.toml.example
- config/configuration.go
- spotguide/spotguide.go
> Support private spotguide source repositories

- api/cluster.go
- api/cluster_delete.go
- cluster/ec2_banzaicloud.go
- cluster/manager_delete.go
- cmd/pipeline/main.go
- internal/providers/banzaicloud/ec2_cluster_model.go
* use clustergetter to dig cluster from request
* added BeforeDelete hook to the EC2BanzaiCloudClusterModel to delete related records
* implemented detach (delete from database)
> implemented delete distro from database (detach)

- cluster/hookfunctions.go
- cluster/hooks.go
- cluster/hooks_ingress.go
- cluster/hooks_monitoring.go
- cluster/manager_create.go
* use `CommonCluster` type instead of `interface{}`
* review logging
> Posthook refactor

- pkg/providers/amazon/autoscaling/autoscaling.go
> Fix getting spot request for an ASG

- Gopkg.lock
- Gopkg.toml
| Related tickets | fixes #1631
We forked the original yaml library to add some patches instead of waiting for a new version. This PR updates the library import to use our fork.
**Note:** none of the above apply to this PR.
> Update yaml library

- pkg/secret/secret.go
- scripts/vault-config.yml
- secret/store.go
Fixes: https://github.com/banzaicloud/pipeline/issues/1415
> Generate distribution CA certificates with Vault

- cmd/pipeline/main.go
> feat: insert shared organization to DB on start if not exists

- api/cluster.go
- api/cluster_get.go
- cluster/acsk.go
- cluster/aks.go
- cluster/common.go
- cluster/dummy.go
- cluster/ec2_banzaicloud.go
- cluster/eks.go
- cluster/gke.go
- cluster/gke_node_pools.go
- cluster/kubernetes.go
- cluster/manager_common_updater.go
- cluster/oke.go
- database/migrations/1547727772_create_scale_options.down.sql
- database/migrations/1547727772_create_scale_options.up.sql
- internal/cluster/cluster_model.go
- internal/cluster/clusters.go
- model/cluster.go
- model/migrate.go
- pkg/cluster/base.go
> cluster: add possibility to save scale options

- Gopkg.lock
- Gopkg.toml
- api/common_stuff.go
- cluster/hooks.go
- docs/postman/e2e_test.postman_collection.json
- internal/ark/providers/azure/secret.go
- internal/providers/azure/objectstore.go
- pkg/providers/amazon/objectstore/objectstore.go
- pkg/providers/azure/objectstore/auth.go
- pkg/providers/azure/objectstore/objectstore.go
- pkg/providers/azure/objectstore/objectstore_test.go
- pkg/providers/azure/objectstore/resource_group.go
- pkg/providers/azure/objectstore/storage_account.go
- fixes #1502 
- remove github.com/Azure/azure-sdk-for-go/storage package (will be deprecated)
- refactor
> refactor azure objectstore

- secret/store.go
> distribution clusterUID scan fix

- internal/ark/api/cluster.go
- internal/ark/config.go
- internal/ark/deployments_svc.go
Enables RBAC for ARK on AKS as well
> ARK - Use RBAC for AKS as well

- api/domain.go
- cluster/hooks.go
- cluster/hooks_ingress.go
- cluster/hooks_monitoring.go
- cmd/pipeline/main.go
- dns/dns.go
- dns/externaldns.go
- dns/route53/route53.go
- internal/monitor/cluster_subscriber.go
| Related tickets | fixes #1666 
It makes generated domains and hostnames lower case to avoid issues with mixed case strings.
> Make generated hostnames lowercase

- cluster/ec2_banzaicloud.go
- cluster/gke.go
- database/migrations/1548428537_create_cluster_status_history_table.down.sql
- database/migrations/1548428537_create_cluster_status_history_table.up.sql
- internal/cluster/cluster_status_history_model.go
- internal/cluster/model.go
- model/cluster.go
- model/cluster_status_history_model.go
- scripts/check-header.sh
| Related tickets | fixes #1619
This PR adds tracking for cluster status changes.
> Add cluster status history

- internal/monitor/cluster_subscriber.go
It adds `cluster_id` and `org_id` to federated prometheus cluster scrape config as labels
Hollowtrees needs these information to scale the cluster when an instance termination alert arrives from Prometheus
> Add cluster_id and org_id to federated cluster monitor scrape config

- api/user.go
- auth/user.go
> Implement revoke github token for user

- api/cluster.go
- cluster/common.go
- pkg/cluster/base.go
> getNodePools: add ScaleEnabled flag

- docker-compose.anchore.yml.dist
Fix missing UI in docker-compose.anchore.yml.dist
> Fix anchore docker-compose override

- cluster/aks.go
This PR implements the UpdateNodePools method for Azure AKS and improves the UpdateCluster method to use a single request.
Because we can. I checked.
> WIP AKS cluster update enhancements

- cluster/autoscale.go
- cluster/eks.go
- cluster/manager_common_updater.go
- pkg/cluster/eks/action/actions.go
- templates/eks/amazon-eks-nodepool-cf.yaml
> EKS: add ASG tags from cf template, swith off Cluster Autoscaler if Hollowtrees is enabled

- api/ark/backupservice/status.go
- api/ark/common/common.go
- api/imagescan.go
- api/security.go
- internal/security/anchore.go
- pkg/common/common.go
| Related tickets | fixes #1703 
Checking security_scan flag before anchore requests
It makes error messages more exact.
> Check security_scan flag

- config/configuration.go
This fix allows PATCH HTTP requests in CORS scenarios.
We have PATCH verb API endpoints.
> Allow PATCH method in CORS

- pkg/providers/oracle/cluster/cluster.go
- pkg/providers/oracle/model/cluster.go
> Add nodepool name label after  create cluster request validation

- cmd/pipeline/main.go
- config/configuration.go
This is a hot-fix to allow setting listen address and port as well to metrics endpoint
> Hot-fix pipeline metrics port

- docker-compose.yml
This version uses the stable v2.15.0 released version of Dex.
> dex-shim:0.3.0

- Gopkg.lock
- internal/providers/alibaba/network.go
- internal/providers/network.go
VPC query API implementation for Alibaba Cloud.
Alibaba cloud was not yet supported. Now it is.
> implement VPC query service for Alibaba

- internal/monitor/spotmetrics.go
| New feature?    |no
| Related tickets | fixes #1740
Add context to spot request polling errors for easier error tracking.
> Add context to SR polling errors

- cluster/ec2_pke.go
Add missing arguments to PKE bs commands
> pke: update install commands

- docker-compose.yml
contains dex vs. virtual user fix
> update cicd to 0.8.2

- pkg/cluster/acsk/action/action_utils.go
| Related tickets | fixes #1749
> Fix: Graceful deletion of ACK cluster fails if ScalingGroup missing

- Gopkg.lock
- pkg/providers/azure/extensions.go
> fixed azure k8s validation

- docker-compose.yml
This PR removes restart always.
This sneaked back somehow.
> Remove restart always from docker-compose

- cluster/acsk.go
- pkg/cluster/acsk/action/action_create_nodepool.go
- pkg/cluster/acsk/action/action_delete_nodepool.go
- pkg/cluster/acsk/action/action_update_nodepool.go
- pkg/cluster/acsk/action/action_utils.go
- pkg/cluster/acsk/defaults.go
| Related tickets | fixes #1752
> Fix: ACK cluster creation fails with throttling error

- Dockerfile
- Dockerfile.debug
- Dockerfile.local
- Makefile
- cmd/pipeline/build.go
- cmd/pipeline/main.go
This PR includes a few fixes around building docker images as well as adds support for multiple build binaries.
> Improve docker setup, prepare for multiple binary support

- docs/postman/e2e_test.postman_collection.json
> postman: add Cluster Create with Scale option example

- pkg/cluster/base.go
- pkg/secret/secret.go
Valuer implementations for typed IDs.
Without them, the database serializer can't figure out how to serialize these simple types...
> Implement the Valuer interface for ID types

- cluster/manager_common_creator.go
- cmd/worker/main.go
- internal/cluster/clustersecret/clustersecretadapter/clusters.go
- internal/cluster/clustersecret/clustersecretadapter/store.go
- internal/cluster/clustersecret/store.go
- internal/cluster/clustersecret/store_test.go
- internal/providers/pke/pkeworkflow/aws.go
- internal/providers/pke/pkeworkflow/create_aws_roles_activity.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/generate_certificates_activity.go
- internal/providers/pke/pkeworkflow/pkeworkflowadapter/secret.go
This PR contains generic improvements to the PKE distribution workflows.
There are three main improvements in this PR:
- Introduced cluster level secret store
- Added additional parameters to the workflow input
- AWS steps are no longer depending on clusters directly, unless necessary (POC, will be finished in a subsequent PR)
After finishing the POC implementations, it's time to improve the code.
> Pkecadence refactor

- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
Fix worker CF resulting in rollback, due to assuming spot based instances incorrectly.
CloudFormation expects empty spot price in case of non spot based ASG.
> Fix spot price parameter

- helm/install.go
Remove NodeSelector from Helm deployment
> Remove Helm NodeSelector

- Makefile
Update vendor before build if needed, and add runall/run-worker targets to Makefile.
> Run vendor on demand

- api/npls.go
- cluster/nodelabels.go
- docs/postman/e2e_test.postman_collection.json
- pkg/cluster/base.go
> getNodePoolLabels: add reserved flag to labels

- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- templates/pke/master.cf.yaml
- templates/pke/vpc.cf.yaml
- templates/pke/worker.cf.yaml
| Related tickets | |
Amazon CF descriptions are corrected to reflect actual use.
CF had misleading description.
> PKE CF temaplate naming

- Dockerfile
- Dockerfile.debug
> Add PKE templates to dockerfiles

- Dockerfile
- Dockerfile.debug
- Dockerfile.local
Updates docker images to Alpine 3.9
> Upgrade to alpine 3.9

- cluster/gke.go
- cluster/gke_test.go
- secret/verify/google.go
> Fix json imports

- cluster/hookfunctions.go
- cluster/hooks.go
- pkg/cluster/base.go
Implement default storageclass post-hook. Default storageclass implemented on Amazon PKE. Further providers should be added later.
> Add storageclass posthook

- cmd/worker/main.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/create_elastic_ip_activity.go
- internal/providers/pke/pkeworkflow/create_vpc_activity.go
- internal/providers/pke/pkeworkflow/update_cluster_network.go
- internal/providers/pke/pkeworkflow/wait_for_cf_completion_activity.go
Improve cluster create workflow.
> Refactor PKE cluster create flow

- cluster/ec2_pke.go
- database/migrations/1551273183_add_pke_nodepools_autoscaling.down.sql
- database/migrations/1551273183_add_pke_nodepools_autoscaling.up.sql
- internal/providers/pke/nodepool.go
- internal/providers/pke/nodepool_provider_config_amazon.go
- internal/providers/pke/pkeworkflow/cluster.go
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/pkeworkflowadapter/cluster_manager.go
- internal/providers/pke/pkeworkflow/update_aws_pool_activity.go
- pkg/cluster/pke/types.go
- templates/pke/worker.cf.yaml
Support autoscaler and changing/loading the desired size of cluster.
> Pke nodepool count

- auth/user.go
- config/config.toml.dist
- config/configuration.go
- docs/developer.md
| Related tickets | fixes #1757
This PR removes the whitelist feature.
> Remove the whitelist feature

- api/hpa.go
- cluster/hooks.go
- config/configuration.go
- docs/postman/e2e_test.postman_collection.json
- go.mod
- go.sum
- pkg/hpa/hpa.go
- pkg/k8sutil/portforwarder.go
> use kube-metrics-adapter for custom metrics

- cluster/manager_delete.go
- helm/helm.go
Cherry-pick: https://github.com/banzaicloud/pipeline/commit/9596965400a6f7a06a0b707b38729725ca0b287a
> Properly delete pending deployments as well (#1825)

- cmd/pipeline/main.go
- config/config.toml.dist
- config/configuration.go
> Fix metrics middleware order and metrics address

- pkg/providers/oracle/model/cluster.go
> oke: fix missing node pool labels

- cluster/autoscale.go
Deploy cluster autoscaler on PKE on AWS if there is an autoscaled worker pool.
> pke: deploy cluster-autoscaler if needed

- secret/store.go
Adds root CA to intermediate CAs.
Certificate verification chain is broken without the actual root CA.
> Fix PKE missing root CA

- cmd/pipelinectl/main.go
- cmd/pipelinectl/vars.go
This PR allows turning root CA verification off.
> Fix pipelinectl CA verification

- auth/migrate.go
- auth/user.go
- database/migrations/1551727551_drop_whitelisted_auth_identities_table.down.sql
- database/migrations/1551727551_drop_whitelisted_auth_identities_table.up.sql
| Related tickets | fixes #1809
This PR removes unused code and drops unused table.
> Remove unused whitelisted identity table

- cluster/ec2_pke.go
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/create_master_activity.go
Fixes for certificate handling.
> Bump PKE version

- secret/store.go
| Bug fix?        | enhancement
For ease of debugability, PKI secret engines are now mounted under `clusters/orgID/clusterID/pki`.
> pke: change vault pki paths to orgID/clusterID

- cluster/gke.go
Replace the explicit dependency on GORM DB in GKE cluster with a repository interface. It also removes some unnecessary double indirections (passing `&model` where `model` is already `*GKEClusterModel`).
On the way to (easier) testability explicit dependencies should be eliminated.
> Replace explicit GORM DB dependency with repository interface in GKE cluster

- api/npls.go
- cluster/hooks_nodelabels.go
- cluster/manager_common_updater.go
- cluster/nodelabels.go
- pkg/cluster/base.go
This PR simplifies the node pool label installation code. It is the first part of an effort to eliminate shared instance dependency.
> Npls cadence

- cluster/acsk.go
- cluster/aks.go
- cluster/common.go
- cluster/dummy.go
- cluster/ec2_pke.go
- cluster/eks.go
- cluster/gke.go
- cluster/hookfunctions.go
- cluster/hooks.go
- cluster/kubernetes.go
- cluster/manager_common_creator.go
- cluster/manager_common_nodepool_updater.go
- cluster/manager_common_updater.go
- cluster/manager_create.go
- cluster/manager_delete.go
- cluster/manager_update.go
- cluster/oke.go
- internal/providers/pke/pkeworkflow/cluster.go
- internal/providers/pke/pkeworkflow/update_cluster_status_activity.go
Reverts banzaicloud/pipeline#1860
Breaks PKE cluster creation.
> Revert "Set cluster status"

- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/create_master_activity.go
Use the correct pke tool version.
> 0.14: bump pketool

- api/cluster.go
- api/cluster_create.go
- api/cluster_posthook.go
- cluster/cluster_workflow.go
- cluster/hook_workflow.go
- cluster/hookfunctions.go
- cluster/hooks.go
- cluster/hooks_nodelabels.go
- cluster/manager_create.go
- cmd/pipeline/main.go
- cmd/worker/main.go
This PR moves PostHook execution to cadence workflows.
This PR supersedes #1843
> Posthook workflow

- templates/pke/global.cf.yaml
> 0.14 fix pke cf roles

- internal/providers/pke/pkeworkflow/create_cluster.go
> pke: bump pkeVersion

- model/cluster.go
| Related tickets | related #1878
Quick fix for cluster status history.
> Fix cluster status history

- cluster/ec2_pke.go
- cluster/gke.go
> Fix cluster status history tracking for GKE and PKE

- cluster/ec2_pke.go
- cluster/gke.go
Reverts banzaicloud/pipeline#1881
> Revert "Fix cluster status history tracking for GKE and PKE"

- docs/developer.md
Update developer docs to reflect changes introduced by Cadence and PKE.
> developer.md: update with worker/pke details

- cluster/manager_common_creator.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/create_vpc_activity.go
- pkg/cluster/pke/types.go
This PR fixes existing VPC support on PKE.
> 0.14.x: Fix existing VPC support in PKE

- cluster/manager_common_creator.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/create_vpc_activity.go
- pkg/cluster/pke/types.go
This PR fixes existing VPC support on PKE.
> Fix existing VPC support in PKE

- api/cluster_get.go
| Related tickets | fixes #1827 
Check secret before check cluster status in case of cluster details
> Add secret information to cluster details response in case of not ready cluster

- cluster/acsk.go
- cluster/acsk_test.go
| Related tickets | fixes #1890 
Set `region` field with region information instead of zone
> Set region field with region information in case of Alibaba ACK

- internal/providers/pke/pkeworkflow/create_cluster.go
Upgrading PKE cluster version to 0.2.0
> Upgrade PKE tool version

- .vscode/tasks.json
Updated VSCode tasks that call the new `run*` make targets.
> VSCode tasks updates

- api/cluster.go
- api/npls.go
- cluster/manager_common_updater.go
- cluster/manager_create.go
- cluster/nodelabels.go
- internal/cloudinfo/machine_types.go
- Remove location from cache key, since there's no difference in instance types
- Add some log & locking around instancetype map
> cloudinfo: additional logging & locking

- api/ark/backupservice/enable.go
- api/ark/buckets/create.go
- api/ark/common/common.go
- cluster/hooks.go
- internal/providers/objectstore.go
> get location for bucket(s) in case of backup enable/create

- internal/cluster/clusters.go
Move the cluster query filter generation out of the common method and into the specialization methods.
The current implementation uses too much type checking.
> Simplify cluster search implementation

- templates/pke/master.cf.yaml
https://github.com/banzaicloud/pipeline/pull/1911
> remove AvailabilityZone parameter from instance definition

- auth/gitlab.go
> gitlabURL fix

- internal/providers/pke/pkeworkflow/create_cluster.go
Use latest pke tool version to fix pke boots
> 0.15 pke bump

- cluster/eks.go
- cluster/manager_common_creator.go
| API breaks?     | n
| Related tickets | related #1878
Fixes cluster status code.
> Cluster status fixes round 2

- spotguide/scm/github.go
| Related tickets | #1916 
Fix GitHub repo init order.
The GitHub repository has to be initialized with a file first (a specific GitHub API call) before additional, content can be added, the order of this has been exchanged in the previous PR #1916.
> fix github spotguide init order

- templates/pke/master.cf.yaml
- templates/pke/vpc.cf.yaml
- templates/pke/worker.cf.yaml
Don't associate public ip to workers in custom VPCs.
Don't allow external SSH connection to nodes.
> No public ip no ssh

- templates/pke/master.cf.yaml
- templates/pke/vpc.cf.yaml
- templates/pke/worker.cf.yaml
> 0.16 no public ip no ssh

- docker-compose.yml
Related #1940
Fixes Cadence config path in the development environment.
> Fix cadence config

- internal/providers/pke/pkeworkflow/create_cluster.go
Updated default PKE base machine images.
> Update default PKE images

- api/cluster/pke_azure.go
> Add squash json tag

- etc/docker/uiproxy/nginx.conf
> Fix UI proxy

- cluster/nodelabels.go
Formats attribute key & value coming from Cloud Info to according to K8s label key/value regexp.
> format node pool labels from cloud info

- cluster/autoscale.go
- internal/ark/api/cluster.go
- internal/ark/deployments_svc.go
- internal/providers/azure/pke/adapter/commoncluster/cluster.go
| New feature?   | no 
Fixes a wrong type assertion which could cause panic.
> Fix ARK type assertion

- internal/providers/azure/pke/workflow/delete_vmss_activity.go
In case of cluster delete the VMSSes of the cluster should be deleted regardless of their provisioning state.
> Disregard provisioning status when deleting VMSS

- api/cluster_get.go
- internal/providers/azure/pke/workflow/create_cluster.go
- internal/providers/azure/pke/workflow/delete_cluster.go
> Add TaskStartToCloseTimeout

- internal/cluster/workflow/delete_k8s_resources.go
Warn on namespace delete error instead of breaking flow
> Warn on namespace delete error instead of breaking flow

- pkg/cluster/base.go
Rephrase base status messages of clusters.
> cluster: rephrase base cluster status messages

- internal/cluster/kubernetes/namespace_resources_deleter.go
Wait for deleted PVCs to disappear during cluster deletion.
This may help to prevent leaking cloud resources.
> cluster: wait for deletion of PVCs

- cluster/hooks.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/workflow/create_infra.go
> Set taint on headnode through VMSS user datascript

- internal/providers/azure/pke/workflow/delete_lb_activity.go
- internal/providers/azure/pke/workflow/delete_nsg_activity.go
- internal/providers/azure/pke/workflow/delete_public_ip_activity.go
- internal/providers/azure/pke/workflow/delete_route_table_activity.go
- internal/providers/azure/pke/workflow/delete_vnet_activity.go
When deleting the Azure infrastructure of a PKE cluster there is no need to stop the deletion process if an infrastructure component is in updating or provisioning state. We can safely invoke the delete on the infrastructure component as Azure will take care of it.
> PKE: delete Azure infra components regardless of their provisioning state

- internal/istio/istiofeature/reconcile_istio_cr.go
PKE needs `Always` image pull policy
> Use always image pull policy

- api/clustergroup/deployment/create.go
- api/clustergroup/deployment/delete.go
- api/clustergroup/deployment/sync.go
- api/clustergroup/deployment/upgrade.go
- internal/clustergroup/deployment/deployment.go
- internal/clustergroup/deployment/manager.go
- internal/clustergroup/deployment/repository.go
Return error code 207 in case of partial success of deployment operations.
> cgroup deployment: return error code when there are failing operations

- auth/authn.go
- config/config.toml.dist
- config/configuration.go
- go.mod
- go.sum
> dex: support for insecure tls

- go.mod
- go.sum
| Related tickets | partially #2043 
This version includes a global http client, OIDC access is now configured centrally.
> bump auth version to v0.1.3

- cmd/pipeline/main.go
- spotguide/spotguide.go
- spotguide/spotguide_test.go
This PR adds support for spotguides without external DNS.
> Make spotguides work without external DNS

- internal/providers/azure/pke/workflow/create_vmss_activity.go
- internal/providers/azure/pke/workflow/create_vmss_activity_test.go
> azure/pke: disable Overprovision on vmsss

- auth/user.go
- config/configuration.go
> cicd: support insecure tls calls

- cluster/hooks_logging.go
| Related tickets | related #2048
Fixes S3 output value structure.
> Fix s3 logging output value structure

- internal/providers/azure/pke/cluster.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/driver/commoncluster/cluster.go
Remove unused `Labels` field.
Simplify code, do not confuse developers with unused fields.
> Remove unused Labels field

- api/cluster.go
- api/cluster_create.go
- api/cluster_update.go
- cluster/ec2_pke.go
- cluster/manager_common_creator.go
- cluster/manager_common_updater.go
- cluster/manager_create.go
- cmd/pipeline/main.go
- config/config.toml.dist
- config/configuration.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/driver/cluster_updater.go
- internal/providers/azure/pke/driver/common.go
- internal/providers/pke/pkeworkflow/cluster.go
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/create_master_activity.go
- internal/providers/pke/pkeworkflow/pkeworkflowadapter/cluster_manager.go
- internal/providers/pke/pkeworkflow/update_cluster.go
Support deploying PKE cluster with insecure Pipeline API https endpoint.
> Support deploying PKE cluster with insecure Pipeline

- cluster/autoscale.go
- cluster/hooks.go
- config/config.toml.dist
- config/configuration.go
Install configurable version of cluster-autoscaler, hpa-operator charts.
> add cluster autoscaler & hpa operator chart version config

- api/spotguide.go
| Bug fix?        |yes|
| New feature?    |no|
| API breaks?     |no|
| Deprecations?   |no|
Remove unnecessary log in front of errorHandler
> Remove unnecessary log in front of errorHandler

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/driver/cluster_updater.go
- internal/providers/azure/pke/driver/common.go
- internal/providers/azure/pke/driver/preparers.go
- internal/providers/azure/pke/workflow/azure.go
- internal/providers/azure/pke/workflow/collect_update_cluster_providers_activity.go
- internal/providers/azure/pke/workflow/create_infra.go
- internal/providers/azure/pke/workflow/create_route_table_activity.go
- internal/providers/azure/pke/workflow/create_vnet_activity.go
- internal/providers/azure/pke/workflow/delete_vnet_activity.go
Advanced network implementation for Azure PKE.
Feature parity.
> Azure PKE advanced network

- internal/providers/azure/pke/workflow/create_vmss_activity.go
- internal/providers/azure/pke/workflow/create_vmss_activity_test.go
Enable accelerated networking for VMs that support it.
Some Azure VMs support accelerated networking provides improved  network performance in certain conditions: https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli
> Pke azure accelerated network

- api/cluster.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/azure/pke/driver/cluster_updater.go
- internal/providers/azure/pke/workflow/update_cluster.go
Install labels to new node pools created when updating a cluster.
> Label new node pools on cluster update

- Dockerfile
- Dockerfile.debug
- Dockerfile.local
> Add bash as default shell to dockerfile

- Makefile
On linux we need to manually create volume directories, otherwise Docker creates them with root owner and the container won't be able to write it.
> Fix linux setup script

- internal/providers/azure/pke/workflow/azure.go
- internal/providers/azure/pke/workflow/create_lb_activity.go
- internal/providers/azure/pke/workflow/create_nsg_activity.go
- internal/providers/azure/pke/workflow/create_public_ip_activity.go
- internal/providers/azure/pke/workflow/create_route_table_activity.go
- internal/providers/azure/pke/workflow/create_vmss_activity.go
- internal/providers/azure/pke/workflow/create_vnet_activity.go
Use `Tag` struct instead of string pairs.
Make working with tags easier.
> Azure PKE tags refactor

- config/cadence.yml
- database/docker-init-mysql.sql
- database/docker-init-postgres.sql
- docker-compose.yml
Upgrade Cadence to the latest stable version in the development environment.
1. Execute the following in your local MySQL server (or reset the local environment):
```sql
CREATE DATABASE IF NOT EXISTS cadence;
GRANT ALL PRIVILEGES ON cadence.* TO 'sparky'@'%';
CREATE DATABASE IF NOT EXISTS cadence_visibility;
GRANT ALL PRIVILEGES ON cadence_visibility.* TO 'sparky'@'%';
```
2. Restart your Docker Compose environment:
`docker-compose up -d`
> Upgrade cadence

- internal/cluster/kubernetes/user_namespace_deleter.go
> Fix: wrong orig error is wrapped into the returned error

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/pke/pkeworkflow/create_cluster.go
Use PKE tool version 0.4.9.
Use PKE tool version 0.4.9 as that includes a fix for multi-master clusters.
> Update the used PKE tool version to 0.4.9

- cluster/aks.go
- cluster/ec2_pke.go
- cluster/gke.go
| Bug fix?        |yes|
| New feature?    |no|
| API breaks?     |no|
| Deprecations?   |no|
This PR comments out logs which floods the output and cause unreadable pipeline logs. When logging is refactored this can be un commented.
> Comment out flodding logs while logging refactored

- cluster/ec2_pke.go
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/delete_aws_pool_activity.go
- internal/providers/pke/pkeworkflow/update_cluster.go
| Related tickets | fixes #2103
> Fix: add node pool to PKE on AWS

- internal/dashboard/api.go
Return cluster in any state with partial response code.
> dashboardAPI: return clusters regardless of their state

- cluster/kubernetes.go
- cluster/manager_delete.go
- cmd/pipeline/main.go
- cmd/worker/main.go
- helm/helm.go
- internal/cluster/kubernetes/user_namespace_deleter.go
- internal/cluster/workflow/delete_helm_deployments_activity.go
- internal/cluster/workflow/delete_user_namespaces_activity.go
- internal/istio/istiofeature/reconcile_mesh_namespace.go
- internal/istio/istiofeature/reconcile_namespace.go
- internal/istio/istiofeature/reconcile_remoteistios.go
- pkg/k8sutil/namespace.go
* determine if RBAC is enabled on the imported cluster
* when deleting imported cluster remove only resources from namespaces created by Pipeline
> Cluster import enhancements

- internal/federation/reconcile_crb.go
> fedv2: fix namespace for clusterrolebinding

- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/pke/pkeworkflow/delete_cluster.go
- internal/providers/pke/pkeworkflow/update_cluster.go
Execute node pool creating activities in parallel when creating a cluster. Similarly, execute node pool create/update/delete activities in parallel when updating a cluster.
Node pool creation/deletion/updating activities can be executed in parallel to speed up the workflow.
> PKE on AWS: create node pools in parallel when creating cluster

- pkg/secret/secret.go
> add CloudFlare and DigitalOcean

- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/HelmInitRequest.md
- client/model_helm_init_request.go
- cluster/hooks.go
- cluster/hooks_tiller.go
- config/config.toml.dist
- config/configuration.go
- docs/openapi/pipeline.yaml
- helm/install.go
- pkg/helm/helm.go
> Update helm version

- Dockerfile
- Dockerfile.debug
- Dockerfile.local
> [Backport] Add nsswitch.conf to Docker image

- api/cluster.go
- cluster/kubernetes.go
- config/config.toml.dist
- pkg/k8sclient/clean.go
- pkg/k8sclient/client.go
- pkg/k8sclient/config.go
- secret/verify/common.go
- secret/verify/kubernetes.go
* validate KubeConfig through checking API server version
* sanitize KubeConfig before being used
* support whether to allow or not connecting to local API server through Pipeline
> Kubeconf validation patch

- api/cluster.go
- config/config.toml.dist
- pkg/k8sclient/clean.go
- pkg/k8sclient/client.go
- pkg/k8sclient/config.go
Sanitize KubeConfig before being used.
> Kubeconfig validation

- cluster/hooks.go
- config/configuration.go
- internal/clusterfeature/clusterfeaturedriver/endpoints.go
- internal/clusterfeature/clusterfeaturedriver/endpoints_test.go
- internal/clusterfeature/clusterfeaturedriver/transport_http.go
- internal/clusterfeature/clusterfeaturedriver/transport_http_test.go
- internal/clusterfeature/features/dns/manager.go
- internal/clusterfeature/features/dns/spec.go
- internal/clusterfeature/service.go
- internal/clusterfeature/service_test.go
* http status codes aligned with problems status code
* made domain posthook disableable
* list of features decorated with details
> Dns feature and feature framework amendments

- internal/clusterfeature/features/dns/manager.go
* response json formatting related fix
> camelcase dns feature output fields

- cmd/worker/config.go
> Fix worker config in local env

- Dockerfile
| Related tickets | fixes #2171, fixes #2183 
Install AWS IAM Authenticator from prebuilt binary instead of source.
Since last we checked the state of the IAM Authenticator library,
it received some updates and prebuilt binaries.
We switched to scratch containers a while ago, and our CGO-enabled IAM Authenticator build did not work on it.
~~- [-] Implementation tested (with at least one cloud provider)~~
> Install IAM Authenticator from prebuilt binary

- Dockerfile
Fix IAM authenticator executable
> Fix iam authenticator executable

- internal/providers/pke/pkeworkflow/create_cluster.go
Add nil reference check to nodepool creation
Cluster creation failed while creating nodepools.
> Fix PKE cluster creation failure

- internal/clustergroup/repository.go
Fix Postgres error when creating a cluster group.
> clustergroup feature: use latest error handling, fix postgres error

- cmd/pipeline/config.go
- cmd/pipeline/main.go
- cmd/worker/main.go
- config/configuration.go
- internal/platform/log/k8s_logger.go
This PR replaces the global API machinery error handler, which is a klog instance.
It also contains some general improvements for the logger in pipeline's main.
Klog tries to write logs to file and ingeniously exits when that fails. When running Pipeline in a scratch container, this is quite an issue.
> Override klog

- docs/postman/e2e_test.postman_collection.json
Add postman collection for feature actions
There's no feature endpoints in the current postman collection
> Add postman collection for feature actions

- cluster/hooks.go
Retry the creation of  AllowAll security whitelist CR if it fails as on the first attempt it may fail due to the `whitelists.security.banzaicloud.com` CRD not being created by in time by API server.
It may take some time for API server to create the `whitelists.security.banzaicloud.com` CRD thus the creation of the AllowAll CR of type `whitelists.security.banzaicloud.com` may fail at the first and succeed at the second attempt.
> Retry the creation of AllowAll whiltelist CR in case of failure

- config/configuration.go
- internal/federation/reconcile_controller.go
> fedv2: fix tag and image repo config properties

- pkg/cluster/ack/action/action_utils.go
| Related tickets | fixes #2214 
Add UUID to Alibaba clusters
> Add UUID to Alibaba clusters

- docs/developer.md
Supplementing MySQL UI connection info in the developer doc.
The default Server/Database values aren't good.
> Fix MySQL UI connection info

- cluster/hooks.go
> [Backport] 2220

- client/SHA256SUMS
- client/api/openapi.yaml
- client/docs/CreateClusterRequest.md
- client/model_create_cluster_request.go
- docs/openapi/pipeline.yaml
> move back ScaleOptions to root level of CreateClustrerRequest

- internal/providers/azure/pke/workflow/create_infra.go
- internal/providers/azure/pke/workflow/delete_infra.go
- internal/providers/azure/pke/workflow/update_cluster.go
Gather errors from futures, combine them, return if necessary.
Until this point only the first error was returned from a list of possibly failed activities.
> Gather all errors from futures in Azure PKE workflows

- cmd/worker/config.go
> Fix worker database config

- Makefile
- go.mod
- go.sum
| Related tickets | related qor/auth#12
Downgrade GORM because it doesn't work with qor auth.
> Revert gorm update

- pkg/secret/secret.go
- secret/store.go
> secret: change how we decide TLS secret generation

- internal/audit/middleware.go
> audit: change JSON binding errors to http 400 and return error as well

- .circleci/config.yml
> circleci: enable docker layer cache

- pkg/cluster/eks/action/actions.go
During EKS cluster creation flow when checking the tags of ELBs to see if they belong to the cluster being deleted do not query more than 20 ELBs at once.
The describe ELBs tags API call doesn't allow more than 20 ELBs to be queried at once: https://docs.aws.amazon.com/elasticloadbalancing/2012-06-01/APIReference/API_DescribeTags.html
> Describe ELB tags in chunks of 20 ELBs

- api/spotguide.go
- auth/authn.go
- auth/user.go
- cmd/pipeline/main.go
- config/config.toml.dist
- config/configuration.go
| Related tickets | fixes #2284 
CICD is not required in every installation, so this PR makes int configurable, end users can enable it or disable it `config.toml`.
> cicd: make it optional

- auth/oidc.go
| Related tickets | https://github.com/banzaicloud/banzai-cli/pull/135
Handles the refresh token sent by the CLI in https://github.com/banzaicloud/banzai-cli/pull/135
Otherwise, we can't save the user refresh token.
> oidc: handle refresh token in cli login flow

- auth/authadapter/organization_store.go
- auth/authadapter/organization_store_test.go
- auth/authadapter/organization_test.go
- auth/interfaces.go
- auth/oidc.go
- auth/organization.go
- auth/organization_test.go
- auth/role.go
- auth/role_test.go
- auth/user.go
- cmd/pipeline/config.go
- cmd/pipeline/main.go
- config/config.toml.dist
| Related tickets | fixes #2278
Binds OIDC groups to Pipeline roles.
> Role binding

- cluster/common_test.go
- go.mod
- go.sum
- pkg/cluster/eks/action/actions.go
- pkg/cluster/eks/defaults.go
> Add support for k8s 1.14 to EKS

- cmd/worker/main.go
- go.mod
- internal/clusterfeature/features/kubernetes.go
- internal/clusterfeature/features/vault/client.go
- internal/clusterfeature/features/vault/common_test.go
- internal/clusterfeature/features/vault/manager_test.go
- internal/clusterfeature/features/vault/operator.go
- internal/clusterfeature/features/vault/operator_test.go
- internal/clusterfeature/features/vault/spec.go
- internal/kubernetes/service.go
| Related tickets | #2276 
- introduced KubernetesService for handling Kubernetes primitives from Cluster Features
- add SA JWT configuration and provisioning to Vault Feature
- fixed some bugs
- Added some TODOs to places where is still some work left
> [vault-cluster-feature] Configure Vault k8s auth with JWT and some fixes

- cmd/pipeline/main.go
> spotguides: path fix

- auth/migrate.go
- database/migrations/mysql/1568644399_drop_github_id_column_from_organizations_table.down.sql
- database/migrations/mysql/1568644399_drop_github_id_column_from_organizations_table.up.sql
- database/migrations/postgres/1568644399_drop_github_id_column_from_organizations_table.down.sql
- database/migrations/postgres/1568644399_drop_github_id_column_from_organizations_table.up.sql
Removes an unused column from the database.
> Drop github ID column from organizations table

- cmd/pipeline/main.go
> Remove deprecated token endpoint

- docker-compose.override.yml.dist
- docker-compose.yml
> docker-compose: make cicd optional

- cluster/ec2_pke.go
- internal/providers/pke/pkeworkflow/update_aws_pool_activity.go
Persist to the database the new node pool node count when updating a node pool.
> PKE on AWS - node count not persisted after nodepool resize

- cluster/eks.go
- pkg/cluster/eks/action/actions.go
- pkg/cluster/eks/action/network.go
- pkg/providers/amazon/ec2/network.go
> [Backport] 2320

- internal/clusterfeature/features/vault/manager_test.go
The tests have failed in the previous PR, and somehow it wasn't reported back to the status check.
See: #2343
> fix vault feature tests

- internal/clusterfeature/clusterfeatureadapter/gorm_feature_repository.go
| Related tickets | fixes #2349 
> postgres: fix where field clauses

- internal/app/pipeline/auth/token/mock_Store_test.go
- internal/app/pipeline/auth/token/token.go
- internal/app/pipeline/auth/token/token_test.go
- internal/app/pipeline/auth/token/tokenadapter/store.go
- internal/app/pipeline/auth/token/tokenadapter/store_test.go
> Fix token store

- Makefile
> Add lint fixer

- internal/app/frontend/issue/issuedriver/endpoint_test.go
- internal/app/frontend/issue/issuedriver/transport_http_test.go
- internal/app/frontend/notification/notificationdriver/endpoint_test.go
- internal/app/frontend/notification/notificationdriver/transport_http_test.go
- internal/app/pipeline/auth/token/tokendriver/endpoint_test.go
- internal/app/pipeline/auth/token/tokendriver/transport_http_test.go
> Improve kit tests

- internal/providers/azure/pke/driver/cluster_updater.go
Do not try to create and thus update already existing subnets because that assigns the default route table to them.
When the default route table is assigned to already existing subnets, the deletion of the route table will fail because the subnets have not been deleted (or disassociated from the route table) because we do not delete preexisting subnets.
> Fix Azure PKE route table deletion failure

- Makefile
- auth/authz_test.go
- auth/organization.go
- auth/organization_test.go
- auth/user_test.go
- internal/app/frontend/issue/issue.go
- internal/app/frontend/issue/issue_test.go
- internal/app/frontend/notification/notification.go
- internal/app/frontend/notification/notification_test.go
- internal/app/pipeline/auth/token/token.go
- internal/app/pipeline/auth/token/token_test.go
- internal/app/pipeline/auth/token/tokendriver/middleware_test.go
- internal/clusterfeature/clusterfeatureadapter/cluster_service.go
- internal/clusterfeature/clusterfeaturedriver/endpoints_test.go
- internal/clusterfeature/features/helm.go
- internal/clusterfeature/interface.go
- internal/common/commonadapter/secret_test.go
- pkg/auth/token_test.go
> Improve code generation

- internal/providers/pke/ec2_cluster_model.go
- internal/providers/pke/model.go
> add dex_enabled column deletion support with a legacy model

- .circleci/config.yml
> circleci: pin mysql version to 5.7.27

- docker-compose.override.yml.dist
- internal/clusterfeature/features/securityscan/operator.go
This PR fixes version of the anchore-policy-validator chart.
> Bump anchore-policy-validator version to the latest

- .gen/pipeline/README.md
- .gen/pipeline/SHA256SUMS
- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_create_eks_properties_eks.go
- apis/pipeline/pipeline.yaml
- cluster/eks.go
- database/migrations/mysql/1571398112_add_eks_logtypes.down.sql
- database/migrations/mysql/1571398112_add_eks_logtypes.up.sql
- database/migrations/postgres/1571398112_add_eks_logtypes.down.sql
- database/migrations/postgres/1571398112_add_eks_logtypes.up.sql
- model/cluster.go
- pkg/cluster/eks/action/actions.go
- pkg/cluster/eks/action/cluster.go
- pkg/cluster/eks/eks.go
https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
> EKS: support master log types

- api/anchore_proxy.go
> Remove unnecessary logs from the anchore proxy

- cmd/pipeline/capabilities.go
- cmd/pipeline/config.go
- cmd/pipeline/main.go
> Rename monitor to monitoring

- .circleci/config.yml
- charts/pipeline/.helmignore
- charts/pipeline/Chart.yaml
- charts/pipeline/README.md
- charts/pipeline/bootstrap/amazon_k8s_ubuntu_16.04_master_pipeline.sh
- charts/pipeline/bootstrap/amazon_k8s_ubuntu_16.04_node_pipeline.sh
- charts/pipeline/bootstrap/weave.yml
- charts/pipeline/requirements.yaml
- charts/pipeline/templates/_helpers.tpl
- charts/pipeline/templates/alertmanager-rules.yaml
- charts/pipeline/templates/configmap.yaml
- charts/pipeline/templates/deployment-worker.yaml
- charts/pipeline/templates/deployment.yaml
- charts/pipeline/templates/ingress.yaml
- charts/pipeline/templates/prometheus-service-monitor.yaml
- charts/pipeline/templates/rbac.yaml
- charts/pipeline/templates/secret-ssh.yaml
- charts/pipeline/templates/secrets.yaml
- charts/pipeline/templates/service.yaml
- charts/pipeline/templates/statestore-pvc.yaml
- charts/pipeline/values.yaml
> Relocate pipeline chart

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_create_eks_properties_eks.go
- apis/pipeline/pipeline.yaml
- cluster/eks.go
- database/migrations/mysql/1571746685_add_eks_api_server_access_points.dow.sql
- database/migrations/mysql/1571746685_add_eks_api_server_access_points.up.sql
- database/migrations/postgres/1571746685_add_eks_api_server_access_points.dow.sql
- database/migrations/postgres/1571746685_add_eks_api_server_access_points.up.sql
- model/cluster.go
- pkg/cluster/eks/action/actions.go
- pkg/cluster/eks/action/vpcconfigrequest.go
- pkg/cluster/eks/eks.go
> EKS: APIServerAccessPoints support

- cmd/pipeline/main.go
- internal/app/frontend/app.go
> Improve router

- etc/manifest.yaml
Add some basic roles and rolebindings as initial manifest.
> Add k8s roles and bindings

- api/security.go
- cmd/pipeline/main.go
- internal/security/anchore_service.go
- internal/security/resource_service.go
| API breaks?     |yes
lightweight pr: add errorHandler to better track failures, remove superfluous debug messages from error blocks
code got cleaner, errors handled/ logged consistently
> improvements to the security scan handler component 

- internal/providers/azure/pke/driver/cluster_updater.go
- internal/providers/azure/pke/workflow/update_vmss_activity.go
> [Backport] 2431

- database/migrations/mysql/1572393884_drop_servicemesh_column_from_clusters_table.down.sql
- database/migrations/mysql/1572393884_drop_servicemesh_column_from_clusters_table.up.sql
- database/migrations/postgres/1572393884_drop_servicemesh_column_from_clusters_table.down.sql
- database/migrations/postgres/1572393884_drop_servicemesh_column_from_clusters_table.up.sql
- internal/cluster/model.go
- model/migrate.go
> Drop service mesh column

- cmd/pipeline/main.go
- internal/app/frontend/app.go
> Remove compat frontend routes

- charts/pipeline/values.yaml
- cluster/common.go
- cluster/hooks.go
- cluster/hooks_tiller.go
- cmd/pipeline/main.go
- cmd/worker/main.go
- config/config.toml.dist
- config/configuration.go
- helm/install.go
- internal/global/config.go
> Helm config

- .banzaicloud/pipeline.yaml
- .circleci/config.yml
- .gitignore
- Makefile
- cmd/pipeline/config_test.go
- cmd/worker/config_test.go
- config/config.yaml.dist
- docs/developer.md
- docs/migrations.md
- spotguide/cicdrepoconfig_test.go
Converts toml config to yaml
We use yaml everywhere else, TOML was the reference configuration.
> Convert configuration to yaml

- config/ui/feature-set.json.dist
- docker-compose.yml
> Upgrade UI

- cmd/worker/main.go
- config/config.toml.dist
- config/config.yaml.dist
- config/configuration.go
- internal/cluster/endpoints/common.go
- internal/cluster/endpoints/endpoints.go
- internal/clusterfeature/features/kubernetes.go
- internal/clusterfeature/features/monitoring/common.go
- internal/clusterfeature/features/monitoring/common_test.go
- internal/clusterfeature/features/monitoring/error.go
- internal/clusterfeature/features/monitoring/manager.go
- internal/clusterfeature/features/monitoring/manager_test.go
- internal/clusterfeature/features/monitoring/operator.go
- internal/clusterfeature/features/monitoring/operator_secret.go
- internal/clusterfeature/features/monitoring/operator_test.go
- internal/clusterfeature/features/monitoring/output.go
- internal/clusterfeature/features/monitoring/output_alertmanager.go
- internal/clusterfeature/features/monitoring/output_grafana.go
- internal/clusterfeature/features/monitoring/output_prometheus.go
- internal/clusterfeature/features/monitoring/output_pushgateway.go
- internal/clusterfeature/features/monitoring/secret_alertmanager.go
- internal/clusterfeature/features/monitoring/secret_base.go
- internal/clusterfeature/features/monitoring/secret_prometheus.go
- internal/clusterfeature/features/monitoring/secret_pushgateway.go
- internal/clusterfeature/features/monitoring/spec.go
- internal/clusterfeature/features/monitoring/values.go
- internal/clusterfeature/features/vault/common_test.go
- internal/kubernetes/service.go
Support new payload of the feature
> Monitoring feature improvement

- .gen/pipeline/api/openapi.yaml
- apis/pipeline/pipeline.yaml
Add capabilities to the openAPI specification
> Cap openapi

- cmd/pipeline/config.go
- cmd/pipeline/main.go
- cmd/worker/config.go
- cmd/worker/main.go
- config/config.yaml.dist
- config/configuration.go
- internal/clusterfeature/features/monitoring/config.go
- internal/clusterfeature/features/monitoring/manager.go
- internal/clusterfeature/features/monitoring/manager_test.go
- internal/clusterfeature/features/monitoring/operator.go
- internal/clusterfeature/features/monitoring/operator_secret.go
- internal/clusterfeature/features/monitoring/operator_test.go
- internal/cmd/config.go
> Add monitoring config

- cluster/eks.go
> Fix: adding new node pools to existing EKS cluster fails

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_node_pool_status.go
- .gen/pipeline/pipeline/model_node_pool_status_amazon.go
- apis/pipeline/pipeline.yaml
Client apps interacting with Pipeline using API client generated from the Open API descriptor are required to refresh the generated API client.
> Fix spot price field name of NodePoolStatusAmazon in openapi descriptor

- config/config.yaml.dist
- config/configuration.go
> Fix logging operator default config

- internal/cmd/config.go
> Fix security scan default value

- internal/clusterfeature/features/monitoring/operator.go
Add grafana to the values in case of disabled state too
To avoid deploy errors
> [Monitoring] Fix Grafana values

- internal/app/pipeline/cap/capdriver/transport_http.go
Add content type header to the get capabilities response
> add content type to capabilities response header

- templates/eks/amazon-eks-iam-cf.yaml
> Fix: EKS create cluster ingores user provided node instance role id

- cluster/eks.go
- templates/eks/amazon-eks-iam-cf.yaml
> Backport EKS fixes

- config/config.yaml.dist
- internal/clusterfeature/features/dns/externaldns/chart.go
- internal/clusterfeature/features/dns/operator.go
- internal/clusterfeature/features/dns/spec.go
- internal/clusterfeature/features/dns/spec_test.go
DNS cluster feature related fixes. See commits for more details.
> DNS cluster feature related fixes

- internal/clusterfeature/features/dns/operator.go
When no provider options are sent in the request, the `Options` field will be `nil`. Before dereferencing, check for `nil`.
> Do not dereference DNS cluster feature spec provider options without checking for nil

- config/config.yaml.dist
- internal/clusterfeature/features/logging/config.go
- internal/clusterfeature/features/monitoring/config.go
- internal/cmd/config.go
- Add Monitoring and Logging feature chart config validation
- Add Loki configs to the logging
> [Feature] Add Monitoring and Logging chart config validation

- auth/oidc.go
Pass the same. configured httpClient to each call through context.
To use the same configuration.
> oidc: pass the same, configured httpClient to each call

- internal/clusterfeature/features/monitoring/operator_secret.go
> [Monitoring] Fix create secret request in case of generate component secrets

- go.mod
- go.sum
Fix for Vault client `Close()`.
https://github.com/banzaicloud/bank-vaults/commit/7da4cb38e487e0144241562b04fd5adc7864098a#diff-66925bd79e13b4b8ee8eb7f75abf8d7d
To close the client properly and get rid of:
```
=pipeline
time="2019-11-08T13:53:36Z" level=info msg="2019/11/08 13:53:36 Failed to request new Vault token Put asdf/v1/auth/kubernetes/login: unsupported protocol scheme \"\"" application=pipeline
time="2019-11-08T13:53:36Z" level=info msg="2019/11/08 13:53:36 Failed to request new Vault token Put asdf/v1/auth/kubernetes/login: unsupported protocol scheme \"\"" …
```
> update bank-vaults sdk to 0.2.1, contains close() fix

- charts/pipeline/Chart.yaml
- charts/pipeline/values.yaml
> Bump chart version

- internal/clusterfeature/features/vault/client.go
- internal/clusterfeature/features/vault/operator.go
Making Vault feature activation/deactivation more robust and resilient.
It was unstable if the cluster was a bit more loaded (Service Account Token creation is async).
> [Vault Feature] Making feature activation/deactivation more robust and resilient

- auth/config.go
- internal/cmd/config.go
Fix token config audience error message
> Fix token config audience error message

- config/config.yaml.dist
- internal/clusterfeature/features/logging/common.go
- internal/clusterfeature/features/logging/common_test.go
- internal/clusterfeature/features/logging/config.go
- internal/clusterfeature/features/logging/error.go
- internal/clusterfeature/features/logging/manager.go
- internal/clusterfeature/features/logging/manager_test.go
- internal/clusterfeature/features/logging/spec.go
- internal/cmd/config.go
> [Logging] Add feature manager

- config/config.yaml.dist
- internal/cmd/config.go
vault-feature: bump chart version to 0.6.0
> vault-feature: bump chart version to 0.6.0

- api/cluster/namespace/list.go
- api/cluster/namespace/namespace.go
- apis/pipeline/pipeline.yaml
- cmd/pipeline/main.go
- internal/security/anchore_client.go
* The PR contains the implementation of retrieving namespaces for a given cluster (this is required by pipeline clients to facilitate eg.: feature activation)
* the new resource has been added to the open API specification
> endpoint for listing namespaces for a cluster

- internal/clusterfeature/features/monitoring/operator.go
- internal/clusterfeature/features/monitoring/values.go
Set `grafana.persistence.enabled` value to `true`
Use persistent volume to store data
> [Monitoring] Use persistent volume to store data in case of Grafana

- internal/kubernetes/scheme.go
- internal/kubernetes/service.go
> KubernetesService: fix scheme registration

- internal/clusterfeature/features/logging/operator.go
Merge generated values with config values
> [Logging] Merge generated values with config values

- internal/clusterfeature/features/monitoring/operator.go
- internal/clusterfeature/features/monitoring/values.go
Cleanup CRDs after deactivating monitoring service
Otherwise activating monitoring again does not work.
> Cleanup CRDs after deactivating monitoring service

- internal/clusterfeature/features/monitoring/operator.go
- internal/clusterfeature/features/monitoring/values.go
Remove affinity and toleration from chart values
> [monitoring] Remove affinity and toleration from chart values

- cluster/hookfunctions.go
- cluster/hooks.go
- internal/providers/azure/pke/adapter/gorm_store.go
- pkg/cluster/base.go
Remove anchore image validator posthook
Use security scan feature instead.
> Remove anchore image validator posthook

- cluster/gke.go
Initiate cluster version upgrades on cluster update only if the desired K8s version is greater than the actual K8s master version. 
GCP auto-upgrade GKE masters (or the user upgrades it manually from GCP console) thus the K8s version Pipeline stores in the database might be obsolete. When a cluster update is initiated Pipeline reads cluster version from the database. If this version different from the actual cluster version it started a cluster version upgrade regardless of the actual version being higher. This resulted in failure as the obsolete version wasn't supported for GKE any more.
> Upgrade only GKE cluster if the desired K8s version is greater than the actual current master version

- internal/cluster/endpoints/endpoints.go
Add http prefix to service endpoints
> Add http prefix to service endpoints

- cluster/ack.go
- cluster/aks.go
- cluster/common.go
- cluster/dummy.go
- cluster/ec2_pke.go
- cluster/eks.go
- cluster/gke.go
- cluster/kubernetes.go
- cluster/oke.go
- internal/providers/azure/pke/driver/commoncluster/cluster.go
Remove CommonCluster.GetCreatedBy
Not used
> Remove CommonCluster.GetCreatedBy

- api/cluster_get.go
- cluster/ack.go
- cluster/aks.go
- cluster/common.go
- cluster/dummy.go
- cluster/ec2_pke.go
- cluster/eks.go
- cluster/gke.go
- cluster/kubernetes.go
- cluster/oke.go
- cmd/pipeline/main.go
- internal/cluster/cluster_model.go
- internal/cluster/model.go
- internal/dashboard/api.go
- internal/dashboard/dashboard.go
- internal/monitor/cluster_subscriber.go
- internal/providers/azure/pke/adapter/gorm_store.go
- internal/providers/azure/pke/cluster.go
- internal/providers/azure/pke/driver/commoncluster/cluster.go
- internal/providers/azure/pke/store.go
- model/cluster.go
- model/migrate.go
- pkg/cluster/base.go
Remove cluster feature flags from common cluster
We use integrated services from now on.
> Remove cluster feature flags from common cluster

- cluster/hookfunctions.go
- cluster/hooks.go
- cmd/worker/main.go
- internal/cluster/clustersetup/activity_create_pipeline_namespace.go
- internal/cluster/clustersetup/activity_create_pipeline_namespace_test.go
- internal/cluster/clustersetup/integration_test.go
- internal/cluster/clustersetup/workflow.go
- internal/cluster/clustersetup/workflow_test.go
- pkg/cluster/base.go
- pkg/k8sclient/dynamic_test.go
Relocate pipeline namespace create
Posthooks are being replaced by cluster setup workflow.
> Relocate pipeline namespace create

- cmd/worker/main.go
> Fix missing activity registration

- cluster/create_workflow.go
Fix setup privileges config secret ID
Config secret ID needs to be in BRN format.
> Fix setup privileges config secret ID

- cmd/pipeline/config.go
> Fix default UI config

- auth/authn.go
- cmd/pipeline/config.go
- cmd/pipeline/main.go
> Fix UI signup redirect URL

- cluster/hookfunctions.go
- cluster/hooks_nodelabels.go
- cmd/worker/main.go
- internal/cluster/clusterconfig/config.go
- internal/cluster/clustersetup/activity_install_nodepool_labelset_operator.go
- internal/cluster/clustersetup/activity_install_nodepool_labelset_operator_test.go
- internal/cluster/clustersetup/helm.go
- internal/cluster/clustersetup/workflow.go
- internal/cluster/clustersetup/workflow_test.go
- internal/cmd/config.go
- internal/global/config.go
- pkg/cluster/base.go
Relocate nodepool label operator
Posthooks are deprecated
> Relocate nodepool label operator

- .gen/pipeline/api/openapi.yaml
- apis/pipeline/pipeline.yaml
Several OpenAPI optimizations:
- Reused parameters
- Coding style fixes
- Removed superfluous quotes
Descriptor became shorter by almost 2k LOC.
> Optimize openapi

- .gen/pipeline/api/openapi.yaml
- apis/pipeline/pipeline.yaml
- cmd/pipeline/main.go
> Nodepool labels api

- auth/oidc.go
- docker-compose.yml
- etc/config/dex.yml.dist
Since https://github.com/dexidp/dex/releases/tag/v2.21.0 Dex supports "groups" claim, which can be translated into Pipeline organizations.
> auth: support for google groups

- database/migrations/mysql/1574935040_drop_nodepool_label_tables.down.sql
- database/migrations/mysql/1574935040_drop_nodepool_label_tables.up.sql
- database/migrations/postgres/1574935040_drop_nodepool_label_tables.down.sql
- database/migrations/postgres/1574935040_drop_nodepool_label_tables.up.sql
- internal/providers/google/gke_cluster_model.go
- internal/providers/google/model.go
- internal/providers/oracle/model.go
- model/cluster.go
- model/migrate.go
- pkg/providers/oracle/model/cluster.go
> Remove unused tables

- internal/clusterfeature/features/monitoring/operator.go
Add annotations to annotations of ingress
To use auth on prometheus too in case of enabled ingress
> [Monitoring] Fix ingress annotations on Prometheus

- etc/config/dex.yml.dist
- scopes: the default is good for google, don't specify it
- issuer: not available for google
> dex: cleanup unused and unavailable fields

- cmd/pipeline/main.go
- cmd/pipeline/migrate.go
- cmd/worker/main.go
- internal/cluster/clusteradapter/gorm_cluster_model.go
- internal/cluster/clusteradapter/gorm_cluster_status_history_model.go
- internal/cluster/clusteradapter/gorm_clusters.go
- internal/cluster/clusteradapter/gorm_model.go
- internal/cluster/clusteradapter/log.go
- internal/cluster/common.go
- internal/providers/azure/pke/adapter/gorm_store.go
- internal/providers/azure/pke/adapter/gorm_store_test.go
- internal/providers/google/gke_cluster_model.go
- internal/providers/google/gke_cluster_model_test.go
- internal/providers/pke/ec2_cluster_model.go
- src/api/ark/common/middleware.go
- src/api/cluster.go
- src/api/cluster_create.go
- src/api/secrets.go
- src/cluster/common.go
- src/cluster/ec2_pke.go
- src/cluster/gke.go
- src/cluster/gke_global.go
- src/cluster/middleware.go
- src/cluster/pipeline_monitoring.go
- src/cluster/ttl_controller.go
- Remove some (hardly) used code
- Relocate Gorm models to adapter package
> Cluster refactors

- database/migrations/mysql/1574424732_modify_topology_kubeadms_extra_args_json.down.sql
- database/migrations/mysql/1574424732_modify_topology_kubeadms_extra_args_json.up.sql
- database/migrations/mysql/1574432613_modify_azure_pke_node_pools_json_roles_and_zones.down.sql
- database/migrations/mysql/1574432613_modify_azure_pke_node_pools_json_roles_and_zones.up.sql
- database/migrations/postgres/1574424732_modify_topology_kubeadms_extra_args_json.down.sql
- database/migrations/postgres/1574424732_modify_topology_kubeadms_extra_args_json.up.sql
- database/migrations/postgres/1574432613_modify_azure_pke_node_pools_json_roles_and_zones.down.sql
- database/migrations/postgres/1574432613_modify_azure_pke_node_pools_json_roles_and_zones.up.sql
- internal/clusterfeature/clusterfeatureadapter/gorm_feature_repository.go
- internal/providers/azure/pke/adapter/gorm_store.go
- internal/providers/model.go
- internal/providers/pke/config.go
- internal/providers/pke/config_test.go
- internal/providers/pke/cri.go
- internal/providers/pke/cri_test.go
- internal/providers/pke/kubeadm.go
- internal/providers/pke/kubeadm_test.go
- internal/providers/pke/network.go
- internal/providers/pke/network_test.go
- internal/providers/pke/nodepool.go
- internal/providers/pke/nodepool_test.go
* Use JSON scanner/valuer implementation helper in more places.
* Use scanner/valuer types in more places.
* Move scanner/valuer implementation checks to tests.
* Change some columns' types to JSON for possible performance gains and validation.
Simpler and more uniform code.
Also, non-runtime checks belong in tests.
> Database refactors

- pkg/kubernetes/custom/npls/manager.go
> Add node pool label set delete client

- README.md
Simplifying the readme - all information is available in the public docs.
Docs.
> Simplifying the readme

- src/auth/oidc.go
This maps to the Google auth model much better than the previous version.
> auth/google: group domain -> org, group name -> role

- cmd/worker/main.go
- internal/global/config.go
- src/api/npls.go
- src/cluster/manager_common_updater.go
> Fix: wrong namespace config passed to node pool labelset manager

- src/auth/authz.go
- src/auth/authz_test.go
> Fix kube config download

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_google_project.go
- .gen/pipeline/pipeline/model_google_projects.go
- apis/pipeline/pipeline.yaml
- cmd/pipeline/main.go
Remove deprecated google projects call
> Remove deprecated google projects call

- database/migrations/mysql/1575564926_drop_feature_columns_from_clusters.down.sql
- database/migrations/mysql/1575564926_drop_feature_columns_from_clusters.up.sql
- database/migrations/postgres/1575564926_drop_feature_columns_from_clusters.down.sql
- database/migrations/postgres/1575564926_drop_feature_columns_from_clusters.up.sql
- internal/cluster/clusteradapter/gorm_model.go
- src/model/migrate.go
> Remove cluster feature columns

- internal/providers/amazon/eks/workflow/bootstrap_activity.go
Retrieve user name from IAM User ARN for cluster users and use that in the user config map that grants users access to the cluster
> Use user name IAM user ARN for EKS cluster user

- cmd/pipeline/main.go
> Fix Pipeline config parsing

- src/cluster/gke.go
Verify if a GKE cluster already exists with the same name in the Google project/zone and continue the cluster setup flow only of that cluster was created by Pipeline. If the cluster was created by some 3rd party (e.g created manually through Google console) return an error message to the user indicating that a cluster with the same name already exists.
The Google project/zone may already host a GKE cluster with the same name. In this case, Pipeline should not continue with setting up the cluster as that cluster is already set up by 3rd party. Pipeline should only continue if the cluster was created by a Pipeline instance …
> Return with error if a GKE cluster with same name created by 3rd party already exists

- config/config.yaml.dist
- internal/cmd/config.go
> Update default list of forbidden domain list for node pool labelset operator

- go.mod
- go.sum
- internal/providers/amazon/eks/workflow/create_eks_control_plane_activity.go
Upgrade to latest EKS SDK as that allows tagging EKS control plane. Apply Pipeline tags to EKS control plane.
Pipeline's delete/update privileges can be restricted at IAM role level to resources that have certain tags. This requires all resources created by Pipeline to be tagged by Pipeline.
> Apply Pipeline tags to EKS control plane

- internal/providers/azure/pke/adapter/gorm_store.go
- internal/providers/azure/pke/adapter/gorm_store_test.go
Make old store models behave more like the new ones.
More uniform codebase.
> Refactor Azure PKE store model<->entity conversion

- internal/integratedservices/services/logging/operator.go
- internal/integratedservices/services/logging/values.go
Add `annotations` field to loki's ingress values
To fix Loki ingress
> [Logging]: Fix Loki ingress annotations

- src/cluster/gke.go
- src/cluster/oke.go
| Bug fix?        |  yes
Fix kubeconfigs for OKE clusters by generating SA for Pipeline and replace the exec auth in the stored kubeconfig with the SA token for now.
OKE started providing kubeconfigs with exec auth setting which requires the `oci` CLI tool and that breaks the current implementation.
The change also affects the GKE cluster implementation, since we use SA token based auth there as well. The PR changes the namespace/name of the generated SA from `default/netes-default` to `kube-system/pipeline`.
> replace exec auth in OKE kubeconfig to SA token

- src/cluster/hooks_ingress.go
Tag LoadBalancer type service for ingress with Pipeline managed tags when the cluster is created on Amazon.
Allows the IAM account to be limited to resources by tags.
> Tag ingress load balancers when on amazon

- internal/providers/amazon/eks/workflow/bootstrap_activity.go
Configure the CNI driver to tag ENIs with Pipeline tags by patching the CNI driver daemonset when creating the cluster.
ENIs are not cleaned up by the control plane delete, so we need to clean them up once the cluster is deleted. In order to allow customers to restrict IAM access to resources created/managed by Pipeline, we need to tag them. ENIs are created by the CNI driver, so we need to configure it before creating any ASGs during cluster create.
This feature is not released yet. Will be part of the 1.6.0 CNI driver release:
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.0-rc5
Additional resources: …
> Patch AWS CNI daemonset with additional tags

- .gen/pipeline/api/openapi.yaml
- apis/pipeline/pipeline.yaml
- cmd/pipeline/main.go
- docs/postman/e2e_test.postman_collection.json
- internal/integratedservices/integratedservicedriver/transport_http.go
- internal/integratedservices/integratedservicedriver/transport_http_test.go
Rename features to integrated services in API endpoints/transport layer.
Make API consistent with new naming (features → integrated services)
> Integrated services endpoints

- internal/providers/amazon/eks/workflow/amazon.go
Add additional logging to EKS when waiting for ASG spot fulfilment.
> EKS: additional logging in WaitForASGToBeFulfilled

- internal/providers/amazon/eks/workflow/bootstrap_activity.go
Report back error if creating `aws-auth` config map fails.
> Fix aws auth error reporting

- internal/cluster/clustersetup/activity_install_tiller_wait.go
- internal/providers/amazon/eks/workflow/bootstrap_activity.go
Add a few debug logs to the EKS flow
> Add debug logs

- internal/cluster/clustersetup/activity_install_tiller_wait.go
- internal/cluster/clustersetup/workflow.go
- internal/providers/amazon/eks/workflow/bootstrap_activity.go
> Backport AWS fixes into 0.3.6

- internal/cluster/clusterdriver/cluster_transport_http.go
> fix cluster delete routing

- cmd/worker/main.go
> fix missing workflow client

- internal/integratedservices/services/common.go
- internal/integratedservices/services/expiry/adapter/expiry_service.go
The PR contains  some bug fixes around error checking and leftovers (code improvements) from the previous related PR
Some bugs have slipped in with the latest PR
> expiry related amendaments

- config/config.yaml.dist
- internal/cmd/config.go
Upgrade chart version and image tags
> [Monitoring] Upgrade chart version and image tags

- .circleci/config.yml
> Fix docker build in case of `/` in branch name

- Makefile
- config/config.dev.yaml
Generate a default UUID in local environment.
> Generate default UUID in dev environment

- docker-compose.yml
Update dev environment components.
> Update dev environment

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/cmd/config.go
- internal/integratedservices/services/securityscan/config.go
- internal/integratedservices/services/securityscan/manager.go
- internal/integratedservices/services/securityscan/manager_test.go
- internal/integratedservices/services/securityscan/operator.go
- internal/integratedservices/services/securityscan/spec.go
- internal/integratedservices/services/securityscan/spec_test.go
- internal/integratedservices/services/securityscan/values.go
The PR contains updates to the security scan int. svc. implementation to support the refreshed webhook version
Major amendments have been added to the webhook implementation, that simplifies the way the integrated service configures it.
> update security scan integrated service

- internal/cmd/config.go
the minor version of the chart has been increased ...
> increase the default security scan realated chart version

- apis/pipeline/pipeline.yaml
- cmd/pipeline/main.go
- src/api/cluster.go
> Remove unused apiendpoint

- docker-compose.yml
> Remove adminer from the dev environment

- cmd/pipeline/main.go
- internal/global/config.go
- src/api/security.go
Remove unused security scan call
> Remove unused security scan call

- internal/providers/amazon/eks/workflow/amazon.go
- internal/providers/amazon/eks/workflow/bootstrap_activity.go
- internal/providers/amazon/eks/workflow/create_iam_roles_activity.go
- internal/providers/amazon/eks/workflow/create_iam_roles_activity_test.go
- templates/eks/amazon-eks-iam-cf.yaml
backport of:
https://github.com/banzaicloud/pipeline/pull/2699
https://github.com/banzaicloud/pipeline/pull/2707
> [backport-0.37.x] EKS AWS IAM path fixes

- cmd/pipeline/config.go
- cmd/worker/config.go
- internal/cmd/config.go
> fix worker auth config

- internal/providers/pke/pkeworkflow/delete_cluster.go
> fix the retryPolicy for cluster deletion activities

- cmd/pipeline/config.go
- cmd/worker/config.go
- internal/cmd/config.go
> remove CICD database config from worker config

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/istio/istiofeature/handler.go
> Pass missing config to ServiceMeshFeatureHandler

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/istio/istiofeature/handler.go
> Fix istiofeature config backport

- cmd/pipeline/main.go
- go.mod
- go.sum
- internal/app/frontend/app.go
- internal/app/pipeline/auth/token/token.go
- internal/app/pipeline/auth/token/tokendriver/middleware.go
- internal/cluster/errors.go
- internal/cluster/service.go
- internal/cluster/service_node_pool.go
- internal/common/secret.go
- internal/integratedservices/integratedserviceadapter/gorm_integrated_service_repository.go
- internal/integratedservices/interface.go
- internal/integratedservices/registry.go
- internal/integratedservices/service.go
- pkg/kubernetes/label_validator.go
- src/secret/store.go
Fix errors being returned as internal server errors.
> Fix error handling

- .github/workflows/.editorconfig
- .github/workflows/snapshot.yml
- Makefile
> Add snapshot workflow

- cmd/worker/main.go
- internal/providers/azure/pke/driver/cluster_deleter.go
- internal/secret/kubesecret/kubernetes.go
- internal/secret/kubesecret/kubernetes_test.go
- src/cluster/secrets.go
> Relocate kubernetes secret code

- .circleci/config.yml
- cmd/pipeline/config.go
- internal/cmd/config.go
> move telemetry config defaults to common configurator function

- internal/providers/azure/pke/driver/ssh.go
- internal/secret/sshsecret/ssh.go
> Relocate ssh secret tools

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/global/vault.go
- internal/secret/pkesecret/pkesecret.go
- internal/secret/restricted/store.go
- internal/secret/secretadapter/integration_test.go
- internal/secret/secretadapter/store_vault.go
- internal/secret/secretadapter/store_vault_test.go
- internal/secret/service.go
- src/api/secrets_test.go
- src/cluster/common_test.go
- src/dns/externaldns.go
- src/dns/route53/route53_test.go
- src/secret/store.go
This PR adds a new (heavily integration tested) Vault secret store adapter.
Secret management is a central part of the platform, yet it hasn't been touched for a long time.
> Implement Vault secret store adapter

- go.mod
- go.sum
- pkg/providers/azure/clients.go
- pkg/providers/azure/cloud.go
- pkg/providers/azure/extensions.go
- src/cluster/aks.go
- src/cluster/create_workflow.go
- src/cluster/manager_common_updater.go
| Related tickets | related https://github.com/Azure/AKS/issues/1088#issuecomment-587730732
Azure AKS now supports adding initial node labels to agent pools.
Use it instead of manually adding labels.
> Use AKS AgentPool node labels

- cmd/worker/main.go
- go.mod
- go.sum
> Update run group

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/pke/pkeworkflow/create_cluster.go
> providers: update PKE to 0.4.23

- internal/cmd/config.go
- internal/global/config.go
- src/cluster/hooks.go
Upgrade hpa-operator charts, refactor config
> hpa post hook upgrade

- .golangci.yml
- cmd/worker/aws.go
- cmd/worker/config.go
- cmd/worker/main.go
- config/config.yaml.dist
- internal/cmd/config.go
- internal/providers/pke/pkeworkflow/create_cluster.go
| Related tickets | fixes #2760, fixes #2759
Make the region for the `pke-global` stack configurable.
> Make pke global region configurable

- .gen/dex/api.pb.go
- Makefile
- go.mod
- go.sum
Make sure that protoc-gen-go is always up to date with the used version in the project.
> Fix protoc-gen-go binaries build

- database/migrations/mysql/1583070164_drop_ttl_minutes_column_from_clusters_table.down.sql
- database/migrations/mysql/1583070164_drop_ttl_minutes_column_from_clusters_table.up.sql
- database/migrations/postgres/1583070164_drop_ttl_minutes_column_from_clusters_table.down.sql
- database/migrations/postgres/1583070164_drop_ttl_minutes_column_from_clusters_table.up.sql
- internal/cluster/clusteradapter/gorm_model.go
- src/model/migrate.go
Drop unused TTL fields from the database.
> Drop TTL fields

- .github/mergeable.yml
> Improve mergeable rules

- src/model/ack.go
- src/model/aks.go
- src/model/cluster.go
- src/model/dummy.go
- src/model/eks.go
- src/model/kube.go
Reorganize legacy cluster models
> Reorganize models

- internal/providers/google/model.go
- pkg/gormhelper/migrate.go
- src/model/migrate.go
> Move common gorm code to separate package

- internal/providers/google/model.go
Use the correct cluster model.
> Fix google orm foreign key

- internal/providers/amazon/amazonadapter/migrate.go
- src/model/migrate.go
> Refactor amazon foreign keys

- src/api/secrets.go
| Related tickets | backports  #2773
Backports  #2773 to 0.39.x
> Return 404 when a secret cannot be found

- .circleci/config.yml
- cmd/pipeline/migrate.go
- internal/providers/amazon/amazonadapter/eks.go
- internal/providers/amazon/amazonadapter/migrate.go
- internal/providers/amazon/eks/driver/cluster_creator.go
- internal/providers/amazon/eks/driver/cluster_deleter.go
- internal/providers/amazon/eks/driver/cluster_updater.go
- internal/providers/amazon/eks/workflow/amazon.go
- src/cluster/common.go
- src/cluster/eks.go
- src/model/cluster.go
- src/model/migrate.go
Refactor EKS cluster model
Makes it easier to work with EKS.
> Refactor EKS model

- internal/providers/pke/pkeworkflow/create_cluster.go
| Related tickets | fixes #2759
> Wait for PKE global stack in the right region

- apis/pipeline/postman.json
> Improve postman collection

- Makefile
> Add ref support to snapshot

- internal/cluster/distribution/eks/eksprovider/workflow/save_network_details_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/save_nodepools_activity.go
> Fix EKS model save

- apis/pipeline/postman.json
vsphere: add create cluster request sample to Postman collection
> vsphere: add create cluster request sample to Postman collection

- cmd/pipeline/main.go
| Related tickets | n/a
Use run https://github.com/oklog/run in main.go instead of goroutines for API listeners.
For better structure and handling.
> use run.Group

- cmd/pipeline/main.go
Improve run group usage:
- shutdown servers gracefully
- add spotmetrics to run group
- add ark sync services to run group
> Graceful shutdown

- docker-compose.yml
- dex-shim 0.6.0
- bank-vaults 1.0.1
> update dex-shim and bank-vaults

- .gen/pipeline/pipeline/model_pke_on_vsphere_node_pool.go
- src/api/cluster/pke_vsphere.go
Case fix for vsphere generated model code.
The openapi generator changes the case to camelcase on rerun, the code breaks.
> vsphere: fix openapi case

- internal/security/anchore_client.go
Fix potential panic in anchore client (check error first before checking response)
> Fix potential panic in anchore client

- cmd/pipeline/main.go
> make ca cert optional (client auth)

- apis/pipeline/postman.json
- cmd/pipeline/main.go
- cmd/worker/eks.go
- internal/cluster/clusteradapter/distribution_eks.go
- internal/cluster/clusterdriver/transport_http.go
- internal/cluster/clusterdriver/transport_http_test.go
- internal/cluster/clusterdriver/zz_generated.endpoint.go
- internal/cluster/distribution/eks/eksadapter/node_pool_manager.go
- internal/cluster/distribution/eks/eksprovider/workflow/aws_session.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cluster/distribution/eks/eksworkflow/activity_wait_cloudformation_stack_update.go
- internal/cluster/distribution/eks/eksworkflow/common.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
- internal/cluster/distribution/eks/service.go
- internal/cluster/service.go
- internal/cluster/service_node_pool.go
- internal/cluster/service_node_pool_test.go
- internal/cluster/zz_generated.mock.go
- templates/eks/amazon-eks-nodepool-cf.yaml
Initial node pool update process
> Node pool update MVP

- cmd/pipeline/config.go
- cmd/worker/config.go
- config/config.yaml.dist
- internal/cluster/distribution/eks/eksprovider/workflow/templates.go
- internal/global/config.go
- templates/eks/amazon-eks-nodepool-cf.yaml
Enable Go templating of CF templates.
Some parts can't be configured otherwise.
> add go templates to cloudformation templates

- charts/pipeline/Chart.yaml
> Update helm chart logo

- src/cluster/hooks.go
> Do not install the instance termination handler by default

- charts/pipeline/Chart.yaml
- charts/pipeline/templates/deployment-worker.yaml
- charts/pipeline/templates/deployment.yaml
- charts/pipeline/values.yaml
> fix missing deploymentLabels

- cmd/pipeline/main.go
- internal/ark/deployments_svc.go
- internal/ark/posthook/posthook.go
- internal/helm/helmadapter/helm_service.go
- src/api/ark/backupservice/backupservice.go
- src/api/ark/backupservice/disable.go
- src/api/ark/backupservice/enable.go
- src/cluster/hook_workflow.go
- src/cluster/hookfunctions.go
- src/cluster/hooks.go
> helm3 support for ark and initspotconfig posthook

- .golangci.yml
- cmd/pipeline/main.go
- internal/cluster/clusterdriver/transport_http.go
- internal/cluster/distribution/eks/eksadapter/node_pool_manager.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cluster/distribution/eks/eksworkflow/common.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
Improve node pool update functionality
> Node pool update

- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
Don't execute wait activity if no update is applied to the CF stack.
> update: skip cf wait if not needed

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/workflow/create_node_activity_test.go
Update PKE version which contains fixes for K8s version 1.18.
> Update pke version

- .circleci/config.yml
- docker-compose.override.yml.dist
- internal/secret/secretadapter/integration_test.go
- src/api/secrets_test.go
- src/cluster/ack_test.go
- src/cluster/common_test.go
- src/dns/route53/route53_test.go
Create a separate job to run integration tests and setup a single node kubernetes test cluster using kind.
> Enable kubernetes integration tests

- internal/platform/gin/drain.go
Fixes a deadlock in the drain middleware when there is an open proxy connection.
> Fix drain deadlock

- internal/platform/gin/drain.go
> Fix drain lock

- pkg/sdk/process/process.go
Temporarily hard coding the task list in the process log SDK.
> Limit the process log SDK to the pipeline tasklist

- cmd/worker/eks.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_calculate_node_pool_version.go
- internal/cluster/distribution/eks/eksworkflow/activity_calculate_node_pool_version_test.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
- internal/cluster/distribution/eks/node_pool.go
- internal/cluster/node_pool_labels.go
- internal/cluster/node_pool_labels_test.go
Add node pool version label to EKS clusters during cluster create and update.
> EKS node pool version

- internal/providers/vsphere/pke/workflow/create_node_activity.go
Ensure vm's are powered on after cloning vm template.
Most of the times after cloning vm from template, it gets powered on as well, however sometimes vm is created but it's not started.
> vsphere: ensure vm's are powered on after cloning

- internal/helm/envresolver.go
- internal/helm/envresolver_integration_test.go
- internal/helm/helmadapter/releaser_service.go
- internal/helm/helmdriver/transport_http.go
- internal/helm/releaser_integration_test.go
- internal/helm/service.go
- src/cluster/hook_workflow.go
* Adds filtering option to the list releases operation. (release names are matched against a given regexp - similarly to the helm cli tool)
* it also contains integration test cases that check the filtering
also fixes #2879 
The filtering options needs to be supported in a handful of flows.
> support filtering while listing releases 

- internal/app/pipeline/process/processadapter/gorm_store.go
Add missing log message to finished processes.
Because it was missing.
> process: write log when finishing process

- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
> Allow changing the desired ASG capacity

- .golangci.yml
- Makefile
- pkg/sdk/go.mod
- pkg/sdk/go.sum
Enable listing in the SDK module as well.
It wasn't running there.
> run linter and tests for the sdk module as well

- internal/helm/charter.go
- internal/helm/helmadapter/helm3_env_service.go
* possibility to retrieve only latest versions of a chart
* fix retrieval of charts from all registered repos
Backwards compatibility reasons
> Helm chart list related amendments (helm v3)

- internal/helm/helmadapter/helm3_env_service.go
- internal/helm/service.go
Helm repo modify and update calls delete and re-add the repository thus making sure the repository is up to date.
Helm repository update and modify calls were broken
> Corrected helm repository repo-modify and  repo-update calls

- cmd/pipeline/main.go
- cmd/worker/main.go
- internal/clustergroup/deployment/helm.go
- internal/clustergroup/deployment/integration_test.go
- internal/clustergroup/deployment/manager.go
- internal/helm/charter.go
- internal/helm/helmadapter/helm3_env_service.go
- internal/helm/helmdriver/zz_generated.endpoint.go
- internal/helm/values.go
- internal/helm/zz_generated.mock_test.go
- internal/helm2/service.go
- internal/istio/istiofeature/reconcile.go
- internal/istio/istiofeature/reconcile_remoteistios.go
- src/api/clustergroup/deployment/create.go
- src/api/clustergroup/deployment/upgrade.go
Prepare a chart description getter component to replace the legacy logic in the clustergroup manager and fix chart version matching on the legacy path
> Helm3 support for Cluster Groups

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/workflow/create_node_activity_test.go
- src/cluster/ec2_pke.go
| Related tickets | fixes #2922
Upgrade PKE to 0.5.0 and add support for Docker container runtime in AWS PKE.
> Upgrade PKE

- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/pke/pkeworkflow/create_cluster.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/workflow/create_node_activity_test.go
- src/cluster/ec2_pke.go
> Backport #2928

- cmd/pipeline/capabilities.go
- internal/integratedservices/services/dns/common_test.go
- internal/integratedservices/services/helm.go
- internal/integratedservices/services/logging/common_test.go
- internal/integratedservices/services/logging/operator.go
- internal/integratedservices/services/logging/values.go
- internal/integratedservices/services/monitoring/common_test.go
- internal/integratedservices/services/vault/common_test.go
Merge bugfix patches applied on top of 0.44.0 until 0.44.1 inclusive
> Integrate 0.44 patches into mainline

- charts/pipeline/templates/deployment.yaml
Fix pipelinectl env vars in pipeline deployment
> Fix pipelinectl env vars

- config/config.dev.yaml
- docker-compose.override.yml.dist
- docs/auth/github.md
- etc/config/dex.yml.dist
- Enable HTTPS by default
- Disable google and ldap providers (causes dex to fail)
> Improve dev env

- Makefile
- cmd/pipeline/capabilities.go
- cmd/pipeline/main.go
- go.mod
Adds helm version compile time to the binary.
> Add helm version compile time

- internal/integratedservices/services/monitoring/operator.go
Fixes the activation path of the monitoring integrated service, as the migration path broke it, since if there is no existing release, then it fails on being unable to get the release.
> Fix the monitoring integrated service broken activation path

- internal/helm/helmadapter/releaser_service.go
Namespaces are handled properly in case of upgrades.
Looking up releases for upgrade failed.
> Fix namespace handling in case of upgrades

- internal/helm/helmadapter/releaser_service.go
- internal/helm/helmdriver/transport_http.go
Chart version passed to the upgrade release operation
Chart version was ignored during upgrade
> Pass the version to the upgrade release operation

- .circleci/config.yml
- docker-compose.yml
- go.mod
- go.sum
Update vault, bank-vaults and the sdk to the latest releases.
> sync bank-vaults versions to upstream latest

- templates/eks/amazon-eks-nodepool-cf.yaml
Making `InstanceMarketOptions` depend on `spotPrice`.
To fix always spot node instance setting.
> eks: fix InstanceMarketOptions templating

- templates/eks/amazon-eks-nodepool-cf.yaml
| Related tickets | #2980 
backport of https://github.com/banzaicloud/pipeline/pull/2980 to 0.46.x
> [0.46.x] eks: fix InstanceMarketOptions templating

- .gen/anchore/model_mapping_rule.go
- .gen/anchore/model_policy_rule.go
- Makefile
- internal/helm/helmadapter/helm_service.go
- internal/helm2/service.go
- internal/integratedservices/services/securityscan/operator.go
- internal/security/anchore_client.go
| Related tickets | fixes #2985, https://github.com/banzaicloud/banzai-cli/pull/268
Implements policy selection in Anchore in the Security Scan integrated service.
It was missing.
> anchore-is: support changing and defining policies

- docs/developer.md
Fixing minor issues in the developer documentation.
Some trailing white-spaces are also removed in this PR from the same documentation file.
Going through the developer documentation I have spotted a couple issues such as references to removed features or incorrect links.
> docs(developer): fix minor outdated information issues in developer documentation

- go.mod
- go.sum
- internal/providers/vsphere/pke/workflow/create_node_activity_test.go
Remove unnecessary rewrite
We needed a special formatting logic into the yaml lib for spotguides.
Since spotguides are removed, we don't need it anymore.
> Remove unnecessary rewrite

- internal/integratedservices/services/securityscan/operator.go
- internal/integratedservices/services/securityscan/spec.go
- internal/security/anchore_client.go
| Related tickets | fixes #2988 
Support enabling custom registries when enabling the Anchore integrated service.
A payload example to enable the service with a custom registry:
```json
{
"spec": {
"customAnchore": {
"enabled": false
},
"policy": {
"policyId": "allow_all_and_warn"
},
"webhookConfig": {
"enabled": true,
"selector": "include",
"namespaces": [
"*"
]
},
"registry": {
"registry": "docker.pkg.github.com",
"secretId": "7a819d477093fa918d5e160d889745e5b00a381497f689d8183be75f53c4f76c"
}
}
}
```
The `secretId` has to point to `"password"` type secret.
> anchore: custom registry support

- internal/integratedservices/services/securityscan/operator.go
- internal/security/anchore_client.go
Taking the correct values from an AWS secret when adding an ECR registry to Anchore.
The feature took the non-existing values from the AWS Secret.
> anchore: fix ecr registry add

- docs/developer.md
Adding K8s version 1.17 to AMI image query script in the documentation.
To sync docs script with Pipeline version support
> docs(developer): add EKS 1.17 k8s version to AMI image query script

- internal/integratedservices/services/zz_generated.mock.go
Run `make generate` and committed the resulting diff.
While I was working on another issue, I had to regenerate some mock code and I noticed a totally unrelated generated change which is missing from the master branch.
What is our stance on adding a CI/Action step which would check whether the code generation make directive on the current commit's code would result in a non-zero diff (and fail if it is a non-zero diff)?
> chore(integratedservices): regenerated mock file, added ApplyDeploymentV3

- apis/pipeline/pipeline.yaml
Fix namespaces fields type of restore result in OpenAPI
> fix namespaces fields type of restore result in OpenAPI

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_restore_result_errors.go
- .gen/pipeline/pipeline/model_restore_result_warnings.go
Regenerate OpenAPI descriptor.
> Regenerate openapi

- .gitignore
- .licensei.toml
- .plzconfig
- .plzconfig.local.dist
- BUILD.plz
- Makefile.plz
- apis/anchore/BUILD
- apis/cloudinfo/BUILD
- apis/dex/BUILD
- apis/pipeline/BUILD
- cmd/pipeline/BUILD
- cmd/pipelinectl/BUILD
- cmd/worker/BUILD
- config/BUILD
- config/ui/BUILD
- etc/config/BUILD
- pleasew
This PR adds [Please](https://please.build/) to the toolchain, replacing most of make.
Make is great, but simple. Please (and similar build systems) come with a more comprehensive solution for building modern projects.
(*Note:* this PR does NOT replace make yet. It only adds please as an alternative, next to the existing toolchain. This is supposed to help with testing and ease the transition/demonstrate the usage of please.)
There is a new makefile (Makefile.plz) that's fully backward compatible (apart from a few removed rules that were only used internally anyway). Under the hood, it uses please. …
> Add Please to the toolchain

- apis/anchore/BUILD
Fix anchore spec build on linux.
> Fix anchore on linux

- .circleci/config.yml
- internal/integratedservices/services/vault/integration_test.go
- internal/integratedservices/services/vault/manager_test.go
- internal/integratedservices/services/vault/operator_test.go
Improve the separation of integration tests
> Improve separation of integration tests

- config/config.yaml.dist
> Fix indentation in the example config

- apis/pipeline/postman.json
Fixed copy&paste typo in the Postman collection.
To make it work out of the box.
> fix(Postman): corrected node pool list API path

- .dockerignore
> Ignore please directories in docker builds

- .plzconfig
- charts/pipeline/.helmignore
- charts/pipeline/BUILD
Add plz build rules for helm charts
> Add helm package and lint for pipeline chart

- .github/workflows/ci.yml
- .plzconfig
- .plzconfig.ci
- BUILD.plz
GitHub Actions take X with Please
> Add CI for please

- .golangci.yml
> Increase lint timeout

- docker-compose.yml
Upgrade cadence in the local development environment
> Upgrade cadence in the local development environment

- internal/cluster/distribution/eks/image_selector_defaults.go
| Related tickets | https://github.com/banzaicloud/cloudinfo/pull/359 , https://github.com/banzaicloud/pipeline/issues/3056
Update EKS optimized AMIs.
> Update EKS optimized amis

- docs/developer.md
- internal/cluster/distribution/eks/image_selector_defaults.go
| Related tickets | fixes #3068
Add a list of GPU accelerated AMIs for EKS.
> Add EKS GPU accelerated images

- internal/cluster/distribution/eks/image_selector_test.go
- internal/cluster/distribution/pke/pkeaws/image_selector_test.go
> Fix mocks in image selectors

- internal/cloudformation/BUILD
- internal/cloudformation/cloud_formation.go
- internal/cluster/distribution/eks/eksprovider/workflow/BUILD
- internal/cluster/distribution/eks/eksprovider/workflow/templates.go
- internal/providers/pke/pkeworkflow/BUILD
- internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
- internal/providers/pke/pkeworkflow/create_subnet_activity.go
> Relocate cloudformation function

- cmd/pipeline/main.go
- cmd/pipelinectl/main.go
- internal/app/pipelinectl/cli/commands/telemetry/telemetry.go
- internal/security/anchore_client.go
- src/api/anchore_proxy.go
- src/api/cluster_auth.go
- src/auth/oidc.go
- src/auth/tls.go
Not supported in a lot of components.
Removed MinVersion configuration because some components don't support 1.3 and some neither 1.2
To make shit work
> fix(TLS): removed MinVersion configuration

- cmd/worker/main.go
- config/config.yaml.dist
- internal/cmd/config.go
| Related tickets | fixes #3019
PKE fallback image override config
> Add PKE fallback image override config

- docs/developer.md
Clarified PKE external URL setting.
Because it was error prone.
> chore(developer.md): fixed PKE external URL

- .idea/pipeline.iml
> Exclude plz-out directory

- charts/pipeline/Chart.yaml
- charts/pipeline/templates/service.yaml
- charts/pipeline/templates/servicemonitor.yaml
- charts/pipeline/values.yaml
| Related tickets | fixes #3109 
> chart: add ServiceMonitor

- docs/developer.md
Clarified PKE cluster creation instructions.
Because it wasn't properly documented.
> chore(developer.md): clarified PKE instructions

- go.mod
- go.sum
- internal/cluster/distribution/eks/eksprovider/workflow/zz_generated.mock.go
Updated the aws-sdk-go dependency to latest version.
To use new features from it in the future.
Required for #3088 
Tested with EKS cluster creation, node pool creation, node pool deletion, cluster deletion, PKE cluster creation and deletion.
> chore(deps): updated aws-sdk-go (1.28.2->)1.34.4

- .circleci/config.yml
- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.alpine
- Dockerfile.debug
- Dockerfile.local
- Makefile
- charts/pipeline/.helmignore
- etc/build/Dockerfile
- go.mod
- pkg/sdk/go.mod
Updating Go versions to 1.15.
For staying up to date with Golang development version.
> chore(Go): updated Go version (1.14[.x]->)1.15

- Makefile
This workaround saves the plz BUILD configuration file. 
The OpenAPI code regeneration deletes all generated files. 
Tried moving it to the .gen/pipeline/go directory in advance or moving away and back before the generation completes, but those approaches did not work.
> chore(generation): keep BUILD file

- .plzconfig
- BUILD.plz
A new snapshot script for creating snapshots instead of the old git tag workflow.
We don't want to spam the repo with tags created for internal testing.
> Add snapshot script

- .github/workflows/snapshot.old.yml
- .github/workflows/snapshot.yml
Add new snapshot workflow for workflow_dispatch event
It's better suited for manual snapshot triggering than `repository_dispatch`.
> Add new snapshot workflow for workflow_dispatch event

- .github/workflows/ci.yml
- Makefile
Added generated file integrity check to the CIs.
Example:
```shell
generated files are not up to date with the configured dependency versions or current source code files, differences:
diff --git a/internal/cluster/distribution/eks/eksprovider/workflow/zz_generated.mock.go b/internal/cluster/distribution/eks/eksprovider/workflow/zz_generated.mock.go
index ed8dedf..519e9f8 100644
--- a/internal/cluster/distribution/eks/eksprovider/workflow/zz_generated.mock.go
+++ b/internal/cluster/distribution/eks/eksprovider/workflow/zz_generated.mock.go
@@ -2298,6 +2298,20 @@ func (_m *MockcloudFormationAPI) …
```
> ci(GHA): added generated file integrity check

- .vscode/launch.json
Fixing the launch.json compile path.
Otherwise, it is not runnable.
> fix VSCode launch.json

- cmd/pipeline/main.go
- go.mod
- go.sum
Update the BV Vault client to be able to configure logging, and use the same Vault client instance for the TokenStore.
> vault: update client to use the pipeline logger

- Makefile
- Makefile.plz
> Add snapshot to make

- internal/cluster/distribution/eks/eksprovider/workflow/select_volume_size_activity.go
Removed unnecessary no lint comment.
Because it was unnecessary as gochecknoglobals don't run on constants.
I'm an idiot.
- ~Implementation tested (with at least one cloud provider)
> chore: removed unnecessary lint comment

- internal/cluster/distribution/eks/image_selector_defaults.go
Add support for new AWS regions in EKS:
- Cape Town
- Milan
> Add new AWS regions for EKS

- internal/cluster/distribution/pke/pkeaws/image_selector_defaults.go
Add support for new AWS regions in PKE:
- Cape Town
- Milan
> Add new AWS regions for PKE

- internal/helm/envresolver_integration_test.go
- internal/helm/integration_test.go
- internal/helm/releaser_service_integration_test.go
Helm tests were not running in the CI
> Fix helm integration test execution

- cmd/worker/eks.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/create_infra_test.go
- internal/cluster/distribution/eks/eksprovider/workflow/validate_iam_role.go
| Related tickets | fixes #3034
Validate cluster role ID in case of EKS
> Validate cluster role ID

- .plzconfig
- .plzconfig.ci
- .plzconfig.local.dist
- BUILD.plz
- charts/pipeline/BUILD
- cmd/pipeline/BUILD
Upgrade please to a newer version
> Upgrade please

- config/config.yaml.dist
- internal/cmd/config.go
| Related tickets | fixes #3181 
Diasble Kubernetes dashboard installation by default
> Diasble Kubernetes dashboard installation by default

- internal/helm/releaser_service_integration_test.go
| API breaks?     |yes
The releaser integration test used invalid test data to manage releases. (app version instead of version)
The releaser integration test failed
> Fix failing integration test

- internal/cluster/distribution/eks/eksprovider/workflow/validate_iam_role.go
Fix cluster role ID validation when it's contains path
> fix cluster role ID validation

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_secret_type_response_fields.go
- apis/pipeline/pipeline.yaml
- internal/app/pipeline/secrettype/types.go
- internal/secret/secrettype/secret.go
- internal/secret/type.go
- internal/secret/types/type_alibaba.go
- internal/secret/types/type_amazon.go
- internal/secret/types/type_azure.go
- internal/secret/types/type_azure_storage_account.go
- internal/secret/types/type_cloudflare.go
- internal/secret/types/type_digitalocean.go
- internal/secret/types/type_google.go
- internal/secret/types/type_htpasswd.go
- internal/secret/types/type_oracle.go
- internal/secret/types/type_password.go
- internal/secret/types/type_slack.go
- internal/secret/types/type_ssh.go
- internal/secret/types/type_tls.go
- internal/secret/types/type_vsphere.go
| Related tickets | partially https://github.com/banzaicloud/banzai-cli/issues/315
Add isPassword field to secret-type response
> Add isPassword field to secret-type response

- internal/cluster/distribution/eks/eksprovider/workflow/validate_iam_role.go
Cherry picking the pathed cluster role ID validation fix to the 0.58.x hotfix branch.
To release a hotfix from the version 0.58.0 to our customers.
> fix(cl/c): fixed pathed cluster role ID validation

- .github/workflows/ci.yml
Improve docker build
Push images to ghcr.io
> Improve docker build

- .github/workflows/ci.yml
> ci: fix info steps

- internal/cluster/distribution/eks/eksprovider/workflow/delete_ssh_key_activity.go
Corrected a function comment to the function's name and content.
Because it showed up as false positive on searches due to the incorrect function comment.
I'm working on the #3185 issue and I was searching for `DeleteStackActivity` to see its usages.
I'm trying to minimize PR sizes so decided to split this out of the PR of that issue into its own according to the SRP.
- ~Related Helm chart(s) updated (if …
> docs(EKS/DeleteSSHKeyAct.): fixed function comment

- .github/workflows/ci.yml
| Related tickets | fixes #3219
> fix: docker image version ref

- .github/workflows/ci.yml
ci: improve GHA Docker image build
> ci: improve GHA Docker image build

- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.alpine
fix docker commit hash and build date
> ci: fix docker commit hash and build date

- cmd/worker/aws.go
- internal/cluster/distribution/pke/pkeaws/pkeawsadapter/node_pool_manager.go
- internal/providers/pke/pkeworkflow/create_master_activity.go
- internal/providers/pke/pkeworkflow/update_master_node_group_activity.go
- internal/providers/pke/pkeworkflow/update_node_group_activity.go
| Related tickets | https://github.com/banzaicloud/pipeline-enterprise/pull/123
Add the possibility to update the PKE master node pool.
> pke: update master workflow

- pkg/sdk/go.sum
Updated the `pkg/sdk` dependencies using `go mod tidy`.
While I was working on #3223 I noticed a lot of changes in the `go.sum` file.
I decided to stash my changes and check out a fresh branch from the latest origin/master state to see if I brought the changes and after running `go mod tidy` it turned out these dependency packages were already outdated before my changes.
Issue for adding CI check on dependency versions: #3230.
Reproduction:
```shell
git fetch --prune --prune-tags
git checkout -b <test-branch-name> origin/master
cd pkg/sdk
go mod tidy
```
- ~Implementation tested (with at least one …
> chore(SDK): updated dependencies

- internal/cluster/distribution/eks/service.go
- internal/cluster/distribution/eks/service_test.go
| Related tickets | resolves #3237 
Modified the EKS "node pool with deleted stack status" node pool status to `DELETED` from `DELETING`.
This state can happen by manually deleting the stack behind Pipeline's back when the listing should show the proper node pool status of being already deleted.
Manual testing involves creating an EKS cluster, deleting a node pool's CF stack manually and issuing a node pool list request.
<details>
<summary>Manually deleted CF stack</summary>
```shell
> banzai cluster create --file ~/banzai_cluster_create.yaml 
? Do you want a recommendation on your node groups? No
The current state of the …
```
> Fixed EKSListNodePools's deleted stack status

- internal/platform/gin/ginauth/middleware.go
- internal/platform/gin/ginauth/middleware_test.go
- src/auth/authz.go
- src/auth/authz_test.go
> improve pke token authorization

- docker-compose.yml
1.7.0 has the fix for the docker-compose stop issue.
> use bank-vaults 1.7.0

- .circleci/config.yml
Docker image build has been moved to GHA.
> circleci: remove docker image build

- go.mod
- go.sum
| Related tickets | backports #3208 to 0.60.x
> Upgrade mapstructure

- internal/cluster/distribution/eks/ekscluster/eks.go
- internal/cluster/distribution/eks/image_selector_defaults.go
| Related tickets | fixes #3256 , related: https://github.com/banzaicloud/cloudinfo/pull/383
Add EKS 1.18 support
> EKS 1.18 support

- cmd/pipeline/main.go
- internal/cmd/config.go
- internal/integratedservices/service_v2.go
> Introduce the Integrated Service v2 skeleton - development purposes only

- cmd/worker/eks.go
Remove extra registration of DeleteStackActivity.
> Fix - Remove DeleteStackActivity registration from eks.

- src/auth/token.go
> auth: handle ExpiresAt correctly even if set but 0

- go.mod
- go.sum
| Related tickets | #3288 
Display a proper error message if user token is not present in the store.
> update gin-utilz to v0.3.1

- .gen/pipeline/api/openapi.yaml
- apis/pipeline/pipeline.yaml
- config/config.yaml.dist
- internal/clustergroup/deployment/integration_test.go
- internal/cmd/config.go
- internal/federation/reconcile_ext_dns_test.go
- internal/helm/integration_test.go
- internal/helm/releaser_service_integration_test.go
- internal/helm/service_test.go
> Switch to read-only stable chart repo

- config/config.yaml.dist
- internal/cmd/config.go
Update cluster autoscaler config with new Kubernetes versions.
> Update cluster autoscaler config

- internal/cluster/distribution/eks/eksprovider/workflow/awsmocks/zz_generated.mock.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_infra.go
- internal/cluster/distribution/eks/eksprovider/workflow/delete_infra_test.go
- lib/cadence-aws-sdk/clients/ec2stub/interface.go
- lib/cadence-aws-sdk/clients/ec2stub/stub.go
> Update Cadence AWS SDK

- internal/ark/backups_model.go
Fix possible nil problem when listing backups from db
> cluster backup: fix possible nil issue

- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
Added return statements for generic errors during EKS node pool update process.
Without this, non-specific errors such as validation issues fail silently and the workflow continues to run, except the wait for update completion activity is never going to finish until it reaches its timeout/retry boundaries.
> fix(EKS/UpdateNP): handle all error kinds

- internal/helm/helmadapter/helm_service.go
Fixed (platform) helm repo addition logic in case of cluster federation
The helm repo addition logic was wrong (only in case of cluster federation) as it 
only checked the repository URL
> Fix platform helm repo addition logic

- internal/cluster/distribution/eks/eksprovider/driver/cluster_updater.go
- src/cluster/eks_update_cluster.go
Simplified `ClusterAPI.EKS.UpdateCluster` node pool deletion logic.
During the previous refactor of introducing DeleteNodePoolWorkflow I missed the chance to simplify the node pool deletion in `ClusterAPI.EKS.UpdateCluster`. I'm fixing that mistake here.
> refactor(ClAPI.UCl): simplified node pool deletion

- charts/pipeline/templates/service.yaml
- charts/pipeline/values.yaml
- cmd/pipeline/config.go
- cmd/pipeline/main.go
- config/config.yaml.dist
- src/api/cluster.go
- src/auth/authn.go
Remove unused internal node pool management API.
We don't use it anymore and we don't want to keep maintaining it.
> Remove internal api

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_eks_update_node_pool_request.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request_all_of.go
- .gen/pipeline/pipeline/model_update_node_pool_request.go
- apis/pipeline/pipeline.yaml
- internal/cluster/distribution/eks/eksadapter/node_pool_manager.go
- internal/cluster/distribution/eks/eksworkflow/activity_calculate_node_pool_version.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
- internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
- internal/cluster/distribution/eks/service.go
| Related tickets | fixes #3324 
Add securityGroups input param to node pool update.
Tested with suggested scenarios by @pregnor.
> Add securityGroups input param to node pool update

- templates/eks/amazon-eks-nodepool-cf.yaml
See #3349.
To fix minor release version.
> Backported #3349

- .github/workflows/is-test-v2.yml
- Makefile
- internal/integratedservices/functional_helpers_test.go
- internal/integratedservices/functional_suite_test.go
- internal/integratedservices/functional_test.go
- internal/integratedservices/integratedserviceadapter/customresource_repository.go
- internal/integratedservices/services/dns/operator.go
- internal/integratedservices/services/dns/operator_v2.go
- internal/integratedservices/services/dns/secretmapper.go
- internal/integratedservices/services/dns/spec.go
- internal/integratedservices/testconfig/config-v2.yaml
Test framework changes and a new workflow to run Integrated Service tests for the new v2 code path as well.
> Integrated service testing for v2 functionalities

- docker-compose.yml
Upgrades the dex-shim that contains an updated version of dex
> Upgrade the dex shim container

- internal/integratedservices/servicerouter.go
- internal/integratedservices/servicerouter_test.go
The PR contains an implementation of the integrated service interface that routes incoming requests to the appropriate service implementation (legacy or v2)
Preparation for switching to the new version of integrated services
The router service is not wired into the application so it doesn't affect the current version of pipeline
> Integrated service router implementation

- internal/integratedservices/integratedserviceadapter/customresource_repository.go
Return explicit error message for GetDetails
Return empty result for List
The list of integrated services will be merged based on the results of the v1 and v2 integrated services. If the CRD for the v2 integrated services is missing that simply means there are no v2 integrated services enabled, thus we want to avoid bailing out with an error.
However in case of the `getDetails` api call it's more useful for clients to return a more informal error instead of the ambiguous "something went wrong".
> fix: Handle missing integrated service CRD on GetDetails and List API calls

- internal/cluster/distribution/pke/pkeaws/pkeaws.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
- src/api/cluster/pke/pkeservice/service.go
- src/api/cluster/pke/pkeservice/service_test.go
* Use PKE version that send progress reports to pipeline
* Fix an error preventing the report's propagation
> Activate PKE installation progress reports

- internal/integratedservices/services/dns/operator.go
- internal/integratedservices/services/dns/operator_v2.go
| Related tickets | fixes #3401
aws credentials secret is stored in the aws credentials file format
the external dns component requires credentials stored in the above format
(previously credentials were stored in json format)
> refactor: allow aws secret values in credentials file format

- .github/workflows/git.yaml
Added auto merge commit rejecter check to GHA workflows.
Because it is difficult to track code/commit integration in a repository with rebase merge strategy - which we are currently using.
Thus we would like to change from rebase merge strategy to (optionally squash) merge commit strategy.
But we do not want to pollute the commit history with "Merge branch 'master' into my-little-feature-branch" and "Merge pull request #123456789 from organization/my-feature-branch" automatic commits from the "Update branch" button and subpar multiple feature branch handling.
In order to avoid the noise, the best …
> Added auto merge commit rejecter check to GHA workflows

- config/config.yaml.dist
Consolidated velero chart config example to [in-code default value](https://github.com/banzaicloud/pipeline/blob/0c6446d6ff4126e04f3aee2d83c489fb78267143/internal/cmd/config.go#L789).
To keep the config file and in-code values in sync.
> Consolidated velero chart config file example to in-code default value

- internal/cmd/config.go
| Related tickets | related: https://github.com/banzaicloud/anchore-image-validator/pull/72, https://github.com/banzaicloud/anchore-image-validator/pull/74
Use new anchore-image-validator
> Security scan: bump chart version

- .plzconfig
> build: upgrade please

- internal/cluster/distribution/pke/pkeaws/pkeaws.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
> Bump PKE version (cilium fix)

- docker-compose.yml
Upgraded Cadence local server 0.14.1->0.15.1.
Converging towards the latest available version.
> Upgraded Cadence local server 0.14.1->0.15.1

- docker-compose.yml
Upgraded local dev env Cadence server to 0.16.1.
Converging towards latest version.
> Upgraded local dev env Cadence server to 0.16.1

- .plzconfig
- internal/cluster/clusterbase/BUILD.plz
- internal/cluster/clusterconfig/BUILD.plz
- internal/cluster/metrics/BUILD.plz
- internal/common/BUILD.plz
- internal/database/sql/json/BUILD.plz
- internal/global/nplabels/BUILD.plz
- internal/integratedservices/services/dns/externaldns/BUILD.plz
- internal/network/BUILD.plz
- internal/secret/BUILD.plz
- internal/secret/secrettype/BUILD.plz
- pkg/cloud/BUILD.plz
- pkg/cluster/kubernetes/BUILD.plz
- pkg/ctxutil/BUILD.plz
- pkg/errors/BUILD.plz
- pkg/helm/BUILD.plz
- pkg/mirror/BUILD.plz
- pkg/sdk/providers/amazon/BUILD.plz
- pkg/security/BUILD.plz
- src/helm/BUILD.plz
Update please and related tools
> Please updates

- docker-compose.yml
Upgraded Cadence dev server 0.16.1->0.17.0
Converging towards the latest version.
Tested locally according to the upgrade guide.
> Upgraded Cadence dev server 0.16.1->0.17.0

- .github/workflows/ci.yml
Fixed a copy-paste typo.
To make the error message correct.
- ~Related Helm chart(s) updated (if needed)
> Fixed a copy-paste typo

- internal/cluster/distribution/pke/pkeaws/pkeaws.go
- internal/providers/azure/pke/driver/cluster_creator.go
- internal/providers/vsphere/pke/driver/cluster_creator.go
| Related tickets | https://github.com/banzaicloud/pke/pull/143
> fix: update pke version

- .github/dependabot.yml
| Related tickets | partially #3508 
Fix dependapot.yml config file.
> fix dependeabot config

- .github/workflows/ci.yml
- pkg/sdk/go.mod
- pkg/sdk/go.sum
Upgraded pkg/sdk module Go version to 1.16.
To use the latest available minor version.
Also fixing an incorrect workaround config.
> Upgraded pkg/sdk module Go version to 1.16

- .github/workflows/scan-images.yml
- docker.images.list
| Related tickets | fixes #3506
Create a manually trigger-able Github action to run security scan on images deploymed by Pipeline.
> GitHub scan

- internal/ark/backups_model.go
- internal/ark/sync/backups_sync_svc.go
- internal/ark/sync/buckets_sync_svc.go
| Related tickets | fixes #3511 
Disable downloading content of nodes from object store when syncing Velero backups to Pipeline db.
When syncing Velero backups, currently Pipeline downloads the content of backups from object storage, more specifically the list of all nodes of the cluster at the time of backup. This sometimes could be quite huge causing problems when persisting to db.
> Velero backup sync: Disable downloading nodes content from objectstore

- docker-compose.yml
Upgraded local development Cadence server 0.18.2,web 3.26.0.
Converging towards latest version.
> Upgraded local development Cadence server 0.18.2,web 3.26.0

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/pipeline/model_eks_node_pool_all_of.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request.go
- .gen/pipeline/pipeline/model_eks_update_node_pool_request_all_of.go
- .gen/pipeline/pipeline/model_node_pool.go
- .gen/pipeline/pipeline/model_node_pool_summary.go
- .gen/pipeline/pipeline/model_update_node_pool_request.go
- apis/pipeline/pipeline.yaml
- internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
- internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
- internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
| Related tickets | [-
Changed default volume type gp2->gp3
GP3 is better, cheaper (on default IOPS and throughput) and newer.
Builds on top of #3532.
> Changed default volume type gp2->gp3

- docker-compose.yml
Converging towards latest version.
Updated Cadence local server 0.18.2->0.19.2.
Converging towards latest version.
> Updated Cadence local server 0.18.2->0.19.2

- src/auth/authn.go
Fixed SyncOrgsForUser OIDC provider setting.
The lack of it broke the user org sync.
> Fixed SyncOrgsForUser OIDC provider setting

- README.md
Removed GoReportCard from Readme.
It cannot run due to issues but we don't have the capacity to debug it right now.
> Removed GoReportCard from Readme

- docker-compose.yml
Upgraded dev Cadence server 0.19.2->0.20.0.
To converge towards the latest version.
> Upgraded dev Cadence server 0.19.2->0.20.0

- docker-compose.yml
Updated dev env Cadence to server 0.21.3, web 3.27.0
To be on the latest version.
Tested using the upgrade guide.
> Updated dev env Cadence to server 0.21.3, web 3.27.0

- charts/pipeline/Chart.yaml
- charts/pipeline/values.yaml
Replaced chart images docker.io->ghcr.io.
To use the GitHub container repository and avoid being rate limited on certain internal services.
> Replaced chart images docker.io->ghcr.io, chart 1.4.0

- charts/pipeline/Chart.yaml
Updated Helm chart versions to 0.77.1, 1.4.1.
To use the latest Pipeline version.
> Updated Helm chart versions to 0.77.1, 1.4.1

- docs/developer.md
- docs/velero-backup.md
Add Velero backup test steps to Dev docs.
> add velero backup test to dev docs

- docs/auth/github.md
- docs/developer.md
Updates in the developer docs to reflect the change from `make` to `please` as the build system and also some additional information.
> docs: update developer documentation

- .plzconfig
Updating our build sytem of choice, `please` to its latest release (`16.0.1` -> `16.9.0`).
I tried the most common targets (up, down, build, run pipeline and worker) and it worked fine.
To make sure you use the latest version, run `please --version`.
> chore: update please version to latest release

- charts/pipeline/values.yaml
- config/config.yaml.dist
- internal/cmd/config.go
Consolidating Pipeline config YAML and default config usage:
- add missing values to `config.go`
- update the current chart version numbers in `config.yaml.dist`
- add some commentet out sections to the pipeline chart `values.yaml`.
Most of these changes were missed or forgot to make during previous changes, now the default configs are showing a much clearer picture.
- ~[] OpenAPI and Postman files updated (if needed)~
- ~[] User guide and development docs updated (if needed)~
> Consolidate default config usage

- charts/pipeline/Chart.yaml
Released Helm chart 1.4.3 (Pipeline 0.79.0).
To use the latest Pipeline version with the latest chart version.
> Released Helm chart 1.4.3 (Pipeline 0.79.0)

- .circleci/config.yml
Kind version update in CircleCI config as we move formward with kubernetes and helm upgrades.
So the CircleCI job can run in a more up-to-date environment.
> Updated .circleci/config.yml

- .plzconfig
Updated please (plz) version 16.9.0->16.18.0.
To use the latest please (plz) version.
Tested locally with some common targets.
> Updated please version 16.9.0->16.18.0

- src/cluster/ec2_pke.go
Added node pool validation for PKE distribution on AWS.
It was only implemented for EKS in #3592.
> Added PKE node pool name validation

- config/config.yaml.dist
- docker.images.list
- internal/cmd/config.go
Updated nodepool-labels-operator 0.1.1->0.1.2, chart 0.2.5->0.2.6
Updated instance-termination-handler 0.1.1->0.1.2, chart 0.1.1->0.1.2
To fix vulnerabilities from older version of gin in these packages.
> Updated packages with vulnerabilities

- templates/eks/amazon-eks-nodepool-cf.yaml
Updated nodepool Cloudformation template with EKS 1.22.
To be in sync with the latest official node pool template from AWS.
> Updated node pool CF template with EKS 1.22

- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- src/cluster/eks.go
Reverts banzaicloud/pipeline#3621
> Revert "Updated client.authentication.k8s.io version"

- config/config.yaml.dist
- docker.images.list
- internal/cmd/config.go
- instance-termination-handler app and chart version 0.1.2->0.1.3
- nodepool-labels-operator app version v0.1.2->v0.2.0, chart version 0.2.6->0.2.7
To use the latest versions
> Updated ITH and NPLS versions

- charts/pipeline/Chart.yaml
- charts/pipeline/values.yaml
Released Helm chart 1.4.1->1.4.2 with image 0.78.0.
To use the latest available image.
> Released Helm chart 1.4.4->1.4.5 (0.81.0)

- .github/workflows/helm.yml
Fixed chart path in helm release workflow.
For the charts to be successfully released on chart tags by Github Actions.
> Fixed chart path in helm release workflow

- internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
- src/cluster/eks.go
Reverts banzaicloud/pipeline#3633
> Revert "fix(EKS,Authn): fixed aws-iam-authn apiversion"

- src/cluster/gke.go
GKE 1.24 ServiceAccount default token usage fix.
Default created SA tokens were removed in 1.24 and GKE needs one in the current implementation, replacing it with a manually created one for now for a drop-in replacement implementation.
> fix(GKE,1.24): fixed SA token

- docker-compose.yml
Updated Cadence server 0.22.1->0.23.2, web v3.28.7->v3.29.5
Converging towards latest supported version.
> Cadence server 0.23.2, web 3.29.5

- charts/pipeline/Chart.yaml
- charts/pipeline/templates/NOTES.txt
- charts/pipeline/templates/ingress.yaml
- charts/pipeline/values.yaml
- made Ingress chart template work with all (including the latest) K8s versions.
- bumped app and chart versions
> Updated Helm chart 1.4.5->2.0.0 and Ingress template

- .github/workflows/helm.yml
Fixed GHA Helm version check to exactly match chart name.
To avoid mismatching other chart's versions.
> ci(GHA): fixed Helm version check

- internal/cmd/config.go
Switched from deprecated grafana helm repo for `loki` to the currently used one.
> Switched grafana helm repo
